// ProfeECEP 2.8.7 — expansión basada en temarios y formato oficial público
(function () {
  'use strict';

  const packs = {};
  const sources = {
    current: 'https://www.evaluacionconocimientos.cl/',
    previous: 'https://www.cpeip.cl/sistema-reconocimiento/',
    released: 'https://www.cpeip.cl/ya-estan-disponibles-las-pruebas-ecep-2017-al-2020/'
  };

  function syllabusFor(specialtyId) {
    return specialtyId === 'basica-matematica'
      ? window.ECEP_DATA || []
      : (window.PE_SYLLABUS_2026 && window.PE_SYLLABUS_2026[specialtyId]) || [];
  }

  function make(specialtyId, index, item) {
    const syllabus = syllabusFor(specialtyId);
    const domain = syllabus[item.di] || ['', []];
    const subdomain = domain[1][item.si] || ['', []];
    const indicator = subdomain[1][item.ii] || '';
    const options = item.o.slice(0, 4);
    const explanations = options.map((option, optionIndex) => optionIndex === item.a
      ? item.e
      : 'Esta alternativa no responde de manera completa al indicador o confunde una relación relevante del problema.');
    return {
      id: specialtyId + '-287-' + String(index + 1).padStart(2, '0'),
      d: domain[0],
      i: subdomain[0],
      q: item.q,
      o: options,
      a: item.a,
      e: item.e,
      explanations,
      diff: item.diff || (index % 3 === 0 ? 'básica' : index % 3 === 1 ? 'media' : 'alta'),
      skill: item.skill || 'razonamiento aplicado',
      specialtyId,
      indicatorId: [item.di, item.si, item.ii].join('-'),
      indicator,
      questionType: item.type || 'aplicación de indicador',
      origin: 'Pregunta original ProfeECEP',
      sourceNote: 'Inspirada en temarios y formato público ECEP/CPEIP; no es una pregunta oficial ni filtrada.',
      version: '2.8.7'
    };
  }

  function addPack(specialtyId, items) {
    packs[specialtyId] = items;
  }

  addPack('basica-matematica', [
    {di:0,si:0,ii:0,q:'Un número natural es divisible por 2 y por 3, pero no por 5. ¿Cuál podría ser?',o:['6','10','15','25'],a:0,e:'6 es divisible por 2 y por 3, y no es divisible por 5.',diff:'básica',skill:'divisibilidad'},
    {di:0,si:0,ii:1,q:'¿Cuál es el orden de menor a mayor?',o:['-0,75 < -1/2 < 0,2 < 3/4','-1/2 < -0,75 < 0,2 < 3/4','-0,75 < 0,2 < -1/2 < 3/4','3/4 < 0,2 < -1/2 < -0,75'],a:0,e:'-0,75 es menor que -0,5; luego siguen 0,2 y 0,75.',diff:'media',skill:'comparación de racionales'},
    {di:0,si:0,ii:2,q:'Una botella contiene 3/4 de litro y se usan 2/5 de litro. ¿Cuánto queda?',o:['1/20 L','7/20 L','9/20 L','11/20 L'],a:1,e:'3/4−2/5=15/20−8/20=7/20 de litro.',diff:'media',skill:'operaciones con racionales'},
    {di:0,si:1,ii:0,q:'En una tabla, x toma los valores 2, 4 y 6, mientras y toma 5, 10 y 15. ¿Qué expresión representa la relación?',o:['y=x+3','y=2,5x','y=5x+2','y=x/2'],a:1,e:'El cociente y/x es constante e igual a 2,5; por eso y=2,5x.',diff:'media',skill:'representaciones proporcionales'},
    {di:0,si:1,ii:1,q:'¿Cuál situación no representa una relación directamente proporcional?',o:['El precio de fruta a $1.200 por kilogramo','La distancia recorrida a rapidez constante','El costo de un taxi con bajada de bandera y cobro por kilómetro','La cantidad de agua en botellas iguales'],a:2,e:'La bajada de bandera es un costo fijo; por eso el costo no es proporcional a cero kilómetros.',diff:'alta',skill:'relaciones proporcionales'},
    {di:0,si:1,ii:2,q:'Cuatro trabajadores terminan una tarea en 15 días. Si trabajan seis al mismo ritmo, ¿cuántos días tardarán?',o:['8 días','10 días','12 días','18 días'],a:1,e:'El trabajo total equivale a 4×15=60 jornadas; 60÷6=10 días.',diff:'alta',skill:'proporcionalidad inversa'},
    {di:0,si:1,ii:3,q:'El 30% de una cantidad es 24. ¿Cuál es la cantidad?',o:['54','72','80','96'],a:2,e:'24 representa 0,30 de la cantidad; 24÷0,30=80.',diff:'media',skill:'porcentajes'},
    {di:0,si:2,ii:0,q:'¿Cuál es el resultado de (−2)^3+2^2?',o:['−12','−4','4','12'],a:1,e:'(−2)^3=−8 y 2^2=4; la suma es −4.',diff:'media',skill:'potencias'},
    {di:0,si:2,ii:1,q:'¿Cuál es el valor de (3/4)^2?',o:['3/8','6/8','9/16','12/16'],a:2,e:'Se elevan numerador y denominador: (3/4)^2=9/16.',diff:'básica',skill:'potencias fraccionarias'},
    {di:1,si:0,ii:0,q:'La secuencia 4, 7, 10, 13,… mantiene una diferencia constante. ¿Cuál es su término número 12?',o:['34','37','40','43'],a:1,e:'El término general es 3n+1; para n=12 resulta 37.',diff:'media',skill:'regularidades'},
    {di:1,si:0,ii:1,q:'¿Qué expresión representa “el doble de un número aumentado en 5”?',o:['2x+5','2(x+5)','x+10','5−2x'],a:1,e:'Primero se aumenta el número en 5 y luego se multiplica todo por 2: 2(x+5).',diff:'media',skill:'traducción algebraica'},
    {di:1,si:0,ii:2,q:'¿Qué expresión representa el 25% de una cantidad x?',o:['25x','x/25','x/4','4x'],a:2,e:'25%=25/100=1/4, por lo que el resultado es x/4.',diff:'básica',skill:'modelación algebraica'},
    {di:1,si:1,ii:0,q:'Un cuaderno y tres lápices cuestan $2.300. Cada lápiz cuesta $400. ¿Qué ecuación permite hallar el precio x del cuaderno?',o:['x+400=2.300','3x+400=2.300','x+3·400=2.300','x−3·400=2.300'],a:2,e:'El costo total es el cuaderno más tres lápices de $400: x+3·400=2.300.',diff:'media',skill:'modelación con ecuaciones'},
    {di:1,si:1,ii:1,q:'Una persona dispone de $12.000 y cada entrada cuesta $2.500. ¿Cuál es la mayor cantidad de entradas que puede comprar?',o:['3','4','5','6'],a:1,e:'4 entradas cuestan $10.000; 5 costarían $12.500 y superarían el presupuesto.',diff:'media',skill:'inecuaciones'},
    {di:1,si:1,ii:2,q:'¿Cuál es la solución de x/3+2=7?',o:['x=5','x=9','x=15','x=21'],a:2,e:'Restando 2 queda x/3=5; multiplicando por 3, x=15.',diff:'básica',skill:'resolución de ecuaciones'},
    {di:1,si:2,ii:0,q:'La función f(x)=√(x−1) está definida para qué valores de x?',o:['x≥1','x>1','x≤1','Todos los números reales'],a:0,e:'El radicando debe ser no negativo: x−1≥0, por lo tanto x≥1.',diff:'alta',skill:'dominio'},
    {di:1,si:2,ii:1,q:'El consumo de electricidad de una casa depende de la cantidad de horas que funcionan sus artefactos. ¿Cuál es la variable dependiente?',o:['La cantidad de horas','El consumo de electricidad','El precio de cada artefacto','El nombre de la casa'],a:1,e:'El consumo cambia según las horas de funcionamiento, por lo que depende de ellas.',diff:'básica',skill:'variables'},
    {di:1,si:2,ii:2,q:'En y=−3x+12, ¿qué representa el número 12?',o:['La pendiente','El dominio','La intersección con el eje y','La variable independiente'],a:2,e:'En y=mx+b, b es la intersección con el eje y; aquí b=12.',diff:'básica',skill:'parámetros de funciones'},
    {di:1,si:2,ii:3,q:'Un taxi cobra $1.500 de bajada de bandera y $800 por cada kilómetro. ¿Qué función modela el costo y para x kilómetros?',o:['y=1.500x+800','y=800x','y=1.500+800x','y=2.300x'],a:2,e:'El costo fijo es 1.500 y se suma a 800 por cada kilómetro: y=1.500+800x.',diff:'media',skill:'modelación funcional'},
    {di:2,si:0,ii:0,q:'¿Cuál conjunto de longitudes no puede formar un triángulo?',o:['3 cm, 4 cm y 5 cm','5 cm, 5 cm y 8 cm','3 cm, 4 cm y 8 cm','6 cm, 7 cm y 10 cm'],a:2,e:'3+4=7 no supera a 8, por lo que no se cumple la desigualdad triangular.',diff:'media',skill:'construcción de triángulos'},
    {di:2,si:0,ii:1,q:'Un cuerpo tiene seis caras rectangulares, con caras opuestas iguales. ¿Cómo se clasifica?',o:['Pirámide','Prisma rectangular','Cilindro','Cono'],a:1,e:'Un prisma rectangular tiene seis caras rectangulares y sus caras opuestas son congruentes.',diff:'básica',skill:'clasificación de cuerpos'},
    {di:2,si:0,ii:2,q:'¿Cuántos ejes de simetría tiene un hexágono regular?',o:['3','4','6','12'],a:2,e:'Cada vértice y cada lado opuesto determinan un eje; el hexágono regular tiene seis.',diff:'media',skill:'simetría'},
    {di:2,si:0,ii:3,q:'¿Cuál es la suma de los ángulos interiores de un pentágono?',o:['360°','540°','720°','900°'],a:1,e:'La suma es (5−2)·180°=540°.',diff:'media',skill:'propiedades de polígonos'},
    {di:2,si:0,ii:4,q:'Una circunferencia tiene radio 4 cm. ¿Cuánto mide su diámetro?',o:['2 cm','4 cm','8 cm','16 cm'],a:2,e:'El diámetro es el doble del radio: 2·4=8 cm.',diff:'básica',skill:'circunferencia'},
    {di:2,si:1,ii:0,q:'Un rectángulo mide 9 cm de largo y 4 cm de ancho. ¿Cuál es su perímetro?',o:['13 cm','26 cm','36 cm','40 cm'],a:1,e:'P=2(9+4)=26 cm.',diff:'básica',skill:'perímetro'},
    {di:2,si:1,ii:1,q:'Un prisma rectangular mide 3 cm, 4 cm y 5 cm. ¿Cuál es su volumen?',o:['12 cm³','20 cm³','47 cm³','60 cm³'],a:3,e:'V=3·4·5=60 cm³.',diff:'básica',skill:'volumen'},
    {di:2,si:1,ii:2,q:'Entre rectángulos de perímetro 20 cm, ¿cuál tiene mayor área?',o:['1 cm×9 cm','2 cm×8 cm','4 cm×6 cm','5 cm×5 cm'],a:3,e:'Sus áreas son 9, 16, 24 y 25 cm²; el cuadrado de 5×5 maximiza el área.',diff:'alta',skill:'familias de figuras'},
    {di:2,si:1,ii:3,q:'Una figura en forma de L se obtiene de un rectángulo de 10×6 cm al quitar un rectángulo de 4×2 cm. ¿Cuál es su área?',o:['44 cm²','48 cm²','52 cm²','60 cm²'],a:2,e:'El área restante es 10·6−4·2=60−8=52 cm².',diff:'media',skill:'áreas compuestas'},
    {di:2,si:2,ii:0,q:'¿Qué propiedad se conserva necesariamente cuando dos figuras son congruentes?',o:['Solo el color','Las distancias correspondientes','La posición en el plano','El sentido de orientación'],a:1,e:'La congruencia conserva lados, ángulos y distancias correspondientes.',diff:'media',skill:'congruencia'},
    {di:2,si:2,ii:1,q:'El punto (1,2) se rota 90° en sentido horario alrededor del origen. ¿Cuál es su imagen?',o:['(−2,1)','(2,−1)','(−1,−2)','(1,−2)'],a:1,e:'Una rotación horaria de 90° transforma (x,y) en (y,−x): (1,2)→(2,−1).',diff:'alta',skill:'rotaciones'},
    {di:2,si:2,ii:2,q:'El patrón de alas de una mariposa puede modelarse principalmente mediante una:',o:['Reflexión','Traslación','Homotecia','Descomposición'],a:0,e:'Las alas presentan una correspondencia bilateral que puede representarse mediante una reflexión.',diff:'básica',skill:'transformaciones en la naturaleza'},
    {di:3,si:0,ii:0,q:'En una encuesta, las categorías A y B registran 12 y 18 respuestas, respectivamente. ¿En cuánto supera B a A?',o:['6','12','18','30'],a:0,e:'La diferencia es 18−12=6 respuestas.',diff:'básica',skill:'interpretación de gráficos'},
    {di:3,si:0,ii:1,q:'Los datos son 2, 4, 4, 6 y 9. ¿Cuál es la moda?',o:['2','4','5','9'],a:1,e:'4 es el único valor que se repite y aparece con mayor frecuencia.',diff:'básica',skill:'tendencia central'},
    {di:3,si:0,ii:2,q:'Un conjunto tiene un valor extremadamente alto. ¿Qué medida suele verse más afectada?',o:['La media','La mediana','La moda siempre','El número de categorías'],a:0,e:'La media incorpora todos los valores y es sensible a valores extremos.',diff:'media',skill:'selección de indicador'},
    {di:3,si:0,ii:3,q:'Un estudio encuesta a 80 de los 1.200 estudiantes de una escuela. ¿Qué representan los 80 encuestados?',o:['La población','La muestra','La variable','El parámetro'],a:1,e:'La muestra es el subconjunto de personas observado dentro de la población.',diff:'básica',skill:'población y muestra'},
    {di:3,si:1,ii:0,q:'Al lanzar dos monedas, ¿cuántos resultados ordenados forman el espacio muestral?',o:['2','3','4','6'],a:2,e:'Cada moneda tiene 2 resultados y 2·2=4 pares ordenados.',diff:'básica',skill:'espacio muestral'},
    {di:3,si:1,ii:1,q:'En 100 lanzamientos, una moneda mostró cara 57 veces. ¿Cuál es la frecuencia relativa de cara?',o:['0,43','0,50','0,57','57'],a:2,e:'La frecuencia relativa es 57/100=0,57.',diff:'media',skill:'frecuencia relativa'},
    {di:3,si:1,ii:2,q:'Se elige una camiseta entre 3 colores y un pantalón entre 2 colores. ¿Cuántas combinaciones hay?',o:['5','6','8','9'],a:1,e:'El principio multiplicativo entrega 3·2=6 combinaciones.',diff:'media',skill:'principio multiplicativo'},
    {di:3,si:1,ii:3,q:'Se lanza un dado justo. ¿Cuál es la probabilidad de obtener un número mayor que 4?',o:['1/6','1/3','1/2','2/3'],a:1,e:'Los casos favorables son 5 y 6: 2/6=1/3.',diff:'básica',skill:'modelo de Laplace'},
    {di:4,si:0,ii:0,q:'Para introducir la proporcionalidad directa, ¿qué secuencia favorece mejor la comprensión?',o:['Fórmula, memorización y prueba','Situación contextualizada, tabla o gráfico y expresión simbólica','Solo ejercicios rutinarios','Definición escrita y copia'],a:1,e:'Transitar desde una situación y sus representaciones hacia el símbolo construye significado.',diff:'media',skill:'estrategias de enseñanza',type:'decisión pedagógica'},
    {di:4,si:0,ii:1,q:'Para comprender fracciones equivalentes, ¿qué representación es más pertinente al inicio?',o:['Una lista de reglas','Diagramas que muestran la misma cantidad dividida de distintas maneras','Solo números decimales','Una prueba sumativa'],a:1,e:'Las representaciones visuales permiten observar que distintas fracciones pueden expresar la misma cantidad.',diff:'básica',skill:'representaciones de contenidos',type:'decisión pedagógica'},
    {di:4,si:0,ii:2,q:'Dos estudiantes resuelven un problema con estrategias distintas y ambas son válidas. ¿Qué intervención favorece mejor el aprendizaje?',o:['Exigir un único método','Comparar y justificar las estrategias','Corregir la más lenta','Evitar la puesta en común'],a:1,e:'Comparar estrategias permite analizar validez, eficiencia y conexiones entre procedimientos.',diff:'alta',skill:'intervención docente',type:'decisión pedagógica'},
    {di:4,si:0,ii:3,q:'Al elegir un simulador digital para la clase, ¿qué criterio debe guiar la decisión?',o:['Que sea novedoso','Que tenga muchas animaciones','Que apoye el objetivo y haga visible el razonamiento','Que reemplace toda explicación'],a:2,e:'La pertinencia depende de su alineación con el objetivo y la evidencia esperada.',diff:'media',skill:'selección de recursos',type:'decisión pedagógica'},
    {di:4,si:0,ii:4,q:'Si el énfasis curricular es argumentar, ¿qué actividad está mejor alineada?',o:['Copiar una definición','Resolver y justificar por qué funciona una estrategia','Memorizar fórmulas','Ordenar ejercicios por longitud'],a:1,e:'Explicar y justificar una estrategia entrega evidencia directa de argumentación matemática.',diff:'media',skill:'énfasis curricular',type:'decisión pedagógica'},
    {di:4,si:0,ii:5,q:'Un grupo se bloquea al resolver problemas porque no identifica los datos relevantes. ¿Qué apoyo es más adecuado?',o:['Darles la respuesta','Modelar cómo representar la situación y formular preguntas guía','Cambiar siempre los números','Evaluar solo el resultado'],a:1,e:'Las preguntas guía y la representación ayudan a identificar relaciones sin quitar el desafío.',diff:'alta',skill:'dificultades de aprendizaje',type:'decisión pedagógica'},
    {di:4,si:1,ii:0,q:'Al iniciar ecuaciones lineales, ¿qué saber previo permite transformar ambos miembros de manera equivalente?',o:['Nombres de polígonos','Igualdad y operaciones inversas','Clasificación de gráficos','Unidades de volumen'],a:1,e:'Comprender la igualdad y las operaciones inversas sustenta las transformaciones equivalentes.',diff:'media',skill:'conocimientos previos',type:'análisis pedagógico'},
    {di:4,si:1,ii:1,q:'Un estudiante calcula A=2(largo+ancho) como área de un rectángulo. ¿Qué confusión revela?',o:['Área y perímetro','Volumen y capacidad','Media y mediana','Fracción y decimal'],a:0,e:'2(largo+ancho) corresponde al perímetro; el área se calcula multiplicando largo por ancho.',diff:'básica',skill:'aprendizaje desde el error',type:'análisis pedagógico'},
    {di:4,si:2,ii:0,q:'Si el indicador exige justificar un procedimiento, ¿qué evidencia es más pertinente?',o:['Elegir verdadero o falso sin explicar','Resolver una tarea y argumentar por qué la estrategia funciona','Copiar fórmulas','Registrar solo el tiempo'],a:1,e:'La justificación requiere que el estudiante haga visible y fundamente su razonamiento.',diff:'media',skill:'indicadores y desempeños',type:'evaluación'},
    {di:4,si:2,ii:1,q:'Para valorar cómo una estudiante defiende oralmente su estrategia matemática, ¿qué instrumento conviene usar?',o:['Una rúbrica con criterios de razonamiento y comunicación','Solo una lista de asistencia','Una escala de velocidad','Una prueba sin espacio de explicación'],a:0,e:'La rúbrica permite observar criterios de razonamiento y comunicación de manera explícita.',diff:'alta',skill:'instrumentos de evaluación',type:'evaluación'}
  ]);
  addPack('basica-ciencias', [
    {di:0,si:0,ii:0,q:'Una tira de papa se coloca en una solución de sal muy concentrada y pierde masa. ¿Qué proceso explica mejor el resultado?',o:['Ósmosis de agua hacia la solución','Transporte activo de sal hacia la papa','Endocitosis de agua','Síntesis de proteínas'],a:0,e:'El agua sale de las células hacia el medio más concentrado por ósmosis, un transporte pasivo.',diff:'media',skill:'intercambio celular'},
    {di:0,si:0,ii:1,q:'¿Qué característica de los fosfolípidos permite formar una bicapa estable en la membrana celular?',o:['Poseen una zona hidrofílica y otra hidrofóbica','Son completamente solubles en agua','Tienen carga positiva en todas sus partes','Se unen mediante enlaces peptídicos'],a:0,e:'La doble afinidad de los fosfolípidos orienta sus cabezas al agua y sus colas hacia el interior de la bicapa.',diff:'media',skill:'moléculas orgánicas'},
    {di:0,si:1,ii:0,q:'¿Qué relación describe mejor el trabajo conjunto de los sistemas respiratorio y circulatorio?',o:['Los alvéolos intercambian gases y la sangre distribuye oxígeno','El corazón produce oxígeno y los pulmones lo almacenan','El sistema respiratorio digiere nutrientes y la sangre los elimina','Los alvéolos impulsan la sangre por las arterias'],a:0,e:'Los alvéolos permiten el intercambio gaseoso y la sangre transporta el oxígeno a los tejidos.',diff:'básica',skill:'sistemas del organismo'},
    {di:0,si:1,ii:1,q:'Un virus se multiplica dentro de una célula huésped porque:',o:['Usa la maquinaria celular para copiar su material genético','Realiza fotosíntesis en la membrana','Se convierte en una bacteria independiente','Produce sus propios ribosomas fuera de la célula'],a:0,e:'Los virus dependen de la maquinaria de la célula huésped para replicarse.',diff:'básica',skill:'infección viral'},
    {di:0,si:1,ii:2,q:'¿Cuál es un ejemplo de barrera inespecífica de defensa?',o:['La mucosidad que atrapa microorganismos','Los anticuerpos contra un virus específico','La memoria de un linfocito','Una vacuna dirigida a un antígeno'],a:0,e:'La mucosidad actúa como barrera inicial sin reconocer un microorganismo particular.',diff:'básica',skill:'defensas inespecíficas'},
    {di:0,si:1,ii:3,q:'¿Qué contraste es correcto entre neutrófilos y macrófagos?',o:['Los neutrófilos responden rápidamente y los macrófagos fagocitan y pueden presentar antígenos','Los macrófagos producen oxígeno y los neutrófilos forman hueso','Ambos solo producen anticuerpos','Los neutrófilos son células de memoria y los macrófagos son virus'],a:0,e:'Los neutrófilos son fagocitos de respuesta rápida; los macrófagos también fagocitan y pueden presentar antígenos.',diff:'alta',skill:'respuesta inmune'},
    {di:0,si:2,ii:0,q:'Una proteína que acelera una reacción química en la célula cumple principalmente una función:',o:['Enzimática','Estructural mineral','De almacenamiento de información genética','De aislamiento eléctrico'],a:0,e:'Las enzimas son proteínas que catalizan reacciones químicas.',diff:'básica',skill:'nutrientes y funciones'},
    {di:0,si:2,ii:1,q:'Para planificar una dieta balanceada se debe considerar especialmente:',o:['Edad, actividad física y estado de salud','Solo el color de los alimentos','La marca de cada producto','Eliminar siempre un grupo completo de nutrientes'],a:0,e:'Las necesidades nutricionales varían según edad, actividad y condiciones de salud.',diff:'media',skill:'dieta balanceada'},
    {di:0,si:2,ii:2,q:'¿Qué sustancia del cigarrillo se asocia principalmente con la dependencia?',o:['Nicotina','Oxígeno','Agua','Calcio'],a:0,e:'La nicotina actúa sobre el sistema nervioso y puede generar dependencia.',diff:'básica',skill:'sustancias adictivas'},
    {di:0,si:3,ii:0,q:'¿Qué función corresponde principalmente a los ovarios y al útero, respectivamente?',o:['Producir ovocitos y hormonas; permitir la implantación','Transportar espermatozoides; producir bilis','Filtrar sangre; almacenar orina','Producir insulina; intercambiar gases'],a:0,e:'Los ovarios producen gametos y hormonas; el útero recibe al embrión durante la implantación.',diff:'básica',skill:'sistema reproductor'},
    {di:0,si:3,ii:1,q:'El aumento brusco de la hormona luteinizante (LH) se relaciona directamente con:',o:['La ovulación','La menstruación por ausencia de fecundación','La producción de leche','La digestión de grasas'],a:0,e:'El pico de LH desencadena la ovulación en el ciclo ovárico.',diff:'alta',skill:'ciclo ovárico'},
    {di:0,si:3,ii:2,q:'¿Qué mecanismo explica que un preservativo reduzca el riesgo de embarazo y de infecciones de transmisión sexual?',o:['Actúa como barrera física que impide el paso de espermatozoides y reduce el intercambio de fluidos','Modifica permanentemente las hormonas','Elimina todos los microorganismos del cuerpo','Detiene la ovulación en cada ciclo'],a:0,e:'El preservativo funciona como barrera y disminuye el contacto con fluidos potencialmente infectantes.',diff:'media',skill:'regulación de la fertilidad'},
    {di:1,si:0,ii:0,q:'En la fotosíntesis, las plantas utilizan principalmente:',o:['Dióxido de carbono y agua para producir glucosa y oxígeno','Oxígeno y glucosa para producir dióxido de carbono','Nitrógeno y sal para producir proteínas sin luz','Solo agua para producir oxígeno'],a:0,e:'Con energía luminosa, las plantas transforman dióxido de carbono y agua en glucosa y oxígeno.',diff:'básica',skill:'fotosíntesis'},
    {di:1,si:1,ii:0,q:'En un bosque, todos los individuos de la misma especie que viven en una zona forman una:',o:['Población','Comunidad','Ecosistema','Biosfera'],a:0,e:'Una población reúne individuos de una misma especie en un lugar y tiempo determinados.',diff:'básica',skill:'niveles ecológicos'},
    {di:1,si:1,ii:1,q:'¿Qué medida favorece una explotación sustentable de una pesquería?',o:['Establecer cuotas y temporadas de veda basadas en evidencia','Capturar todos los ejemplares antes de la reproducción','Eliminar la fiscalización','Aumentar la extracción cuando disminuye la población'],a:0,e:'Las cuotas y vedas permiten que las poblaciones se recuperen y mantienen el recurso a largo plazo.',diff:'media',skill:'impacto de actividades productivas'},
    {di:2,si:0,ii:0,q:'¿Cuál combinación de carga eléctrica es correcta?',o:['Protón positiva, electrón negativa y neutrón neutra','Protón negativa, electrón neutra y neutrón positiva','Las tres partículas son positivas','Las tres partículas son neutras'],a:0,e:'El protón tiene carga positiva, el electrón negativa y el neutrón no tiene carga neta.',diff:'básica',skill:'partículas subatómicas'},
    {di:2,si:0,ii:1,q:'Un gas está encerrado en un recipiente rígido. Si aumenta su temperatura y el volumen no cambia, la presión:',o:['Aumenta','Disminuye a cero','Permanece siempre igual','Se transforma en masa'],a:0,e:'En un recipiente rígido, el aumento de temperatura incrementa la rapidez de las partículas y la presión.',diff:'media',skill:'gases ideales'},
    {di:2,si:0,ii:2,q:'¿Qué procedimiento separa mejor una mezcla de arena y agua?',o:['Filtración','Destilación fraccionada','Cromatografía de gases','Evaporación del hierro'],a:0,e:'La arena queda retenida en el filtro mientras el agua lo atraviesa.',diff:'básica',skill:'separación de mezclas'},
    {di:3,si:0,ii:2,q:'Un carrito en movimiento cambia de dirección al chocar con una barrera. ¿Qué conclusión es correcta?',o:['Una fuerza produjo un cambio en su movimiento','La masa desapareció','La temperatura determinó por sí sola la trayectoria','La velocidad no puede cambiar por una fuerza'],a:0,e:'Una fuerza neta puede cambiar la rapidez o la dirección del movimiento.',diff:'básica',skill:'fuerza y movimiento'},
    {di:3,si:1,ii:6,q:'En un circuito, dos ampolletas están conectadas en paralelo. Si una se quema, ¿qué ocurre idealmente con la otra?',o:['Puede seguir encendida porque tiene una rama independiente','Se apagan ambas necesariamente','Aumenta la masa de la batería','La corriente deja de existir en todo el circuito'],a:0,e:'En paralelo, cada rama tiene un camino propio; una ampolleta puede continuar funcionando.',diff:'media',skill:'circuitos eléctricos'},
    {di:5,si:0,ii:1,q:'En un experimento se cambia la cantidad de luz y se mide el crecimiento de una planta. ¿Cuál es la variable dependiente?',o:['El crecimiento de la planta','La cantidad de luz','El tipo de maceta si se mantiene constante','La hipótesis'],a:0,e:'La variable dependiente es el resultado que se mide: el crecimiento.',diff:'media',skill:'diseño experimental',type:'razonamiento científico'},
    {di:6,si:2,ii:1,q:'Si un objetivo pide explicar un fenómeno con evidencia, ¿qué evaluación está mejor alineada?',o:['Una respuesta escrita que relaciona datos, modelo y conclusión','Solo marcar la asistencia','Copiar una definición sin aplicarla','Medir cuánto tarda en terminar'],a:0,e:'La tarea solicita explicar y relacionar evidencia con una conclusión, por lo que entrega información sobre el objetivo.',diff:'alta',skill:'evaluación de ciencias',type:'evaluación pedagógica'}
  ]);
  addPack('basica-historia', [
    {di:0,si:0,ii:0,q:'En un mapa, ¿qué concepto indica la distancia angular de un lugar respecto del meridiano de Greenwich?',o:['Longitud','Latitud','Relieve','Densidad'],a:0,e:'La longitud mide la distancia angular al este u oeste del meridiano de Greenwich.',diff:'básica',skill:'conceptos geográficos'},
    {di:0,si:0,ii:1,q:'Para localizar la Región de Coquimbo respecto de la Región del Maule se debe indicar que está:',o:['Más al norte','Más al sur','Al este de África','En otro continente'],a:0,e:'Coquimbo se ubica al norte del Maule en el territorio chileno.',diff:'básica',skill:'orientación espacial'},
    {di:0,si:0,ii:2,q:'En un mapa a escala 1:100.000, una distancia de 3 cm representa aproximadamente:',o:['3 km','30 km','300 m','300 km'],a:0,e:'A esa escala, 1 cm representa 100.000 cm, es decir, 1 km; por tanto 3 cm son 3 km.',diff:'media',skill:'interpretación cartográfica'},
    {di:0,si:1,ii:1,q:'¿Qué característica se asocia principalmente a la zona central de Chile?',o:['Clima mediterráneo y concentración importante de población','Clima polar durante todo el año','Ausencia de actividades agrícolas','Relieve exclusivamente desértico'],a:0,e:'La zona central presenta clima mediterráneo y concentra gran parte de la población y actividades del país.',diff:'básica',skill:'zonas naturales'},
    {di:0,si:1,ii:2,q:'Una región del norte enfrenta escasez hídrica y alta demanda minera. ¿Qué desafío requiere considerar dimensiones físicas y económicas?',o:['Gestionar el agua compatibilizando consumo humano, ecosistemas y producción','Aumentar la extracción sin límites','Ignorar a las comunidades locales','Reemplazar todos los mapas por fotografías'],a:0,e:'El desafío regional exige equilibrar condiciones naturales, necesidades sociales y actividades económicas.',diff:'alta',skill:'desafíos regionales'},
    {di:0,si:2,ii:0,q:'La construcción de una carretera que elimina un humedal puede provocar a corto y largo plazo:',o:['Pérdida de hábitat y menor regulación natural de inundaciones','Aumento automático de biodiversidad','Formación de nuevos glaciares','Disminución de toda actividad humana'],a:0,e:'Los humedales son hábitats y regulan agua; su intervención puede reducir biodiversidad y aumentar riesgos.',diff:'media',skill:'impacto ambiental'},
    {di:1,si:0,ii:1,q:'Analizar cómo una reforma modificó la sociedad durante varias décadas corresponde a una mirada:',o:['Diacrónica','Sincrónica','Atemporal',' exclusivamente espacial'],a:0,e:'La diacronía estudia cambios y continuidades a través del tiempo.',diff:'básica',skill:'tiempo histórico'},
    {di:1,si:1,ii:0,q:'¿Qué legado de Roma sigue influyendo directamente en muchos sistemas jurídicos actuales?',o:['El derecho y la organización de normas escritas','La escritura jeroglífica','El sistema de castas egipcio','La navegación polinesia'],a:0,e:'El derecho romano aportó conceptos e instituciones que influyeron en tradiciones jurídicas posteriores.',diff:'básica',skill:'civilizaciones antiguas'},
    {di:1,si:1,ii:2,q:'¿Cuál ejemplo corresponde a una forma de organización política de una civilización americana?',o:['Ciudades-Estado mayas con gobiernos locales','Parlamento industrial inglés del siglo XIX','Feudo europeo medieval en Japón','República romana en Mesopotamia'],a:0,e:'Varias ciudades mayas funcionaron como unidades políticas independientes o ciudades-Estado.',diff:'media',skill:'civilizaciones americanas'},
    {di:1,si:1,ii:3,q:'¿Qué combinación favoreció los viajes europeos de exploración de los siglos XV y XVI?',o:['Mejoras náuticas, búsqueda de rutas comerciales y apoyo monárquico','Aislamiento de los puertos y rechazo de la cartografía','Descubrimiento de la electricidad y del ferrocarril','Abandono del comercio marítimo'],a:0,e:'La navegación, los intereses comerciales y el respaldo de monarquías impulsaron las exploraciones.',diff:'media',skill:'exploración europea'},
    {di:1,si:1,ii:4,q:'Dos crónicas sobre la conquista describen de manera distinta la relación entre españoles e indígenas. ¿Qué procedimiento es más riguroso?',o:['Contrastar autoría, propósito y contexto antes de construir una interpretación','Elegir la fuente más extensa sin analizarla','Suponer que toda fuente es neutral','Descartar ambas por tener perspectivas'],a:0,e:'Contrastar contexto, propósito y autoría permite interpretar críticamente fuentes con perspectivas diferentes.',diff:'alta',skill:'análisis de fuentes'},
    {di:1,si:1,ii:5,q:'Una fuente colonial registra tributos y trabajo obligatorio asignados a comunidades indígenas. ¿Qué institución ayuda a contextualizarla?',o:['La encomienda','El sufragio universal','La industrialización','La separación de poderes'],a:0,e:'La encomienda organizó tributos y trabajo indígena bajo dominio colonial.',diff:'media',skill:'periodo colonial'},
    {di:1,si:1,ii:6,q:'Una proclama de 1818 declara la independencia de Chile. Para interpretarla históricamente conviene:',o:['Relacionarla con la crisis de la monarquía, la guerra y los proyectos políticos del periodo','Leerla como una noticia contemporánea sin contexto','Usarla para describir solo el clima','Ignorar quién la emitió'],a:0,e:'La fuente adquiere sentido al vincularla con el contexto político y militar de la independencia.',diff:'alta',skill:'independencia de Chile'},
    {di:1,si:1,ii:7,q:'Los textos constitucionales de 1823, 1826 y 1828 muestran que la organización nacional chilena:',o:['Experimentó distintas fórmulas antes de consolidar un orden político','Fue idéntica desde el primer ensayo','Dependió exclusivamente de una potencia extranjera','Eliminó toda discusión sobre autoridad'],a:0,e:'Los ensayos constitucionales expresan debates y ajustes sobre la forma de organizar la república.',diff:'media',skill:'organización nacional'},
    {di:1,si:1,ii:9,q:'¿Qué cambio territorial se asocia directamente a la Guerra del Pacífico?',o:['Chile incorporó territorios de Perú y Bolivia, incluido Tarapacá y Antofagasta','Chile perdió todo su litoral frente a Argentina','Se creó la frontera actual con Brasil','Se anexó la Isla de Pascua a Bolivia'],a:0,e:'Tras la guerra, Chile incorporó Tarapacá y Antofagasta, modificando el territorio nacional.',diff:'básica',skill:'conformación territorial'},
    {di:1,si:1,ii:10,q:'En un sistema presidencial, a diferencia de uno parlamentario, el gobierno se caracteriza por:',o:['Un presidente con legitimidad y atribuciones propias separadas del Congreso','Un gabinete que depende siempre de un voto de censura parlamentario','La inexistencia de elecciones ejecutivas','La prohibición de todo control legislativo'],a:0,e:'En el presidencialismo el Ejecutivo tiene una jefatura propia y separación más definida respecto del Legislativo.',diff:'media',skill:'sistemas políticos'},
    {di:1,si:1,ii:11,q:'¿Cuál proceso refleja la progresiva democratización de la sociedad chilena durante el siglo XX?',o:['Ampliación de la participación electoral y reconocimiento de nuevos actores sociales','Reducción permanente del sufragio','Eliminación de organizaciones sindicales en todo el periodo','Concentración del voto en una sola familia'],a:0,e:'La democratización incluyó la ampliación del sufragio y la incorporación de diversos actores sociales.',diff:'básica',skill:'democratización'},
    {di:1,si:1,ii:12,q:'Una transformación característica del régimen militar chileno fue:',o:['Reorganización institucional autoritaria y reformas económicas de orientación neoliberal','Restablecimiento inmediato del Congreso en 1973','Eliminación de toda política económica','Transferencia del poder a cabildos medievales'],a:0,e:'El régimen combinó una reorganización política autoritaria con profundas reformas económicas.',diff:'alta',skill:'régimen militar'},
    {di:2,si:0,ii:0,q:'En un Estado de derecho, ¿qué principio es fundamental?',o:['Autoridades y ciudadanía están sometidas a la Constitución y las leyes','La autoridad puede actuar sin normas','Los derechos dependen de la riqueza','Las decisiones públicas no pueden revisarse'],a:0,e:'El Estado de derecho limita el poder mediante normas y protege derechos exigibles.',diff:'básica',skill:'Estado de derecho'},
    {di:3,si:2,ii:1,q:'Para evaluar si un estudiante interpreta una fuente histórica, ¿qué evidencia es más pertinente?',o:['Una explicación que usa datos de la fuente y los relaciona con su contexto','Repetir una fecha sin relacionarla','Colorear un mapa sin leyenda','Memorizar una lista de personajes'],a:0,e:'Interpretar exige usar evidencias de la fuente y vincularlas con el contexto histórico.',diff:'alta',skill:'evaluación disciplinar',type:'evaluación pedagógica'}
  ]);
  addPack('basica-ingles', [
    {di:0,si:0,ii:0,q:'Read: “The school garden opens every Friday afternoon. Students grow herbs and share them with the cafeteria.” What is the text mainly about?',o:['A school garden activity','A new cafeteria menu','A Friday sports club','A science exam'],a:0,e:'The two sentences focus on the school garden and what students do there.',diff:'básica',skill:'global reading'},
    {di:0,si:0,ii:1,q:'Read: “Mia arrived at 8:15 and left her bicycle beside the blue gate.” Where did Mia leave her bicycle?',o:['Beside the blue gate','Inside the classroom','At the bus stop','Behind the cafeteria'],a:0,e:'The sentence states that the bicycle was left beside the blue gate.',diff:'básica',skill:'local reading'},
    {di:0,si:0,ii:2,q:'Read: “Tom missed the bus, walked to school and arrived before the bell.” Which sentence best summarizes the text?',o:['Tom walked to school after missing the bus.','Tom went home before the bell.','Tom took the bus very early.','Tom forgot where the school was.'],a:0,e:'The option keeps the main event and its sequence without adding information.',diff:'media',skill:'summarizing'},
    {di:0,si:0,ii:3,q:'A notice says: “Dear families, please sign the permission form by Monday.” Who is the intended recipient?',o:['Students’ families','The school bus driver','The town mayor','A group of tourists'],a:0,e:'The greeting and request address students’ families.',diff:'básica',skill:'text purpose and audience'},
    {di:0,si:0,ii:4,q:'Read: “The river level rose after two days of heavy rain, so the park was closed.” What can be concluded?',o:['The rain caused a safety concern in the park.','The park closed because it was sunny.','The river level fell during the storm.','Visitors were asked to swim in the river.'],a:0,e:'The rise in water and the closure imply a safety concern.',diff:'media',skill:'drawing conclusions'},
    {di:0,si:0,ii:5,q:'Read: “Leo wore a helmet while cycling to school.” What is the relation between the two ideas?',o:['The helmet is a safety measure for cycling.','The helmet caused Leo to walk.','Cycling was replaced by swimming.','The school lent Leo a bicycle.'],a:0,e:'The sentence connects wearing a helmet with the activity of cycling safely.',diff:'media',skill:'text relations'},
    {di:0,si:0,ii:6,q:'Read: “Although the test was difficult, Ana stayed calm and checked each answer.” What can be inferred about Ana?',o:['She used a strategy to manage the challenge.','She did not take the test.','She finished without reading.','She thought the test was easy.'],a:0,e:'Her calm attitude and checking show a strategy for dealing with difficulty.',diff:'alta',skill:'contextual inference'},
    {di:0,si:1,ii:0,q:'In “The path was narrow, so only one person could walk at a time,” narrow means:',o:['Not wide','Very noisy','Completely dark','Far from the town'],a:0,e:'The clause about one person at a time signals that narrow means not wide.',diff:'básica',skill:'vocabulary in context'},
    {di:0,si:1,ii:1,q:'In “The players packed their bags because they were leaving early,” the pronoun “they” refers to:',o:['The players','The bags','The coaches’ cars','The morning'],a:0,e:'The plural pronoun refers to the previously mentioned players.',diff:'básica',skill:'reference mechanisms'},
    {di:1,si:0,ii:0,q:'Listen to the imagined announcement: “The museum will open at ten and close at six.” What information is given globally?',o:['The museum’s opening hours','The museum’s ticket price','The museum’s address','The museum’s oldest object'],a:0,e:'The announcement communicates when the museum opens and closes.',diff:'básica',skill:'global listening'},
    {di:1,si:0,ii:1,q:'Listen: “Please bring a pencil and your science notebook to tomorrow’s class.” What must students bring?',o:['A pencil and a science notebook','A calculator and a map','A lunch and a camera','A ruler and a dictionary'],a:0,e:'Both requested items are explicitly named in the announcement.',diff:'básica',skill:'local listening'},
    {di:1,si:0,ii:8,q:'A teacher says, “Could you close the window? It is getting cold.” What is the communicative purpose?',o:['To make a polite request','To tell a story','To give a weather forecast','To apologize for being late'],a:0,e:'The speaker asks the listener to perform an action politely.',diff:'media',skill:'oral purpose'},
    {di:1,si:0,ii:9,q:'Two classmates plan a project and take turns suggesting ideas. This is mainly a:',o:['Collaborative planning conversation','Formal news broadcast','Monologue to an audience','Written instruction manual'],a:0,e:'The speakers interact and negotiate ideas, which characterizes a collaborative conversation.',diff:'media',skill:'communicative situation'},
    {di:1,si:1,ii:1,q:'If someone says “It’s raining cats and dogs,” the intended meaning is:',o:['It is raining very heavily','Animals are falling from the sky','The weather is completely dry','A storm has ended'],a:0,e:'This idiom means that it is raining a lot.',diff:'media',skill:'idioms'},
    {di:2,si:0,ii:0,q:'Choose the correct verb form: “If she ___ early, she will call us.”',o:['arrives','arrive','arrived','arriving'],a:0,e:'The first conditional uses present simple in the if-clause: “If she arrives…”',diff:'media',skill:'verb tenses'},
    {di:2,si:0,ii:1,q:'Choose the correct form: “They enjoy ___ science videos after class.”',o:['watching','to watch','watch','watched'],a:0,e:'The verb enjoy is followed by a gerund: “enjoy watching”.',diff:'media',skill:'gerunds and infinitives'},
    {di:2,si:0,ii:3,q:'Which sentence is correctly written in the passive voice?',o:['The experiment was designed by the students.','The students was design the experiment.','The experiment designing the students.','The students have design by the experiment.'],a:0,e:'The passive pattern is be + past participle: “was designed”.',diff:'alta',skill:'complex structures'},
    {di:2,si:0,ii:5,q:'Choose the connector that best completes the idea: “The route was long; ___, the hikers reached the lake before noon.”',o:['however','because','unless','therefore'],a:0,e:'However introduces a contrast between the long route and the successful arrival.',diff:'media',skill:'cohesion and connectors'},
    {di:3,si:0,ii:1,q:'Which activity best represents an active methodology in an English class?',o:['Students solve a real-world problem collaboratively and present their solution','Students copy a vocabulary list silently for the whole lesson','The teacher reads every answer without student interaction','Students memorize rules without using them'],a:0,e:'An authentic collaborative problem with a product promotes active participation and communication.',diff:'media',skill:'active methodologies',type:'decisión pedagógica'},
    {di:3,si:1,ii:2,q:'The objective is “identify specific information in a short audio.” Which assessment is best aligned?',o:['A listening task with selected details and feedback on evidence','A drawing task unrelated to the audio','A spelling list with no recording','A participation score only'],a:0,e:'The task asks students to identify details in audio, matching the stated objective.',diff:'alta',skill:'aligned assessment',type:'evaluación pedagógica'}
  ]);
  addPack('basica-lenguaje', [
    {di:0,si:0,ii:0,q:'Un texto cuenta que una niña encuentra una carta, enfrenta un conflicto y toma una decisión final. ¿A qué género pertenece principalmente?',o:['Narrativo','Lírico','Dramático','Expositivo'],a:0,e:'La presencia de personajes, acciones y una secuencia de acontecimientos caracteriza la narrativa.',diff:'básica',skill:'géneros literarios'},
    {di:0,si:0,ii:1,q:'En “La luna es una moneda de plata”, ¿qué figura literaria aparece?',o:['Metáfora','Onomatopeya','Anáfora','Hipérbole'],a:0,e:'Se identifica la luna con una moneda sin usar “como”; es una metáfora.',diff:'básica',skill:'figuras literarias'},
    {di:0,si:0,ii:2,q:'En los versos “La abeja trabaja / y el campo se alaga”, ¿qué elemento se debe observar para estudiar la rima?',o:['La semejanza de sonidos finales','La cantidad de personajes','La información del título','El tamaño de la letra'],a:0,e:'La rima se reconoce comparando los sonidos al final de los versos.',diff:'media',skill:'rima y métrica'},
    {di:0,si:0,ii:3,q:'En “El viento susurra entre los árboles”, la expresión destacada se interpreta como:',o:['Una personificación que atribuye una acción humana al viento','Una definición científica del viento','Una comparación explícita con una persona','Una enumeración de objetos'],a:0,e:'“Susurrar” es una acción humana aplicada al viento, por lo que hay personificación.',diff:'media',skill:'interpretación figurada'},
    {di:0,si:0,ii:4,q:'¿Qué efecto produce decir “esperé una eternidad” en un relato?',o:['Intensifica subjetivamente la duración de la espera','Entrega una medida exacta de tiempo','Elimina la emoción del personaje','Describe un lugar fantástico'],a:0,e:'La hipérbole exagera la duración para enfatizar la experiencia del personaje.',diff:'media',skill:'efecto del lenguaje figurado'},
    {di:0,si:0,ii:5,q:'En un cómic, varias viñetas muestran a vecinos organizándose para limpiar una plaza. ¿Cuál es el tema central?',o:['La colaboración comunitaria','La competencia deportiva','El viaje espacial','La preparación de una receta'],a:0,e:'Las acciones de las viñetas se organizan alrededor de la colaboración para cuidar un espacio común.',diff:'básica',skill:'tema de cómic'},
    {di:0,si:0,ii:6,q:'Un cómic muestra un personaje muy pequeño frente a un edificio enorme. ¿Qué recurso visual puede reforzar ese sentido?',o:['El contraste de tamaños','La eliminación de los globos de diálogo','La repetición de una fecha','El uso exclusivo de onomatopeyas'],a:0,e:'El contraste de tamaños puede comunicar pequeñez, distancia o sensación de desventaja.',diff:'media',skill:'recursos del cómic'},
    {di:0,si:1,ii:0,q:'¿Qué rasgo es central en un artículo informativo?',o:['Presenta información organizada sobre un tema con propósito de informar','Relata únicamente sentimientos del autor','Desarrolla una trama con personajes ficticios','Entrega instrucciones sin explicar el tema'],a:0,e:'Un artículo informativo organiza datos y explicaciones para comunicar conocimientos.',diff:'básica',skill:'textos informativos'},
    {di:0,si:1,ii:1,q:'Una noticia titulada “Aumenta el uso de bicicletas en la ciudad” busca principalmente:',o:['Informar sobre un hecho de interés público','Convencer de comprar una bicicleta específica','Contar una historia fantástica','Dar instrucciones para reparar una rueda'],a:0,e:'El titular anuncia un hecho y la noticia lo desarrolla con propósito informativo.',diff:'básica',skill:'propósito comunicativo'},
    {di:0,si:1,ii:2,q:'Una tabla muestra que, al aumentar las horas de estudio, también sube el promedio del curso. ¿Qué relación se puede interpretar?',o:['Una asociación positiva entre ambas variables','Que una variable causa siempre la otra','Que no existe ninguna relación','Que ambas variables son idénticas'],a:0,e:'Los datos muestran que ambas variables tienden a aumentar juntas; eso describe una asociación positiva.',diff:'media',skill:'lectura de tablas'},
    {di:0,si:1,ii:4,q:'¿Cuál enunciado es una opinión?',o:['El parque abre a las ocho, según el aviso municipal.','La plaza tiene dos juegos infantiles.','El nuevo parque es el lugar más hermoso de la ciudad.','La obra fue inaugurada el lunes.'],a:2,e:'“El lugar más hermoso” expresa una valoración subjetiva, no un dato comprobable por sí solo.',diff:'básica',skill:'hechos y opiniones'},
    {di:1,si:0,ii:0,q:'En “El curso visitó el museo. Allí observó piezas de cerámica”, la palabra “allí” contribuye a:',o:['Mantener la cohesión al referirse al museo','Cambiar el tema hacia otro lugar','Introducir una opinión del narrador','Eliminar la relación entre oraciones'],a:0,e:'El adverbio “allí” retoma el lugar mencionado y conecta las oraciones.',diff:'media',skill:'cohesión textual'},
    {di:1,si:1,ii:0,q:'¿Cuál palabra está correctamente escrita según la ortografía acentual?',o:['árbol','lapiz','camion','facilmente'],a:0,e:'“Árbol” es una palabra grave terminada en consonante distinta de n o s y lleva tilde.',diff:'básica',skill:'ortografía'},
    {di:1,si:1,ii:1,q:'Durante un diálogo para llegar a un acuerdo, una intervención adecuada es:',o:['Parafrasear la idea del otro y proponer una alternativa','Interrumpir y cambiar de tema','Repetir la misma frase sin escuchar','Descalificar a la persona'],a:0,e:'Parafrasear y proponer una alternativa muestra escucha y ayuda a construir acuerdos.',diff:'media',skill:'gestión del diálogo'},
    {di:1,si:1,ii:2,q:'Para exponer oralmente ante un curso, un recurso que favorece la claridad es:',o:['Organizar las ideas con introducción, desarrollo y cierre','Leer diapositivas llenas de texto sin mirar al público','Usar solo palabras técnicas sin explicar','Improvisar sin considerar el tiempo'],a:0,e:'Una estructura clara ayuda a que la audiencia siga el desarrollo de la exposición.',diff:'básica',skill:'discurso monologado'},
    {di:2,si:0,ii:1,q:'Antes de leer un texto informativo, ¿qué estrategia favorece la comprensión?',o:['Activar conocimientos previos y anticipar el contenido a partir del título','Copiar cada palabra antes de leer','Memorizar el número de páginas','Evitar formular preguntas'],a:0,e:'Anticipar y activar conocimientos previos prepara un marco para interpretar la información.',diff:'media',skill:'comprensión lectora',type:'decisión pedagógica'},
    {di:2,si:0,ii:2,q:'¿Qué actividad corresponde principalmente a la etapa de planificación de la escritura?',o:['Definir propósito, destinatario y organizar ideas','Corregir tildes del texto final','Publicar sin revisar','Calificar el trabajo de otro curso'],a:0,e:'Planificar implica decidir para quién y para qué se escribe y ordenar las ideas.',diff:'básica',skill:'proceso de escritura',type:'decisión pedagógica'},
    {di:2,si:0,ii:4,q:'Para investigar un tema, ¿qué práctica ayuda a evaluar la confiabilidad de una fuente digital?',o:['Revisar autoría, fecha, propósito y corroborar la información','Elegir la primera página que aparece','Confiar solo en el diseño gráfico','Copiar el texto sin registrar la fuente'],a:0,e:'Autoría, fecha, propósito y corroboración son criterios básicos para evaluar una fuente.',diff:'alta',skill:'investigación',type:'decisión pedagógica'},
    {di:2,si:0,ii:5,q:'Un estudiante escribe “habían muchos problemas”. ¿Cuál retroalimentación es más útil?',o:['Explicar que “había” concuerda con el sentido impersonal y pedir revisar la oración','Decir solo “está malo”','Cambiar toda la idea sin explicar','Ignorar el error porque se entiende'],a:0,e:'La retroalimentación precisa explica el fenómeno y orienta una revisión concreta.',diff:'media',skill:'retroalimentación',type:'aprendizaje desde el error'},
    {di:2,si:2,ii:1,q:'Si el objetivo es distinguir hechos de opiniones en una noticia, ¿qué instrumento es más pertinente?',o:['Una pauta con criterios para clasificar enunciados y justificar la decisión','Una prueba de caligrafía','Una lista de asistencia','Un dibujo libre sin texto'],a:0,e:'La pauta permite observar la clasificación y la justificación que exige el objetivo.',diff:'alta',skill:'evaluación de lenguaje',type:'evaluación pedagógica'}
  ]);
  addPack('media-lengua', [
    {di:0,si:0,ii:0,q:'En “La ciudad despierta con un rugido de motores”, la expresión “despierta” aplicada a la ciudad constituye:',o:['Personificación','Metonimia','Ironía necesariamente','Epíteto'],a:0,e:'Se atribuye a la ciudad una acción propia de seres vivos: despertar.',diff:'básica',skill:'figuras literarias'},
    {di:0,si:0,ii:1,q:'¿Qué efecto produce la hipérbole “te llamé un millón de veces” en un diálogo?',o:['Enfatiza la insistencia sin indicar una cantidad literal','Entrega el número exacto de llamadas','Elimina la emoción del hablante','Describe una llamada internacional'],a:0,e:'La exageración intensifica la insistencia del hablante y no debe entenderse literalmente.',diff:'básica',skill:'lenguaje figurado'},
    {di:0,si:0,ii:2,q:'Una novela comienza con el protagonista adulto y luego vuelve a un episodio de su infancia. ¿Qué técnica narrativa se utiliza?',o:['Analepsis o retroceso temporal','Prolepsis o anticipación','Narración simultánea','Descripción objetiva'],a:0,e:'El regreso a un hecho anterior al presente narrativo es una analepsis.',diff:'media',skill:'técnicas narrativas'},
    {di:0,si:0,ii:3,q:'En una obra dramática, la indicación “[Entra lentamente y deja la carta sobre la mesa]” corresponde a:',o:['Una acotación','Un aparte del público','El desenlace narrado','Una nota bibliográfica'],a:0,e:'La acotación orienta acciones, movimientos o elementos escénicos.',diff:'básica',skill:'mundo dramático'},
    {di:0,si:0,ii:4,q:'Una obra presenta enredos, malentendidos y un final que restablece la armonía. ¿Qué subgénero dramático es más probable?',o:['Comedia','Tragedia','Auto sacramental','Elegía'],a:0,e:'Los enredos y el desenlace armonioso son rasgos frecuentes de la comedia.',diff:'media',skill:'géneros dramáticos'},
    {di:0,si:0,ii:5,q:'En un cómic, una palabra como “¡CRASH!” aparece junto a un objeto que cae. ¿Qué recurso representa?',o:['Onomatopeya que hace audible el impacto','Metáfora visual sobre el tiempo','Cita de autoridad','Descripción científica'],a:0,e:'“¡CRASH!” imita un sonido y refuerza la acción representada.',diff:'básica',skill:'recursos del cómic'},
    {di:0,si:0,ii:7,q:'Un narrador describe una ciudad vigilada y afirma que la obediencia “es la única forma de libertad”. ¿Qué se puede distinguir?',o:['Un punto de vista con carácter argumentativo','Una descripción sin perspectiva','Una lista de datos estadísticos','Una acotación escénica'],a:0,e:'La afirmación expresa una postura que puede analizarse y discutirse como punto de vista.',diff:'alta',skill:'puntos de vista literarios'},
    {di:0,si:0,ii:8,q:'Para interpretar un poema publicado durante una crisis social, es pertinente considerar:',o:['El contexto de producción y las circunstancias de recepción','Solo la cantidad de versos','El precio actual del libro','La biografía de cualquier lector'],a:0,e:'El contexto histórico y cultural puede iluminar decisiones temáticas y formales del poema.',diff:'media',skill:'contexto de producción'},
    {di:0,si:0,ii:9,q:'Una novela contemporánea muestra personas que migran por sequías y reorganizan sus comunidades. ¿Qué tema central aborda?',o:['Desplazamiento humano y adaptación ante cambios ambientales','La vida de una corte medieval','El origen de la imprenta','La clasificación de minerales'],a:0,e:'La trama se centra en migración y adaptación frente a un problema ambiental.',diff:'básica',skill:'temas contemporáneos'},
    {di:0,si:0,ii:10,q:'Una lectura crítica se concentra en repeticiones, imágenes y relaciones internas del texto, sin explicar la obra por la biografía del autor. ¿Qué enfoque refleja?',o:['Formalismo o análisis inmanente','Determinismo biográfico','Historiografía económica exclusivamente','Psicología clínica del lector'],a:0,e:'El análisis formalista privilegia la organización y los recursos internos de la obra.',diff:'alta',skill:'teorías literarias'},
    {di:0,si:1,ii:1,q:'En un discurso, la tesis “La ciudad debe ampliar sus ciclovías” se apoya en datos de accidentes y testimonios. ¿Qué función cumplen esos datos?',o:['Constituyen evidencias que respaldan la tesis','Reemplazan al emisor','Eliminan el propósito persuasivo','Funcionan solo como saludo'],a:0,e:'Los datos y testimonios entregan respaldo para aceptar la tesis.',diff:'básica',skill:'discurso argumentativo'},
    {di:0,si:1,ii:2,q:'“La propuesta es confiable porque fue evaluada por tres especialistas en movilidad” es un argumento basado principalmente en:',o:['Autoridad','Analogía','Causa falsa','Generalización apresurada'],a:0,e:'Se apela al conocimiento de especialistas para respaldar la propuesta.',diff:'media',skill:'tipos de argumentos'},
    {di:0,si:1,ii:3,q:'En un discurso público, la presentación del problema, la propuesta y el llamado a participar corresponden a:',o:['Una organización que orienta la intervención ante una audiencia','Una conversación privada sin propósito','Una descripción de personajes ficticios','Un listado de definiciones aisladas'],a:0,e:'El discurso público organiza contenido y llamado a la acción según una audiencia.',diff:'media',skill:'discurso público'},
    {di:0,si:1,ii:8,q:'Un aviso muestra familias sonrientes y afirma “elige hoy el futuro de tus hijos”. ¿Qué estrategia de persuasión predomina?',o:['Apelación emocional asociada a protección y futuro','Definición técnica neutral','Refutación de una fuente','Descripción sin valoración'],a:0,e:'La imagen y el mensaje apelan a emociones y valores familiares para persuadir.',diff:'media',skill:'persuasión en medios'},
    {di:1,si:0,ii:0,q:'En “El equipo presentó el informe. Este fue revisado por la comisión”, la palabra “este” funciona como:',o:['Un mecanismo de referencia que retoma “el informe”','Un conector causal','Una modalización','Un verbo auxiliar'],a:0,e:'El pronombre demostrativo retoma un elemento mencionado previamente y evita repetirlo.',diff:'básica',skill:'cohesión textual'},
    {di:1,si:0,ii:1,q:'En “Aunque la evidencia era limitada, el informe propuso una hipótesis”, la subordinada introduce:',o:['Una concesión','Una finalidad','Una consecuencia','Una condición'],a:0,e:'“Aunque” presenta una dificultad que no impide la acción principal: es una concesión.',diff:'media',skill:'oraciones subordinadas'},
    {di:1,si:0,ii:2,q:'Un texto presenta primero un problema, luego analiza sus causas y finalmente propone soluciones. ¿Qué progresión temática predomina?',o:['Derivada o encadenada desde un tema hacia aspectos relacionados','Lineal sin ningún desarrollo','Circular basada solo en repeticiones','Aleatoria y sin relaciones'],a:0,e:'El tema se despliega en subtemas vinculados: problema, causas y soluciones.',diff:'alta',skill:'progresión temática'},
    {di:1,si:1,ii:0,q:'¿Qué marca evidencia modalización discursiva?',o:['“Probablemente, la medida tendrá efectos positivos”','“La medida tiene tres artículos”','“La reunión fue el lunes”','“El informe ocupa diez páginas”'],a:0,e:'“Probablemente” expresa el grado de certeza del emisor y modaliza la afirmación.',diff:'básica',skill:'modalización'},
    {di:1,si:1,ii:2,q:'En un debate académico formal, una intervención adecuada para argumentar es:',o:['Presentar una tesis, citar evidencia y responder respetuosamente a una objeción','Interrumpir para descalificar a la persona','Afirmar que la mayoría siempre tiene razón','Cambiar de tema ante cualquier pregunta'],a:0,e:'Una argumentación formal integra tesis, evidencia y respuesta razonada en un intercambio respetuoso.',diff:'media',skill:'diálogo argumentativo'},
    {di:2,si:2,ii:0,q:'Si el objetivo es interpretar el efecto de una figura literaria, ¿qué criterio de evaluación es pertinente?',o:['Explica la figura y relaciona su efecto con el sentido del fragmento','Enumera personajes sin interpretar','Copia el título de la obra','Mide la velocidad de lectura'],a:0,e:'El criterio observa tanto el reconocimiento de la figura como su interpretación contextual.',diff:'alta',skill:'evaluación de literatura',type:'evaluación pedagógica'}
  ]);
  // PACKS_END

  function targetQuestions(specialtyId) {
    if (specialtyId === 'basica-matematica') return window.QBANK || [];
    const pack = window.PE22_CONTENT && window.PE22_CONTENT[specialtyId];
    return pack && Array.isArray(pack.questions) ? pack.questions : [];
  }

  const addedBySpecialty = {};
  Object.entries(packs).forEach(([specialtyId, items]) => {
    if (specialtyId === 'basica-matematica' && window.PE_ACTIVE_SPECIALTY !== specialtyId) return;
    const target = targetQuestions(specialtyId);
    const existing = new Set(target.map(question => question && question.id));
    let added = 0;
    items.forEach((item, index) => {
      const question = make(specialtyId, index, item);
      if (existing.has(question.id)) return;
      target.push(question);
      existing.add(question.id);
      added++;
    });
    addedBySpecialty[specialtyId] = added;
  });

  window.PE287 = {
    sources,
    packs,
    addedBySpecialty,
    totalAdded: Object.values(addedBySpecialty).reduce((sum, count) => sum + count, 0),
    activeCount: () => (window.QBANK || []).length
  };

  function inject() {
    const home = document.getElementById('home');
    if (!home || home.querySelector('.bank287home')) return;
    const card = document.createElement('div');
    card.className = 'card bank287home';
    const active = window.PE20 && typeof window.PE20.active === 'function'
      ? window.PE20.active()
      : {short: 'especialidad activa'};
    card.innerHTML =
      '<span class="pill">Banco ampliado 2.8.7</span><h3>Más práctica, con trazabilidad</h3>' +
      '<p class="muted">Se agregaron ' + (addedBySpecialty[window.PE_ACTIVE_SPECIALTY] || 0) +
      ' preguntas nuevas para ' + active.short + '. Cada ítem indica su dominio, indicador, habilidad y dificultad.</p>' +
      '<p class="tiny">Son preguntas originales de práctica. Se usaron como referencia el temario 2026 y el formato de material público ECEP, no cuadernillos filtrados.</p>' +
      '<div class="bank287Links"><a href="' + sources.current + '" target="_blank" rel="noopener">Temarios ECEP 2026</a>' +
      '<a href="' + sources.previous + '" target="_blank" rel="noopener">Pruebas y plantillas públicas por año</a>' +
      '<a href="' + sources.released + '" target="_blank" rel="noopener">Publicación CPEIP 2017–2020</a></div>';
    const hero = home.querySelector('.hero');
    if (hero) hero.after(card);
    else home.prepend(card);
  }

  const oldRender = window.render;
  if (oldRender && !window.__pe287) {
    window.render = function () {
      const result = oldRender();
      setTimeout(inject, 0);
      return result;
    };
    window.__pe287 = true;
  }
  setTimeout(inject, 0);
}());
