// ProfeECEP 2.8 — expansión del banco propio
(function(){
 'use strict';
 const math='basica-matematica';
 const packs={
  'basica-matematica':[
   [[0,1,3],'En una encuesta, 35 de 140 estudiantes prefieren una actividad. ¿Qué porcentaje representa?', ['15%','20%','25%','35%'],2,'porcentajes','media','35/140=0,25; equivale a 25%.'],
   [[0,1,0],'Una cantidad aumenta de 80 a 100. ¿Qué porcentaje de aumento representa?', ['20%','25%','80%','125%'],1,'porcentajes','media','El aumento es 20 y 20/80=0,25, es decir, 25%.'],
   [[0,1,1],'Si dos variables son directamente proporcionales y una se duplica, la otra:', ['se reduce a la mitad','se mantiene siempre igual','también se duplica','aumenta en una unidad'],2,'proporcionalidad','básica','En una relación directa, el cociente entre las variables permanece constante.'],
   [[0,2,0],'¿Cuál afirmación describe correctamente 2 elevado a 4?', ['2+4','2×4','4 factores iguales a 2 multiplicados','4 factores iguales a 4'],2,'potencias','básica','El exponente indica cuántas veces se usa la base como factor.'],
   [[0,2,1],'¿Cuál es el resultado de 5 elevado a 3 dividido por 5 elevado a 1?', ['5','25','125','625'],1,'propiedades de potencias','media','Al dividir potencias de igual base se restan los exponentes: 5^(3-1)=25.'],
   [[1,0,1],'¿Qué expresión representa tres veces un número más el mismo número?', ['3x','4x','3+x','x+3'],1,'traducción algebraica','básica','Tres veces x más x equivale a 4x.'],
   [[1,1,0],'Si 5x=35, ¿qué valor tiene x?', ['5','6','7','8'],2,'ecuaciones','básica','Divide ambos miembros por 5: x=7.'],
   [[1,1,2],'Al resolver una ecuación, ¿por qué se puede sumar el mismo número a ambos miembros?', ['Porque cambia la solución','Porque conserva la igualdad','Porque elimina siempre la variable','Porque convierte toda ecuación en proporción'],1,'razonamiento algebraico','media','Aplicar la misma operación en ambos miembros mantiene equivalentes las expresiones.'],
   [[1,2,0],'En una función, el conjunto de valores que puede tomar la variable de entrada se llama:', ['recorrido','pendiente','dominio','intercepto'],2,'funciones','básica','El dominio reúne los valores permitidos para la entrada.'],
   [[1,2,2],'En y=−2x+7, ¿qué efecto tiene aumentar x en 1?', ['y aumenta 7','y aumenta 2','y disminuye 2','y permanece igual'],2,'funciones lineales','media','La pendiente −2 indica que y disminuye 2 por cada unidad que aumenta x.'],
   [[2,0,3],'Un polígono tiene todos sus lados y ángulos congruentes. ¿Cómo se clasifica?', ['irregular','regular','abierto','cóncavo siempre'],1,'clasificación geométrica','básica','La congruencia de lados y ángulos caracteriza a un polígono regular.'],
   [[2,0,4],'¿Qué relación existe entre el radio y el diámetro de una circunferencia?', ['El radio es el doble del diámetro','El diámetro es el doble del radio','No tienen relación','Su suma siempre es 1'],1,'circunferencia','básica','El diámetro pasa por el centro y mide dos radios.'],
   [[2,1,0],'Un cuadrado tiene lado de 7 cm. ¿Cuál es su perímetro?', ['14 cm','28 cm','49 cm','56 cm'],1,'perímetro','básica','El perímetro es 4×7=28 cm.'],
   [[2,1,3],'Si se duplica el largo y el ancho de un rectángulo, su área:', ['se duplica','se triplica','se cuadruplica','no cambia'],2,'escala y área','alta','El área queda (2l)(2a)=4la, por lo que se cuadruplica.'],
   [[2,2,1],'Una reflexión respecto del eje x transforma el punto (4,−3) en:', ['(−4,−3)','(4,3)','(−3,4)','(3,−4)'],1,'transformaciones','media','La reflexión en el eje x cambia el signo de y y conserva x.'],
   [[3,0,0],'¿Qué medida estadística corresponde al valor que aparece con mayor frecuencia?', ['media','mediana','moda','rango'],2,'estadística descriptiva','básica','La moda es el valor más frecuente.'],
   [[3,0,2],'Para comparar la variabilidad de dos conjuntos con unidades iguales, ¿qué medida usa los valores extremos?', ['rango','moda','mediana','frecuencia relativa'],0,'dispersión','media','El rango se calcula como máximo menos mínimo.'],
   [[3,1,0],'En una bolsa hay 4 fichas verdes y 6 amarillas. La probabilidad de sacar una verde es:', ['1/10','2/5','3/5','4/6'],1,'probabilidad','básica','Hay 4 casos favorables de 10 posibles: 4/10=2/5.'],
   [[3,1,2],'Se lanzan dos dados. ¿Cuántos resultados ordenados hay en el espacio muestral?', ['6','12','24','36'],3,'principio multiplicativo','media','Cada dado tiene 6 resultados y 6×6=36 pares ordenados.'],
   [[4,0,2],'Una docente quiere saber si un material ayuda a comprender porcentajes. ¿Qué evidencia está mejor alineada?', ['Solo asistencia','Una explicación y resolución de problemas con el material','El color del cuaderno','El tiempo de recreo'],1,'evaluación alineada','media','La evidencia debe mostrar comprensión y aplicación del objetivo.']
  ],
  'basica-ciencias':[
   [[0,0,1],'¿Qué diferencia principal existe entre difusión simple y transporte activo?', ['La difusión usa ATP y el transporte activo no','El transporte activo puede requerir energía para mover sustancias contra el gradiente','Ambos siempre mueven sustancias contra el gradiente','La difusión ocurre solo en organismos multicelulares'],1,'transporte celular','media','El transporte activo usa energía para desplazar sustancias contra su gradiente; la difusión simple es pasiva.'],
   [[0,1,0],'¿Qué sistema transporta oxígeno y nutrientes hacia las células?', ['digestivo','circulatorio','nervioso','excretor'],1,'sistemas del organismo','básica','El sistema circulatorio distribuye sustancias mediante la sangre.'],
   [[0,2,1],'Una dieta equilibrada debe considerar principalmente:', ['solo la cantidad de calorías','variedad de nutrientes y necesidades del organismo','eliminar todos los lípidos','consumir un único alimento'],1,'nutrición y salud','básica','La dieta depende de variedad, cantidades y necesidades individuales.'],
   [[0,3,2],'¿Qué afirmación relaciona correctamente hormonas y ciclo ovárico?', ['Las hormonas no participan','Las variaciones hormonales coordinan cambios del ovario y del útero','Solo interviene el sistema digestivo','La ovulación ocurre sin cambios hormonales'],1,'regulación hormonal','media','Las hormonas coordinan las etapas del ciclo ovárico y uterino.'],
   [[1,0,0],'Durante la fotosíntesis, la energía luminosa permite principalmente:', ['transformar dióxido de carbono y agua en sustancias orgánicas','eliminar toda el agua de la planta','producir oxígeno sin otra transformación','detener el intercambio gaseoso'],0,'fotosíntesis','media','La energía luminosa impulsa la formación de glucosa a partir de agua y dióxido de carbono.'],
   [[1,1,1],'La introducción de una especie invasora puede:', ['afectar redes tróficas y competir con especies nativas','aumentar siempre la biodiversidad','no producir ningún cambio','eliminar únicamente factores abióticos'],0,'ecología','alta','Una especie invasora puede alterar relaciones ecológicas y desplazar especies nativas.'],
   [[2,0,0],'¿Qué partícula subatómica tiene carga negativa?', ['protón','neutrón','electrón','núcleo'],2,'estructura atómica','básica','El electrón posee carga negativa; protones son positivos y neutrones neutros.'],
   [[2,0,2],'Para separar alcohol y agua, que forman una mezcla homogénea, resulta pertinente usar:', ['filtración','decantación','destilación','tamizado'],2,'separación de mezclas','media','La destilación aprovecha diferencias de temperatura de ebullición.'],
   [[3,0,2],'Si sobre un carrito se aplica una fuerza neta en la dirección del movimiento, el carrito:', ['acelera','se detiene necesariamente','pierde masa','queda sin fuerzas'],0,'fuerza y movimiento','media','Una fuerza neta en la dirección del movimiento produce aceleración en esa dirección.'],
   [[3,1,3],'En un circuito paralelo, si una ampolleta se quema, las otras ramas pueden:', ['seguir funcionando porque tienen caminos independientes','apagarse siempre todas','convertirse en circuitos en serie','perder automáticamente su fuente'],0,'circuitos eléctricos','media','Cada rama del circuito paralelo ofrece un camino independiente para la corriente.'],
   [[4,0,0],'Un suelo con partículas grandes y poca materia orgánica suele:', ['retener menos agua que uno con mayor materia orgánica','retener siempre toda el agua','ser idéntico a la arcilla','no permitir ningún intercambio'],0,'propiedades del suelo','media','El tamaño de partículas y la materia orgánica influyen en retención y drenaje.'],
   [[4,0,3],'La vegetación ayuda a disminuir la erosión porque:', ['sus raíces estabilizan el suelo y reducen el arrastre','aumenta siempre la velocidad del agua','elimina la lluvia','convierte el suelo en metal'],0,'erosión','básica','Las raíces sujetan partículas y la cobertura reduce el impacto del agua.'],
   [[5,0,0],'En un experimento sobre luz y crecimiento, la cantidad de luz es la variable:', ['dependiente','independiente','controlada','aleatoria necesariamente'],1,'variables experimentales','básica','Es la condición que el investigador modifica deliberadamente.'],
   [[5,0,2],'Si los resultados no permiten responder la pregunta inicial, una mejora razonable es:', ['modificar el diseño justificando qué variable se controlará','borrar los resultados','cambiar la hipótesis después sin explicar','elegir solo el dato favorable'],0,'diseño experimental','alta','La mejora debe relacionarse con el propósito y hacerse explícita.'],
   [[6,0,1],'Para enseñar densidad, una representación pertinente es:', ['comparar masas y volúmenes de objetos y relacionarlos','memorizar la palabra sin medir','usar únicamente una definición','evitar tablas y gráficos'],0,'representación de contenidos','media','La relación entre masa y volumen se hace visible con mediciones y representaciones.'],
   [[6,0,2],'Ante una explicación alternativa de un estudiante, la intervención más formativa es:', ['pedir evidencia, contrastar el modelo y revisar la explicación','decir solo que está mal','ignorarla','calificar sin retroalimentar'],0,'intervención pedagógica','media','La evidencia permite hacer visible y reconstruir el razonamiento.'],
   [[6,1,0],'Antes de abordar circuitos eléctricos, es especialmente útil explorar si el curso comprende:', ['que un circuito requiere un camino cerrado','los nombres de todos los científicos','la clasificación de rocas','la escala de temperatura'],0,'conocimientos previos','básica','La idea de camino cerrado sostiene la comprensión inicial del circuito.'],
   [[6,1,1],'Si un estudiante cree que una pila “produce corriente sin circuito”, conviene:', ['usar un esquema de circuito cerrado y pedirle predecir qué ocurre al abrirlo','entregar la respuesta sin discutir','cambiar a otro tema','pedir copiar una definición'],0,'aprendizaje desde el error','media','La predicción permite confrontar la concepción con una evidencia observable.'],
   [[6,2,0],'Para evaluar la habilidad de formular una hipótesis, la evidencia más directa es:', ['una hipótesis vinculada a variables y una justificación','colorear un esquema','repetir vocabulario','anotar la fecha'],0,'evaluación de ciencias','media','La evidencia debe mostrar relación entre variables y una explicación anticipada.'],
   [[6,2,1],'Una pauta de observación es pertinente cuando:', ['define conductas o desempeños observables vinculados al objetivo','solo registra si el estudiante asistió','reemplaza todos los criterios','no permite anotar evidencias'],0,'instrumentos de evaluación','básica','Los criterios observables permiten recoger evidencia del desempeño.']
  ],
  'basica-historia':[
   [[0,0,2],'Al comparar un mapa físico y uno político de Chile, una diferencia central es que:', ['el físico representa relieve y el político límites y divisiones','ambos muestran exactamente la misma información','el político solo muestra temperaturas','el físico no permite localizar lugares'],0,'representaciones espaciales','básica','Cada representación selecciona información según su propósito.'],
   [[0,1,1],'La zona central de Chile se caracteriza, entre otros aspectos, por:', ['clima mediterráneo en gran parte de su extensión y alta concentración de población','ausencia total de actividades productivas','clima polar en todo el territorio','no presentar variaciones de relieve'],0,'zonas naturales','media','La caracterización combina clima, población, relieve y actividades.'],
   [[0,2,0],'Una actividad productiva puede generar un efecto ambiental a largo plazo cuando:', ['modifica sostenidamente agua, suelo o biodiversidad','solo cambia el precio de un producto','ocurre durante un día','no interactúa con el entorno'],0,'impactos productivos','media','Los efectos ambientales pueden acumularse y persistir en el tiempo.'],
   [[1,0,1],'La diacronía permite analizar:', ['cambios de un fenómeno a través del tiempo','solo elementos simultáneos','únicamente la ubicación espacial','una fuente sin contexto'],0,'pensamiento temporal','básica','La diacronía sigue transformaciones en distintos momentos.'],
   [[1,1,0],'Una semejanza entre Grecia y Roma antiguas puede estudiarse mediante:', ['comparar instituciones, vida cotidiana y legado con evidencias','suponer que fueron idénticas','describir solo sus nombres','ignorar sus diferencias'],0,'civilizaciones antiguas','media','Comparar exige establecer criterios, semejanzas y diferencias.'],
   [[1,1,4],'Para contrastar dos relatos sobre la conquista, conviene revisar primero:', ['autoría, propósito, contexto y evidencias','solo cuál es más extenso','el color del documento','qué relato aparece primero'],0,'análisis de fuentes','alta','La crítica de fuentes considera producción, propósito y respaldo.'],
   [[1,1,6],'Una fuente sobre la independencia resulta más útil cuando:', ['se interpreta en su contexto y se relaciona con otras evidencias','se toma como descripción neutral absoluta','se copia sin analizar','se elige por su antigüedad solamente'],0,'independencia y fuentes','media','Contextualizar y corroborar permite valorar alcance y límites.'],
   [[1,1,12],'Para analizar una dictadura, una fuente testimonial debe:', ['examinarse como una perspectiva situada y contrastarse con otras fuentes','descartarse por ser personal','considerarse siempre completa','usarse sin identificar autor'],0,'historia reciente','alta','El testimonio aporta una perspectiva y requiere contextualización y contraste.'],
   [[2,0,2],'La participación ciudadana en democracia incluye:', ['informarse, deliberar y participar respetando derechos','obedecer sin poder opinar','eliminar controles institucionales','reemplazar elecciones por decisiones privadas'],0,'democracia','básica','La participación democrática combina derechos, responsabilidades y deliberación.'],
   [[3,0,0],'Una actividad de Historia está bien alineada cuando:', ['la tarea exige la habilidad y el contenido indicados en el objetivo','solo es entretenida','usa muchas imágenes sin propósito','evalúa un contenido distinto'],0,'estrategias de enseñanza','media','La alineación relaciona objetivo, actividad y evidencia.'],
   [[3,0,1],'Para enseñar causalidad histórica, una estrategia adecuada es:', ['analizar varias condiciones y evidencias, evitando atribuirlo todo a una sola causa','memorizar una fecha aislada','ordenar apellidos','copiar un resumen'],0,'pensamiento histórico','media','La causalidad histórica suele involucrar condiciones y perspectivas múltiples.'],
   [[3,0,2],'Una línea de tiempo es más útil si:', ['incluye escala temporal, hechos seleccionados y relaciones explicadas','acumula fechas sin criterio','mezcla pasado y presente sin orden','omite la duración'],0,'recursos didácticos','básica','La representación debe apoyar duración, sucesión y relaciones temporales.'],
   [[3,0,4],'Para trabajar fuentes históricas en grupos, conviene:', ['asignar preguntas de análisis y pedir que fundamenten coincidencias y diferencias','pedir copiar el documento','evitar discutir perspectivas','calificar solo la rapidez'],0,'actividades de aprendizaje','media','Las preguntas y la fundamentación hacen visible el análisis.'],
   [[3,1,0],'Antes de estudiar la organización política de Chile, es útil explorar:', ['qué entienden por autoridad, normas y participación','solo nombres de presidentes','la tabla periódica','reglas ortográficas'],0,'conocimientos previos','básica','Los conceptos previos sostienen la comprensión de instituciones.'],
   [[3,1,1],'Si un estudiante confunde fuente primaria y secundaria, una intervención pertinente es:', ['comparar ejemplos y analizar cuándo y para qué se produjo cada uno','pedir memorizar dos definiciones','decir que toda fuente es igual','evitar usar fuentes'],0,'aprendizaje y retroalimentación','media','La comparación de ejemplos permite reconstruir el criterio de clasificación.'],
   [[3,2,0],'Una pregunta de evaluación sobre interpretación de un mapa debería pedir:', ['usar información del mapa y justificar una conclusión','recordar un color sin contexto','copiar el título','responder solo sí o no'],0,'evaluación histórica','media','La tarea debe producir evidencia de interpretación y justificación.'],
   [[3,2,1],'Una rúbrica es adecuada para una explicación histórica si incluye:', ['criterios de uso de evidencias, temporalidad y claridad de la explicación','solo cantidad de palabras','preferencias personales del docente','asistencia'],0,'instrumentos de evaluación','básica','Los criterios deben corresponder al desempeño esperado.'],
   [[0,0,0],'La latitud se mide tomando como referencia principal:', ['el ecuador','el meridiano de Greenwich','el nivel del mar','la línea costera'],0,'latitud y longitud','básica','La latitud indica distancia angular al norte o sur del ecuador.'],
   [[0,1,3],'Para interpretar un territorio a partir de diversas fuentes, es necesario:', ['relacionar datos de mapas, gráficos y textos considerando sus escalas','usar solo una imagen','ignorar la leyenda','sumar todos los datos sin contexto'],0,'interpretación geográfica','media','Las fuentes se complementan y deben leerse según escala y propósito.'],
   [[2,0,0],'El Estado de derecho supone que:', ['autoridades y ciudadanía están sometidas a normas y derechos','una autoridad puede actuar sin límites','las leyes se aplican solo a algunas personas','no existen controles'],0,'Estado de derecho','básica','El Estado de derecho limita el poder y protege derechos mediante normas.']
  ],
  'basica-ingles':[
   [[0,0,4],'Read: “The library opened a quiet study room after students requested a space for group work.” What can be concluded?', ['The room was created in response to a student need','Students never use the library','The library closed permanently','Group work is forbidden'],0,'reading inference','media','The sentence links the opening to students’ request.'],
   [[0,1,0],'In “The project was challenging, but the team completed it”, what does “it” refer to?', ['the team','the project','the challenge','the sentence'],1,'reference','básica','The pronoun refers to the project mentioned before.'],
   [[1,0,8],'Which classroom task best assesses the purpose of an oral announcement?', ['Choose the announcement’s purpose after listening','Copy every word without listening','Underline unrelated verbs','Draw a map'],0,'listening comprehension','media','The task directly asks learners to identify communicative purpose.'],
   [[1,0,5],'A listener hears “Could you repeat that, please?” The speaker is probably:', ['asking for clarification','saying goodbye','giving a final grade','describing a past event'],0,'oral interaction','básica','The expression is used to request repetition or clarification.'],
   [[1,1,0],'In “The instructions were unclear, so we asked for help”, “so” expresses:', ['result','contrast','time','condition'],0,'lexical meaning in context','básica','The second clause is a result of the first.'],
   [[2,0,0],'Which sentence correctly uses the present perfect?', ['She has visited the museum twice','She have visit the museum twice','She visited has the museum','She has visiting the museum'],0,'verb tenses','básica','Present perfect uses has/have plus the past participle.'],
   [[2,0,3],'Which sentence uses reported speech correctly?', ['He said that he was tired','He said that I am tired yesterday','He say he was tired','He said he tired was'],0,'complex structures','media','The reported clause follows an appropriate tense and word order.'],
   [[2,0,5],'Which connector best completes: “The task was difficult; ___, the learners persevered”?', ['however','because','first','unless'],0,'cohesion','media','However signals contrast between difficulty and perseverance.'],
   [[3,0,1],'Which activity follows an active methodology?', ['Learners solve a real problem collaboratively and explain their decisions','Learners copy a word list silently','The teacher reads all answers','Learners memorize a rule without using it'],0,'active methodologies','media','The task requires purposeful action, collaboration and explanation.'],
   [[3,0,2],'A sequence that develops speaking progressively should:', ['move from supported rehearsal to meaningful interaction and reflection','start with an unprepared long speech only','avoid feedback','assess grammar unrelated to the task'],0,'communicative sequence','alta','Scaffolding and meaningful interaction support progressive development.'],
   [[3,0,3],'To support multimodal production, a teacher should:', ['model how words, images and sound work together for a communicative purpose','grade only spelling','ban visual resources','ask learners to copy a paragraph'],0,'multimodal production','media','Multimodal communication combines modes intentionally for meaning.'],
   [[3,0,4],'A culturally responsive English task should:', ['present perspectives and invite comparison without stereotyping','reduce culture to flags and food only','declare one culture normal','avoid learners’ experiences'],0,'culture and language','alta','Comparison of perspectives supports critical and respectful intercultural learning.'],
   [[3,1,0],'For learners to reflect on language learning, an assessment can ask them to:', ['identify a strategy used, evidence of progress and a next goal','choose the longest answer','copy a mark','avoid discussing process'],0,'assessment reflection','media','Reflection connects strategy, evidence and a next step.'],
   [[3,1,2],'Which assessment is aligned with the objective “write a short invitation”?', ['Write an invitation for a real or simulated event using the intended conventions','Name ten grammar terms','Circle all nouns in a story','Listen to an unrelated song'],0,'assessment alignment','básica','The task elicits the exact written performance in context.'],
   [[0,0,1],'Read: “Mara missed the bus, so she arrived after the meeting began.” Why did Mara arrive late?', ['She missed the bus','She forgot the meeting','The meeting was cancelled','She left early'],0,'literal comprehension','básica','The text explicitly states the cause.'],
   [[0,0,6],'In a text about recycling, the word “reduce” most likely means:', ['use less','decorate','repeat','transport'],0,'vocabulary in context','básica','The environmental context supports the meaning use less.'],
   [[1,0,9],'An exchange in which a customer asks for a product and a clerk responds is mainly:', ['a service interaction','a scientific experiment','a narrative description','a weather report'],0,'communicative situation','básica','The participants and purpose define a service interaction.'],
   [[1,0,2],'After listening to instructions, the best evidence of local comprehension is:', ['selecting the correct step mentioned in the instructions','writing an unrelated opinion','drawing a character','memorizing the speaker’s name only'],0,'local listening','media','Selecting a specific step shows understanding of local information.'],
   [[2,0,7],'In “Please close the window”, the speaker is primarily:', ['making a request','telling a past story','expressing probability','comparing two objects'],0,'language functions','básica','The imperative form functions as a request or instruction.'],
   [[3,1,3],'Formative feedback on a speaking task should:', ['name an observed strength, one actionable improvement and a chance to try again','only assign a score','correct unrelated spelling','compare learners publicly'],0,'formative feedback','media','Actionable feedback becomes useful when learners can apply it.']
  ],
  'basica-lenguaje':[
   [[0,0,0],'En un relato, el narrador que participa como personaje cuenta desde una perspectiva:', ['interna y limitada a su experiencia','totalmente externa y omnisciente','sin relación con los hechos','exclusivamente científica'],0,'narrativa','media','Un narrador personaje conoce y cuenta desde su experiencia situada.'],
   [[0,0,4],'En “El silencio gritaba en la sala”, el efecto principal del lenguaje figurado es:', ['intensificar una sensación mediante una contradicción expresiva','entregar una medida exacta','informar una fecha','describir un sonido literal'],0,'lenguaje figurado','media','La personificación y paradoja intensifican la sensación de tensión o ausencia.'],
   [[0,1,2],'Un artículo incluye un gráfico que muestra la evolución de una cifra. Para interpretarlo es necesario:', ['relacionar título, ejes, unidades y datos con el texto','leer solo el color más fuerte','ignorar la fuente','sumar todos los valores sin contexto'],0,'textos discontinuos','media','La lectura del gráfico depende de sus elementos y de la relación con el texto.'],
   [[0,1,5],'La función principal de un titular periodístico es:', ['presentar de manera condensada el hecho o tema central','expresar siempre la opinión del lector','reemplazar toda evidencia','indicar únicamente el lugar'],0,'textos periodísticos','básica','El titular orienta al lector sobre el contenido principal.'],
   [[1,0,0],'En “Sofía llevó el libro a la sala y allí lo dejó”, la palabra “allí” contribuye a:', ['cohesionar al texto mediante una referencia espacial','introducir una opinión','cambiar el tiempo verbal','crear una rima'],0,'cohesión','básica','El adverbio retoma un lugar mencionado o inferible.'],
   [[1,1,0],'¿Cuál palabra está correctamente tildada?', ['examen','lápiz','camion','facil'],1,'ortografía','básica','Lápiz es una palabra grave terminada en consonante distinta de n o s.'],
   [[1,1,1],'En una discusión, reformular lo dicho por otra persona permite:', ['comprobar comprensión antes de responder','evitar escuchar','imponer la propia opinión','cerrar siempre el diálogo'],0,'gestión del diálogo','media','La reformulación verifica el sentido y favorece el intercambio.'],
   [[2,0,0],'Para enseñar a inferir información, una actividad adecuada es:', ['pedir una conclusión y justificarla con pistas del texto','entregar la conclusión sin leer','copiar palabras aisladas','evaluar solo caligrafía'],0,'comprensión lectora','media','Inferir exige relacionar pistas textuales con conocimientos pertinentes.'],
   [[2,0,2],'Durante la planificación de un texto, es útil definir primero:', ['propósito, destinatario y organización de las ideas','solo el color de la portada','la nota final','la cantidad de errores'],0,'proceso de escritura','básica','Estas decisiones orientan contenido, registro y estructura.'],
   [[2,0,4],'Para acompañar una investigación escolar, el docente debería:', ['modelar cómo formular preguntas, evaluar fuentes y registrar referencias','entregar una única página para copiar','prohibir comparar fuentes','evaluar solo la portada'],0,'investigación','alta','La investigación requiere preguntas, criterios de fuentes y documentación.'],
   [[2,0,5],'Una retroalimentación comprensible sobre un texto debería:', ['señalar una evidencia concreta y proponer una revisión posible','decir únicamente “mejorar”','corregir sin explicar','comparar con otro estudiante'],0,'retroalimentación','media','La evidencia y la acción siguiente hacen operativa la retroalimentación.'],
   [[2,1,0],'Antes de trabajar conectores, conviene explorar si el curso comprende:', ['las relaciones de causa, contraste y consecuencia','los nombres de todos los autores','la cantidad de páginas','el diseño de una portada'],0,'conocimientos previos','básica','Reconocer relaciones semánticas sostiene el uso de conectores.'],
   [[2,1,1],'Si un estudiante interpreta literalmente una metáfora, una intervención pertinente es:', ['comparar sentido literal y figurado usando pistas del fragmento','decir solo la respuesta','eliminar las metáforas','pedir memorizar definiciones'],0,'aprendizaje desde el error','media','La comparación permite reconstruir cómo el recurso aporta significado.'],
   [[2,2,0],'Para evaluar la comprensión de una noticia, una tarea pertinente es:', ['identificar información, propósito y evidencias que la respaldan','copiar el titular','contar sus palabras','colorear una imagen'],0,'evaluación de lectura','media','La tarea recoge desempeños centrales de comprensión crítica.'],
   [[2,2,1],'Un indicador de escritura debería describir:', ['un desempeño observable que pueda evidenciarse en el texto','una preferencia estética del docente','la cantidad de hojas','la velocidad de escritura'],0,'indicadores de evaluación','básica','Un indicador debe orientar qué aprendizaje se observará.'],
   [[0,0,3],'En “La noche abrazó las casas”, el recurso literario permite:', ['representar la noche mediante una acción humana','informar la hora exacta','comparar dos cantidades','explicar una regla ortográfica'],0,'figuras literarias','básica','La acción abrazar se atribuye figuradamente a la noche.'],
   [[0,1,4],'La diferencia entre un hecho y una opinión se reconoce principalmente porque:', ['el hecho puede contrastarse con evidencias y la opinión expresa valoración','la opinión siempre es falsa','el hecho siempre es más largo','no existen criterios para distinguirlos'],0,'lectura crítica','media','La verificabilidad y la valoración son criterios útiles, aunque una opinión puede estar argumentada.'],
   [[1,1,2],'Para buscar un acuerdo, una intervención adecuada es:', ['proponer una razón, escuchar la respuesta y ajustar la propuesta si corresponde','repetir la misma idea más fuerte','interrumpir','cambiar de tema'],0,'comunicación oral','media','El diálogo orientado a acuerdos requiere razones, escucha y revisión.'],
   [[2,0,7],'Un recurso didáctico es pertinente cuando:', ['facilita el aprendizaje que el objetivo busca hacer visible','es el más llamativo','tiene más colores','reemplaza toda interacción'],0,'selección de recursos','básica','La pertinencia depende de la relación entre recurso y aprendizaje.'],
   [[2,2,2],'Para evaluar una exposición oral, es más válido usar criterios de:', ['organización, claridad, uso de evidencias y adecuación a la audiencia','color de la cartulina únicamente','cantidad de diapositivas','preferencia del docente'],0,'evaluación oral','media','Los criterios deben corresponder al desempeño comunicativo.']
  ],
  'media-lengua':[
   [[0,0,0],'En “Sus palabras fueron cuchillos”, la imagen contribuye a:', ['representar el efecto hiriente de las palabras','informar que había armas reales','describir una medida','indicar el lugar de la escena'],0,'figuras literarias','media','La metáfora intensifica el efecto emocional del discurso.'],
   [[0,0,2],'Una narración comienza por el desenlace y luego reconstruye hechos anteriores. ¿Qué procedimiento utiliza?', ['anacronía o alteración del orden temporal','descripción objetiva únicamente','rima consonante','diálogo directo'],0,'técnicas narrativas','alta','La secuencia altera el orden cronológico mediante una retrospección o anticipación.'],
   [[0,0,3],'En un texto dramático, el conflicto se construye principalmente mediante:', ['acciones y parlamentos de personajes en una situación escénica','la voz de un narrador omnisciente siempre','tablas estadísticas','notas al pie'],0,'mundo dramático','básica','El drama presenta conflicto a través de acción, diálogo y situación escénica.'],
   [[0,1,1],'En un discurso argumentativo, la tesis corresponde a:', ['la posición central que se busca sostener','un dato aislado sin relación','el saludo final','la descripción del escenario'],0,'discurso argumentativo','básica','La tesis es la postura que organiza las razones.'],
   [[0,1,2],'Un argumento basado en datos verificables utiliza principalmente:', ['evidencia que respalda la afirmación','un ataque a la persona','una repetición emotiva','una contradicción sin prueba'],0,'tipos de argumentos','media','Los datos pertinentes funcionan como evidencia para apoyar una afirmación.'],
   [[0,1,8],'Una estrategia de persuasión que presenta solo dos opciones cuando existen más alternativas incurre en:', ['falsa dicotomía','analogía pertinente','definición','ejemplo suficiente'],0,'medios y persuasión','alta','La falsa dicotomía reduce indebidamente las opciones posibles.'],
   [[1,0,0],'En “El equipo trabajó con cuidado; por eso, terminó antes”, “por eso” introduce:', ['una consecuencia','una oposición','una condición','una enumeración'],0,'cohesión','básica','El conector relaciona el trabajo cuidadoso con su consecuencia.'],
   [[1,0,2],'La progresión temática de un texto se refiere a:', ['cómo se desarrolla y relaciona la información a lo largo del texto','la cantidad de adjetivos','el tamaño de la letra','solo la puntuación'],0,'progresión temática','media','La progresión organiza la información nueva y retomada.'],
   [[1,1,0],'En “Tal vez la medida sea eficaz”, “tal vez” expresa:', ['modalización de posibilidad','certeza absoluta','orden temporal','referencia espacial'],0,'modalización','básica','El adverbio modaliza el enunciado como posible, no seguro.'],
   [[1,1,2],'En un debate formal, una práctica adecuada es:', ['responder la razón del interlocutor y apoyar la propia con evidencia','interrumpir para ganar tiempo','atacar a la persona','repetir la tesis sin escuchar'],0,'argumentación oral','media','La argumentación formal requiere razones, escucha y evidencia.'],
   [[2,0,0],'Para enseñar a interpretar un ensayo, conviene modelar cómo:', ['identificar tesis, argumentos, relaciones y evidencias del texto','memorizar nombres sin leer','copiar el primer párrafo','calificar solo ortografía'],0,'comprensión lectora','media','El modelado hace visible el proceso de lectura analítica.'],
   [[2,0,1],'En una investigación literaria, una fuente debe seleccionarse considerando:', ['autoridad, propósito, pertinencia y relación con la pregunta','solo su diseño visual','que sea la primera del buscador','que no tenga fecha'],0,'investigación','alta','La evaluación de fuentes relaciona confiabilidad y propósito de investigación.'],
   [[2,0,3],'Para explicar un concepto complejo, una representación pertinente puede:', ['combinar definición, ejemplo, contraejemplo y esquema','repetir el término muchas veces','eliminar el contexto','usar tecnicismos sin explicar'],0,'representación de contenidos','media','Las representaciones múltiples apoyan comprensión y transferencia.'],
   [[2,0,4],'Una intervención pedagógica favorece el aprendizaje cuando:', ['recoge evidencia del razonamiento y ajusta la ayuda al problema observado','entrega la solución antes de escuchar','mantiene la misma explicación siempre','evalúa sin retroalimentar'],0,'decisiones pedagógicas','media','La evidencia permite ajustar la enseñanza a la necesidad real.'],
   [[2,0,5],'Un criterio de evaluación para una interpretación literaria debería valorar:', ['coherencia de la lectura y uso de evidencias textuales','cantidad de palabras únicamente','preferencia por un género','caligrafía'],0,'evaluación literaria','básica','La interpretación se sostiene mediante una lectura coherente y evidencias.'],
   [[0,0,5],'En un cómic, el cambio de tamaño de una viñeta puede:', ['jerarquizar un momento y modificar el ritmo de lectura','eliminar toda narración','indicar siempre una medida real','reemplazar el conflicto'],0,'cómic y recursos literarios','media','La composición visual orienta énfasis, ritmo y sentido.'],
   [[0,1,0],'La situación de enunciación de un texto informativo considera:', ['emisor, destinatario, propósito y contexto','solo la cantidad de párrafos','la rima','la biografía completa del lector'],0,'situación comunicativa','básica','Estos elementos permiten interpretar para qué y para quién se comunica.'],
   [[0,1,3],'En un discurso público, la introducción suele:', ['presentar tema, propósito y orientar a la audiencia','mostrar todas las conclusiones primero','evitar al destinatario','reemplazar las evidencias'],0,'discurso público','media','La introducción establece marco y orientación para la audiencia.'],
   [[1,1,3],'Una situación argumentativa formal se distingue porque:', ['define propósito, audiencia, razones y normas de interacción','impide toda evidencia','solo busca entretener','no requiere organización'],0,'argumentación formal','media','La formalidad exige adecuación al propósito, audiencia y estructura.'],
   [[2,2,1],'La retroalimentación formativa es más útil cuando:', ['se entrega a tiempo, se vincula con criterios y permite revisar el desempeño','solo aparece al final del año','usa una nota sin explicación','compara públicamente'],0,'retroalimentación','básica','La oportunidad y los criterios permiten actuar sobre la evidencia.']
  ]
 };
 function add(sid,items){
  const isMath=sid===math, pack=window.PE22_CONTENT&&window.PE22_CONTENT[sid];if(!isMath&&!pack)return;
  const domains=window.PE_SYLLABUS_2026[sid]||window.ECEP_DATA;
  items.forEach((row,n)=>{const [at,q,o,a,skill,diff,e]=row;let d,s,indicator;
   if(isMath){d=domains[at[0]];s=d[1][at[1]];indicator=s[1][at[2]]}
   else{d=domains[at[0]];s=d[1][at[1]];indicator=s[1][at[2]]}
   if(!d||!s||!indicator)throw new Error('Indicador inválido '+sid+' '+at.join('-'));
   const indicatorId=at.join('-'),id=sid+'-28-'+String(n+1).padStart(2,'0'), explanations=o.map((x,i)=>i===a?e:'Esta alternativa no se ajusta a la evidencia o confunde el concepto central.');
   const item={id,d:d[0],i:s[0],q,o,a,e,explanations,diff,skill,specialtyId:sid,indicatorId,indicator,origin:'Contenido propio ProfeECEP',version:'2.8'};
   if(isMath)window.QBANK.push(item);else pack.questions.push(item);
  });
 }
 Object.entries(packs).forEach(([sid,items])=>{if(sid===math && window.PE_ACTIVE_SPECIALTY!==math)return;add(sid,items)});
 window.PE22_ACTIVATE();
 window.PE28_BANK={counts:Object.fromEntries(Object.entries(packs).map(([id])=>[id,(id===math?window.QBANK.length:(window.PE22_CONTENT[id]?.questions.length||0))]))};
}());
