window.ECEP_DATA=[
["Números",[["1.1 Sistemas numéricos",["Múltiplos, factores, divisibilidad y números primos","Orden y comparación de enteros y racionales","Problemas con operaciones y números racionales"]],["1.2 Proporciones y porcentajes",["Representaciones de proporcionalidad directa e inversa","Reconocimiento de relaciones proporcionales y no proporcionales","Problemas de proporcionalidad directa o inversa","Cálculo e interpretación de porcentajes"]],["1.3 Potencias y raíces",["Problemas con potencias de base real y exponente entero","Operaciones con potencias de base fraccionaria o decimal"]]]],
["Álgebra",[["2.1 Lenguaje algebraico",["Reglas de formación en secuencias numéricas","Traducción entre lenguaje natural, numérico y algebraico","Modelación algebraica de proporciones, porcentajes y potencias"]],["2.2 Ecuaciones e inecuaciones lineales",["Modelación con ecuaciones e inecuaciones lineales","Problemas mediante ecuaciones e inecuaciones","Resolución con coeficientes enteros o fraccionarios"]],["2.3 Funciones",["Dominio y recorrido","Variables dependientes e independientes","Parámetros de funciones lineal y afín","Modelación con funciones lineales o afines"]]]],
["Geometría",[["3.1 Figuras y cuerpos geométricos",["Construcción de triángulos","Clasificación de polígonos y cuerpos","Ejes y centros de simetría","Propiedades de polígonos","Propiedades de la circunferencia"]],["3.2 Perímetros, áreas y volúmenes",["Perímetros y áreas de figuras planas","Perímetros, áreas y volúmenes","Familias de figuras según simetría","Áreas de figuras compuestas"]],["3.3 Transformaciones isométricas",["Congruencia y transformaciones","Traslaciones, reflexiones y rotaciones","Transformaciones en naturaleza y arte"]]]],
["Datos y azar",[["4.1 Estadística",["Interpretación y comparación de gráficos","Medidas de tendencia central","Selección de indicador estadístico pertinente","Población y muestra"]],["4.2 Probabilidad",["Espacio muestral y eventos","Frecuencia relativa","Principio multiplicativo","Modelo de Laplace"]]]],
["Enseñanza-aprendizaje",[["5.1 Estrategias de enseñanza",["Estrategias y actividades","Representaciones de contenidos","Decisiones e intervenciones docentes","Selección de recursos","Actividades según énfasis curriculares","Estrategias ante dificultades"]],["5.2 Aprendizaje",["Conocimientos previos","Errores comunes y aprendizaje desde el error"]],["5.3 Evaluación",["Indicadores y desempeños","Actividades, estrategias e instrumentos de evaluación"]]]]
];

window.QBANK=[
{id:"n1",d:"Números",i:"1.1 Sistemas numéricos",q:"¿Cuál de los siguientes números es primo?",o:["21","29","39","51"],a:1,e:"29 solo tiene como divisores positivos a 1 y 29."},
{id:"n2",d:"Números",i:"1.2 Proporciones y porcentajes",q:"Una chaqueta cuesta $40.000 y tiene 25% de descuento. ¿Cuál es el precio final?",o:["$10.000","$30.000","$35.000","$37.500"],a:1,e:"El 25% de $40.000 es $10.000. Al restarlo al precio original quedan $30.000."},
{id:"n3",d:"Números",i:"1.2 Proporciones y porcentajes",q:"Si 4 cuadernos cuestan $6.000 y el precio es directamente proporcional, ¿cuánto cuestan 10 cuadernos?",o:["$12.000","$15.000","$18.000","$24.000"],a:1,e:"Cada cuaderno cuesta $1.500; 10 cuestan $15.000."},
{id:"a1",d:"Álgebra",i:"2.1 Lenguaje algebraico",q:"¿Qué expresión representa 'el doble de un número disminuido en 7'?",o:["2x-7","2(x-7)","x-14","7-2x"],a:0,e:"El doble de un número es 2x y luego se disminuye en 7."},
{id:"a2",d:"Álgebra",i:"2.2 Ecuaciones e inecuaciones lineales",q:"¿Qué ecuación representa: 'el triple de un número, aumentado en 5, es 26'?",o:["3x+5=26","3(x+5)=26","x+15=26","5x+3=26"],a:0,e:"'El triple de un número' es 3x y luego se aumenta en 5."},
{id:"a3",d:"Álgebra",i:"2.3 Funciones",q:"En la función y=4x+2, ¿qué representa el número 4?",o:["El intercepto con el eje y","La pendiente","El dominio","El recorrido"],a:1,e:"En una función afín y=mx+n, m corresponde a la pendiente."},
{id:"g1",d:"Geometría",i:"3.1 Figuras y cuerpos geométricos",q:"¿Cuál conjunto de longitudes puede formar un triángulo?",o:["2, 3 y 6","4, 5 y 8","1, 2 y 4","3, 3 y 7"],a:1,e:"La suma de dos lados debe ser mayor que el tercero. Para 4, 5 y 8 se cumplen las desigualdades necesarias."},
{id:"g2",d:"Geometría",i:"3.2 Perímetros, áreas y volúmenes",q:"Un rectángulo mide 8 cm de largo y 5 cm de ancho. ¿Cuál es su área?",o:["13 cm²","26 cm²","40 cm²","80 cm²"],a:2,e:"El área de un rectángulo se obtiene multiplicando largo por ancho: 8×5=40 cm²."},
{id:"g3",d:"Geometría",i:"3.3 Transformaciones isométricas",q:"¿Qué transformación conserva forma y tamaño y gira una figura alrededor de un punto?",o:["Traslación","Rotación","Homotecia","Proyección"],a:1,e:"La rotación gira una figura alrededor de un centro conservando distancias y ángulos."},
{id:"d1",d:"Datos y azar",i:"4.1 Estadística",q:"Para los datos 4, 4, 6, 8, 8, ¿cuál es la mediana?",o:["4","6","8","30"],a:1,e:"Ordenados los datos, el valor central es 6."},
{id:"d2",d:"Datos y azar",i:"4.2 Probabilidad",q:"En una bolsa hay 3 fichas rojas y 2 azules. Si todas tienen igual probabilidad de salir, ¿cuál es la probabilidad de obtener una azul?",o:["2/3","2/5","3/5","1/2"],a:1,e:"Hay 5 resultados elementales posibles y 2 favorables: 2/5."},
{id:"d3",d:"Datos y azar",i:"4.2 Probabilidad",q:"Se lanzan una moneda y un dado de 6 caras. ¿Cuántos resultados posibles tiene el experimento?",o:["6","8","12","18"],a:2,e:"Por el principio multiplicativo: 2 resultados de la moneda × 6 del dado = 12."},
{id:"p1",d:"Enseñanza-aprendizaje",i:"5.1 Estrategias de enseñanza",q:"Para introducir el concepto de fracción equivalente, ¿qué recurso favorece mejor una comprensión inicial?",o:["Solo entregar la regla de amplificación","Usar representaciones visuales de una misma cantidad dividida de distintas maneras","Pedir memorizar una lista de fracciones","Comenzar con una prueba sumativa"],a:1,e:"Las representaciones múltiples permiten observar que distintas fracciones pueden representar la misma cantidad."},
{id:"p2",d:"Enseñanza-aprendizaje",i:"5.2 Aprendizaje",q:"Un estudiante afirma que 0,8 es menor que 0,35 porque '8 es menor que 35'. ¿Qué intervención aborda mejor el error conceptual?",o:["Pedirle memorizar la regla de comparación","Comparar ambos números con una representación que haga visible el valor posicional","Indicarle inmediatamente la respuesta correcta","Cambiar el ejercicio por números naturales"],a:1,e:"La dificultad está en el valor posicional. Una representación permite confrontar el razonamiento y reconstruir el concepto."},
{id:"p3",d:"Enseñanza-aprendizaje",i:"5.3 Evaluación",q:"Si el objetivo es evaluar si un estudiante puede justificar un procedimiento matemático, ¿qué evidencia es más pertinente?",o:["Una pregunta de verdadero o falso sin explicación","Una tarea donde deba resolver y explicar por qué su estrategia funciona","Una lista de fórmulas memorizadas","Registrar solo el tiempo que demora"],a:1,e:"La evidencia debe alinearse con el desempeño esperado: justificar requiere hacer visible el razonamiento."},
{id:"n4",d:"Números",i:"1.1 Sistemas numéricos",q:"¿Cuál es el máximo común divisor de 18 y 24?",o:["3","6","9","12"],a:1,e:"Los divisores comunes son 1, 2, 3 y 6; el mayor es 6."},
{id:"n5",d:"Números",i:"1.3 Potencias y raíces",q:"¿Cuál es el valor de (0,5)^2?",o:["0,10","0,25","1,00","2,50"],a:1,e:"0,5 × 0,5 = 0,25."},
{id:"n6",d:"Números",i:"1.3 Potencias y raíces",q:"¿Cuál expresión es equivalente a 2^3 × 2^4?",o:["2^7","4^7","2^12","4^12"],a:0,e:"Al multiplicar potencias de igual base se suman los exponentes: 2^(3+4)=2^7."},
{id:"a4",d:"Álgebra",i:"2.1 Lenguaje algebraico",q:"La secuencia 5, 8, 11, 14,... aumenta siempre en 3. ¿Qué expresión representa su término n?",o:["3n+2","5n+3","3n+5","2n+3"],a:0,e:"Para n=1, 3(1)+2=5; la diferencia constante es 3."},
{id:"a5",d:"Álgebra",i:"2.2 Ecuaciones e inecuaciones lineales",q:"¿Cuál es la solución de 4x-6=18?",o:["x=3","x=5","x=6","x=12"],a:2,e:"4x=24, por lo tanto x=6."},
{id:"a6",d:"Álgebra",i:"2.3 Funciones",q:"En una tabla, cuando x aumenta en 1, y aumenta siempre en 5. ¿Qué representa 5 en una función afín que modele la situación?",o:["El dominio","La pendiente","El recorrido","El intercepto"],a:1,e:"El cambio constante de y por unidad de x corresponde a la pendiente."},
{id:"g4",d:"Geometría",i:"3.1 Figuras y cuerpos geométricos",q:"¿Cuál afirmación es siempre verdadera para un cuadrado?",o:["Tiene solo un eje de simetría","Todos sus ángulos interiores son rectos","Sus diagonales tienen distinta longitud","No es un rectángulo"],a:1,e:"Un cuadrado tiene cuatro ángulos rectos."},
{id:"g5",d:"Geometría",i:"3.2 Perímetros, áreas y volúmenes",q:"Un cubo tiene arista de 3 cm. ¿Cuál es su volumen?",o:["9 cm³","18 cm³","27 cm³","36 cm³"],a:2,e:"El volumen de un cubo es a³: 3³=27 cm³."},
{id:"g6",d:"Geometría",i:"3.3 Transformaciones isométricas",q:"Una figura se desplaza 4 unidades a la derecha sin girar ni reflejarse. ¿Qué transformación se aplicó?",o:["Rotación","Reflexión","Traslación","Homotecia"],a:2,e:"Una traslación desplaza todos los puntos la misma distancia y dirección."},
{id:"d4",d:"Datos y azar",i:"4.1 Estadística",q:"En los datos 3, 4, 4, 5, 20, ¿qué medida resulta menos afectada por el valor 20?",o:["Media","Mediana","Rango","Suma"],a:1,e:"La mediana es resistente a valores extremos comparada con la media."},
{id:"d5",d:"Datos y azar",i:"4.1 Estadística",q:"Un investigador quiere estudiar hábitos de lectura de estudiantes de una escuela y encuesta a 80 de ellos. ¿Qué representan los 80 encuestados?",o:["La población","La muestra","La variable","La moda"],a:1,e:"La muestra es el subconjunto de la población que efectivamente se observa."},
{id:"d6",d:"Datos y azar",i:"4.2 Probabilidad",q:"Un dado justo se lanza una vez. ¿Cuál es la probabilidad de obtener un número mayor que 4?",o:["1/6","1/3","1/2","2/3"],a:1,e:"Los resultados favorables son 5 y 6: 2 de 6, equivalente a 1/3."},
{id:"p4",d:"Enseñanza-aprendizaje",i:"5.1 Estrategias de enseñanza",q:"Si el objetivo es que estudiantes comparen fracciones, ¿qué actividad entrega evidencia más directa del razonamiento?",o:["Copiar definiciones","Ordenar varias fracciones y justificar el criterio usado","Memorizar equivalencias","Completar ejercicios mecánicos sin explicar"],a:1,e:"Ordenar y justificar permite observar tanto la comparación como el razonamiento usado."},
{id:"p5",d:"Enseñanza-aprendizaje",i:"5.2 Aprendizaje",q:"Un estudiante suma 1/3+1/4 y responde 2/7. ¿Qué dificultad revela principalmente?",o:["Confunde suma de fracciones con suma independiente de numeradores y denominadores","No reconoce números naturales","No sabe multiplicar","Confunde área con perímetro"],a:0,e:"El procedimiento muestra que no comprende la necesidad de expresar fracciones con denominador común."},
{id:"p6",d:"Enseñanza-aprendizaje",i:"5.3 Evaluación",q:"¿Qué criterio mejora más la validez de una evaluación matemática?",o:["Que tenga muchas preguntas","Que las tareas se alineen con los objetivos e indicadores","Que todas las preguntas sean difíciles","Que use solo selección múltiple"],a:1,e:"La evaluación debe producir evidencia pertinente al aprendizaje que se pretende evaluar."},
{id:"n7",d:"Números",i:"1.1 Sistemas numéricos",q:"¿Cuál de los siguientes números es múltiplo de 6 y de 8 a la vez?",o:["24","36","42","54"],a:0,e:"24 es divisible por 6 y por 8.",diff:"media",skill:"propiedades numéricas"},
{id:"n8",d:"Números",i:"1.1 Sistemas numéricos",q:"¿Cuál es el orden correcto de menor a mayor?",o:["-0,8 < -3/4 < -0,6","-3/4 < -0,8 < -0,6","-0,6 < -3/4 < -0,8","-0,8 < -0,6 < -3/4"],a:0,e:"-0,8=-0,80; -3/4=-0,75; luego -0,80<-0,75<-0,60.",diff:"alta",skill:"comparación"},
{id:"n9",d:"Números",i:"1.2 Proporciones y porcentajes",q:"Una receta para 4 personas usa 300 g de arroz. ¿Cuánto arroz se necesita para 10 personas manteniendo la proporción?",o:["600 g","650 g","750 g","900 g"],a:2,e:"300/4=75 g por persona; 75×10=750 g.",diff:"media",skill:"modelación"},
{id:"n10",d:"Números",i:"1.2 Proporciones y porcentajes",q:"Un precio aumenta de $50.000 a $62.500. ¿Cuál fue el porcentaje de aumento?",o:["12,5%","20%","25%","30%"],a:2,e:"El aumento es $12.500, que corresponde al 25% de $50.000.",diff:"alta",skill:"porcentajes"},
{id:"n11",d:"Números",i:"1.3 Potencias y raíces",q:"¿Cuál es el valor de 3^2 ÷ 3?",o:["1","3","6","9"],a:1,e:"3^2=9 y 9÷3=3.",diff:"básica",skill:"cálculo"},
{id:"n12",d:"Números",i:"1.3 Potencias y raíces",q:"¿Qué ocurre con (1/2)^n cuando n aumenta?",o:["Aumenta sin límite","Permanece constante","Se acerca a 0","Se vuelve negativa"],a:2,e:"Al multiplicar reiteradamente por 1/2, los valores positivos disminuyen y se acercan a 0.",diff:"alta",skill:"interpretación"},

{id:"a7",d:"Álgebra",i:"2.1 Lenguaje algebraico",q:"¿Qué expresión representa 'la mitad de un número más 4'?",o:["x/2+4","(x+4)/2","2x+4","x/(2+4)"],a:0,e:"La mitad del número es x/2 y luego se suma 4.",diff:"básica",skill:"traducción algebraica"},
{id:"a8",d:"Álgebra",i:"2.1 Lenguaje algebraico",q:"En la secuencia 2, 6, 10, 14,... ¿cuál es el término 20?",o:["74","76","78","82"],a:2,e:"El término general es 4n-2; para n=20: 80-2=78.",diff:"alta",skill:"generalización"},
{id:"a9",d:"Álgebra",i:"2.2 Ecuaciones e inecuaciones lineales",q:"¿Cuál es la solución de 2(x+3)=14?",o:["x=4","x=5","x=7","x=10"],a:0,e:"x+3=7, por lo tanto x=4.",diff:"media",skill:"resolución"},
{id:"a10",d:"Álgebra",i:"2.2 Ecuaciones e inecuaciones lineales",q:"¿Qué inecuación representa 'un número aumentado en 4 es menor que 12'?",o:["x+4<12","x+4>12","4x<12","x-4<12"],a:0,e:"'Aumentado en 4' es x+4 y 'menor que 12' se representa con <.",diff:"media",skill:"modelación"},
{id:"a11",d:"Álgebra",i:"2.3 Funciones",q:"Si y=2x-3, ¿cuál es el valor de y cuando x=5?",o:["5","7","10","13"],a:1,e:"y=2(5)-3=7.",diff:"básica",skill:"evaluación de función"},
{id:"a12",d:"Álgebra",i:"2.3 Funciones",q:"¿Cuál de estas situaciones puede modelarse con una función lineal de la forma y=kx?",o:["Taxi con bajada de bandera más tarifa por km","Costo de manzanas a precio fijo por kg","Temperatura durante el día","Altura de una pelota lanzada"],a:1,e:"Si el precio por kg es constante y no hay costo fijo, el costo es directamente proporcional a la masa.",diff:"alta",skill:"modelación"},

{id:"g7",d:"Geometría",i:"3.1 Figuras y cuerpos geométricos",q:"¿Cuántas diagonales tiene un pentágono?",o:["3","5","7","10"],a:1,e:"Un pentágono tiene 5 diagonales.",diff:"media",skill:"propiedades geométricas"},
{id:"g8",d:"Geometría",i:"3.1 Figuras y cuerpos geométricos",q:"¿Cuál figura tiene infinitos ejes de simetría?",o:["Cuadrado","Rectángulo","Circunferencia","Triángulo equilátero"],a:2,e:"Toda recta que pasa por el centro de una circunferencia determina un eje de simetría.",diff:"media",skill:"simetría"},
{id:"g9",d:"Geometría",i:"3.2 Perímetros, áreas y volúmenes",q:"Un triángulo tiene base 12 cm y altura 5 cm. ¿Cuál es su área?",o:["17 cm²","30 cm²","60 cm²","120 cm²"],a:1,e:"A=(12×5)/2=30 cm².",diff:"básica",skill:"cálculo de área"},
{id:"g10",d:"Geometría",i:"3.2 Perímetros, áreas y volúmenes",q:"Una figura se compone de dos rectángulos de áreas 24 cm² y 15 cm² que no se superponen. ¿Cuál es el área total?",o:["9 cm²","24 cm²","39 cm²","360 cm²"],a:2,e:"Al no superponerse, las áreas se suman: 24+15=39 cm².",diff:"media",skill:"figuras compuestas"},
{id:"g11",d:"Geometría",i:"3.3 Transformaciones isométricas",q:"El punto (3,-2) se refleja respecto del eje y. ¿Cuál es su imagen?",o:["(-3,-2)","(3,2)","(-2,3)","(2,-3)"],a:0,e:"Reflejar respecto del eje y cambia el signo de x y conserva y.",diff:"media",skill:"transformaciones"},
{id:"g12",d:"Geometría",i:"3.3 Transformaciones isométricas",q:"¿Qué propiedad se conserva necesariamente en una isometría?",o:["El área pero no los ángulos","Las distancias entre puntos","La orientación siempre","Las coordenadas originales"],a:1,e:"Las isometrías conservan distancias y, por consecuencia, forma y tamaño.",diff:"alta",skill:"razonamiento geométrico"},

{id:"d7",d:"Datos y azar",i:"4.1 Estadística",q:"Los datos son 2, 4, 4, 6, 9. ¿Cuál es la moda?",o:["2","4","5","9"],a:1,e:"4 es el valor que aparece con mayor frecuencia.",diff:"básica",skill:"estadística descriptiva"},
{id:"d8",d:"Datos y azar",i:"4.1 Estadística",q:"En un gráfico de barras, la barra de A tiene altura 12 y la de B altura 18. ¿En cuánto supera B a A?",o:["6","12","18","30"],a:0,e:"18-12=6.",diff:"básica",skill:"interpretación de gráficos"},
{id:"d9",d:"Datos y azar",i:"4.1 Estadística",q:"Un conjunto tiene media 10. Si se agrega un valor extremadamente alto, ¿qué medida probablemente cambiará más?",o:["La media","La mediana","La moda necesariamente","El número de datos originales"],a:0,e:"La media es sensible a valores extremos.",diff:"media",skill:"interpretación estadística"},
{id:"d10",d:"Datos y azar",i:"4.2 Probabilidad",q:"Se lanza un dado justo. ¿Cuál es la probabilidad de obtener un número par?",o:["1/6","1/3","1/2","2/3"],a:2,e:"Hay 3 resultados pares de 6 posibles: 3/6=1/2.",diff:"básica",skill:"modelo de Laplace"},
{id:"d11",d:"Datos y azar",i:"4.2 Probabilidad",q:"Se eligen una camiseta de 3 colores y un pantalón de 2 colores. ¿Cuántas combinaciones distintas hay?",o:["5","6","8","9"],a:1,e:"3×2=6 combinaciones.",diff:"media",skill:"principio multiplicativo"},
{id:"d12",d:"Datos y azar",i:"4.2 Probabilidad",q:"En 100 lanzamientos una moneda mostró cara 57 veces. ¿Cuál es la frecuencia relativa de cara?",o:["0,43","0,50","0,57","57"],a:2,e:"57/100=0,57.",diff:"media",skill:"frecuencia relativa"},

{id:"p7",d:"Enseñanza-aprendizaje",i:"5.1 Estrategias de enseñanza",q:"Para trabajar proporcionalidad directa, ¿qué secuencia favorece mejor la comprensión?",o:["Fórmula → memorización → prueba","Situación contextualizada → tabla/gráfico → expresión simbólica","Solo ejercicios rutinarios","Definición escrita → tarea"],a:1,e:"Transitar por representaciones permite construir significado antes de formalizar.",diff:"media",skill:"diseño didáctico"},
{id:"p8",d:"Enseñanza-aprendizaje",i:"5.1 Estrategias de enseñanza",q:"Un recurso digital es pertinente principalmente cuando:",o:["Es novedoso","Reemplaza toda explicación docente","Apoya el objetivo y hace visible el razonamiento esperado","Tiene muchas animaciones"],a:2,e:"La pertinencia depende de su alineación con el aprendizaje buscado.",diff:"media",skill:"selección de recursos"},
{id:"p9",d:"Enseñanza-aprendizaje",i:"5.1 Estrategias de enseñanza",q:"Ante estudiantes que resuelven un problema por estrategias distintas, ¿qué intervención favorece mejor la flexibilidad matemática?",o:["Exigir un único método","Comparar y discutir las estrategias y sus ventajas","Corregir todas menos la más rápida","Evitar la puesta en común"],a:1,e:"Comparar estrategias permite analizar eficiencia, validez y conexiones matemáticas.",diff:"alta",skill:"decisión pedagógica"},
{id:"p10",d:"Enseñanza-aprendizaje",i:"5.2 Aprendizaje",q:"Antes de enseñar ecuaciones lineales, ¿qué conocimiento previo es especialmente relevante?",o:["Solo nombres de polígonos","Igualdad y operaciones inversas","Cálculo de probabilidades","Volumen de prismas"],a:1,e:"Comprender igualdad y operaciones inversas sustenta las transformaciones equivalentes de una ecuación.",diff:"media",skill:"conocimientos previos"},
{id:"p11",d:"Enseñanza-aprendizaje",i:"5.2 Aprendizaje",q:"Un estudiante aplica A=2(largo+ancho) para hallar el área de un rectángulo. ¿Qué confusión evidencia?",o:["Área y perímetro","Volumen y capacidad","Media y mediana","Fracción y decimal"],a:0,e:"La expresión corresponde al perímetro, no al área.",diff:"media",skill:"análisis de error"},
{id:"p12",d:"Enseñanza-aprendizaje",i:"5.3 Evaluación",q:"¿Qué instrumento es más pertinente para evaluar una explicación oral de una estrategia matemática?",o:["Una rúbrica con criterios de razonamiento y comunicación","Solo una prueba de selección múltiple","Una lista de asistencia","Una escala de velocidad"],a:0,e:"Una rúbrica permite observar criterios asociados a la calidad de la explicación y el razonamiento.",diff:"alta",skill:"evaluación"}

];

window.QBANK.forEach((q,idx)=>{
  if(!q.diff) q.diff=["básica","media","alta"][idx%3];
  if(!q.skill) q.skill=q.d==="Enseñanza-aprendizaje"?"análisis pedagógico":(idx%2?"interpretación":"resolución");
});

window.STUDY_GUIDES={
"1.1 Sistemas numéricos":{learn:"Trabaja las relaciones entre números: divisibilidad, factores, múltiplos, números primos y compuestos, además de orden y operaciones con enteros y racionales. La clave es comprender las propiedades y no depender solo de algoritmos.",example:"Ejemplo: para comparar -3/4 y -0,6, transforma o representa ambos valores. -3/4=-0,75; como -0,6 está más cerca de 0, entonces -0,6>-0,75.",error:"Un error frecuente es aplicar reglas de signos o divisibilidad de memoria sin interpretar el valor de los números.",pedagogy:"Conviene usar recta numérica, descomposición factorial, representaciones fraccionarias y contextos que hagan visible el significado de las operaciones."},
"1.2 Proporciones y porcentajes":{learn:"Distingue relaciones directamente proporcionales, inversamente proporcionales y no proporcionales. En porcentajes, interpreta el porcentaje como una razón con base 100 y relaciona distintos registros.",example:"Ejemplo: 25% de 80 puede pensarse como 1/4 de 80. Entonces 80÷4=20.",error:"Un error frecuente es asumir que toda relación creciente es directamente proporcional o aplicar regla de tres sin verificar la relación entre variables.",pedagogy:"Tablas, gráficos, dobles rectas numéricas y representaciones de 100 partes ayudan a conectar razón, fracción, decimal y porcentaje."},
"1.3 Potencias y raíces":{learn:"Analiza potencias como multiplicación iterada, reconoce el efecto del exponente y aplica propiedades de multiplicación y división de potencias cuando corresponda.",example:"Ejemplo: (0,5)^3=0,125. Aunque el exponente aumenta, una base entre 0 y 1 produce valores cada vez menores.",error:"Un error habitual es multiplicar base y exponente o extender propiedades de potencias a operaciones donde no corresponden.",pedagogy:"Comparar tablas de valores y representaciones sucesivas ayuda a comprender crecimiento y decrecimiento antes de formalizar propiedades."},
"2.1 Lenguaje algebraico":{learn:"El lenguaje algebraico permite representar regularidades, relaciones y expresiones generales. Es fundamental distinguir entre número desconocido, variable y expresión.",example:"Ejemplo: 'cinco menos el doble de un número' se representa 5-2x, no 2x-5.",error:"Un error común es traducir palabra por palabra sin respetar el orden de las operaciones.",pedagogy:"Usa tablas, patrones figurativos y frases equivalentes para transitar de situaciones concretas a expresiones simbólicas."},
"2.2 Ecuaciones e inecuaciones lineales":{learn:"Una ecuación expresa igualdad entre dos expresiones; una inecuación compara mediante desigualdad. Resolver implica encontrar los valores que hacen verdadera la relación.",example:"Ejemplo: 3x+5=26. Restar 5 en ambos miembros da 3x=21; dividir por 3 entrega x=7.",error:"Un error frecuente es 'pasar términos' cambiando signos sin comprender que se está aplicando la misma operación en ambos miembros.",pedagogy:"La balanza algebraica y la verificación sustituyendo el resultado ayudan a dar sentido a las transformaciones."},
"2.3 Funciones":{learn:"Una función relaciona valores de entrada y salida. Debes identificar dominio, recorrido, variables dependiente e independiente y reconocer parámetros de funciones lineales y afines.",example:"En y=3x+2, 3 es la pendiente y 2 es la intersección con el eje y.",error:"Es común confundir pendiente con intercepto o pensar que toda recta representa proporcionalidad directa.",pedagogy:"Conecta tablas, gráficos y expresiones simbólicas para que una misma relación pueda interpretarse desde varios registros."},
"3.1 Figuras y cuerpos geométricos":{learn:"Estudia propiedades de triángulos, polígonos, cuerpos y circunferencia. La clasificación debe basarse en propiedades y no solo en apariencia visual.",example:"Un cuadrado es también un rectángulo porque tiene cuatro ángulos rectos; además es un rombo porque sus cuatro lados son congruentes.",error:"Un error frecuente es considerar categorías geométricas como excluyentes cuando algunas son inclusivas.",pedagogy:"Clasificar ejemplos y contraejemplos, variar orientación y tamaño, y justificar atributos fortalece el razonamiento geométrico."},
"3.2 Perímetros, áreas y volúmenes":{learn:"Diferencia magnitudes: perímetro mide longitud del contorno, área mide superficie y volumen mide espacio ocupado. Selecciona fórmulas según las propiedades de la figura o cuerpo.",example:"Un rectángulo de 8 cm por 5 cm tiene perímetro 26 cm y área 40 cm²: son magnitudes distintas.",error:"Un error habitual es confundir unidades lineales, cuadradas y cúbicas o usar una fórmula sin identificar qué magnitud se pide.",pedagogy:"Descomponer figuras, cubrir superficies y construir cuerpos permite comprender las fórmulas antes de memorizarlas."},
"3.3 Transformaciones isométricas":{learn:"Las isometrías conservan distancias y ángulos. Traslación, reflexión y rotación cambian posición u orientación sin cambiar forma ni tamaño.",example:"Una rotación de 90° alrededor del origen transforma (2,1) en (-1,2) en sentido antihorario.",error:"Confundir una homotecia con una isometría es frecuente: la homotecia puede cambiar el tamaño.",pedagogy:"Trabajar sobre cuadrículas y plano cartesiano permite observar qué propiedades permanecen invariantes."},
"4.1 Estadística":{learn:"Interpreta gráficos y medidas de tendencia central considerando el contexto. Media, mediana y moda no siempre describen igual de bien un conjunto de datos.",example:"En 2,3,3,4,20 la media es 6,4 pero la mediana es 3; el valor extremo altera fuertemente la media.",error:"Un error frecuente es elegir automáticamente la media sin analizar valores extremos o el propósito de la comparación.",pedagogy:"Pide justificar qué medida representa mejor los datos y comparar distintas representaciones del mismo conjunto."},
"4.2 Probabilidad":{learn:"La probabilidad relaciona casos favorables y posibles cuando los resultados son equiprobables. El espacio muestral debe construirse de manera sistemática.",example:"Al lanzar una moneda y un dado hay 2×6=12 resultados posibles por el principio multiplicativo.",error:"Un error común es contar resultados sin considerar todas las combinaciones o asumir equiprobabilidad cuando no corresponde.",pedagogy:"Diagramas de árbol, tablas de doble entrada y experimentación permiten conectar frecuencia relativa con probabilidad teórica."},
"5.1 Estrategias de enseñanza":{learn:"La estrategia debe ser coherente con el objetivo de aprendizaje, el contenido y la evidencia que se espera observar. No existe una única estrategia adecuada para todos los propósitos.",example:"Si el objetivo es comprender equivalencia de fracciones, comparar representaciones visuales puede ser más pertinente que comenzar con un algoritmo.",error:"Un error docente frecuente es elegir recursos atractivos pero sin relación clara con el aprendizaje que se busca promover.",pedagogy:"Antes de elegir una actividad, pregunta: ¿qué pensamiento matemático quiero hacer visible y qué acción del estudiante permitirá observarlo?"},
"5.2 Aprendizaje":{learn:"Analizar el aprendizaje implica reconocer conocimientos previos y errores como evidencia del razonamiento del estudiante, no solo como respuestas incorrectas.",example:"Si un estudiante cree que 0,35>0,8 porque 35>8, el error revela una dificultad con valor posicional.",error:"Corregir dando solo la respuesta correcta puede ocultar la causa del error y no modificar el razonamiento subyacente.",pedagogy:"Usa preguntas, representaciones y contraejemplos que permitan al estudiante confrontar y revisar su propia estrategia."},
"5.3 Evaluación":{learn:"Una evaluación pertinente alinea objetivo, indicador, tarea y evidencia. El instrumento debe permitir observar realmente el desempeño que se quiere evaluar.",example:"Si el objetivo exige argumentar, una tarea de selección múltiple sin justificación entrega evidencia limitada sobre esa habilidad.",error:"Un error frecuente es evaluar contenidos relacionados pero no el desempeño específico expresado en el objetivo.",pedagogy:"Define primero qué evidencia mostraría logro y luego diseña la actividad o instrumento que permita producir esa evidencia."}
};