window.ECEP_DATA=[
["Números",[["1.1 Sistemas numéricos",["Múltiplos, factores, divisibilidad y números primos","Orden y comparación de enteros y racionales","Problemas con operaciones y números racionales"]],["1.2 Proporciones y porcentajes",["Representaciones de proporcionalidad directa e inversa","Reconocimiento de relaciones proporcionales y no proporcionales","Problemas de proporcionalidad directa o inversa","Cálculo e interpretación de porcentajes"]],["1.3 Potencias y raíces",["Problemas con potencias de base real y exponente entero","Operaciones con potencias de base fraccionaria o decimal"]]]],
["Álgebra",[["2.1 Lenguaje algebraico",["Reglas de formación en secuencias numéricas","Traducción entre lenguaje natural, numérico y algebraico","Modelación algebraica de proporciones, porcentajes y potencias"]],["2.2 Ecuaciones e inecuaciones lineales",["Modelación con ecuaciones e inecuaciones lineales","Problemas mediante ecuaciones e inecuaciones","Resolución con coeficientes enteros o fraccionarios"]],["2.3 Funciones",["Dominio y recorrido","Variables dependientes e independientes","Parámetros de funciones lineal y afín","Modelación con funciones lineales o afines"]]]],
["Geometría",[["3.1 Figuras y cuerpos geométricos",["Construcción de triángulos","Clasificación de polígonos y cuerpos","Ejes y centros de simetría","Propiedades de polígonos","Propiedades de la circunferencia"]],["3.2 Perímetros, áreas y volúmenes",["Perímetros y áreas de figuras planas","Perímetros, áreas y volúmenes","Familias de figuras según simetría","Áreas de figuras compuestas"]],["3.3 Transformaciones isométricas",["Congruencia y transformaciones","Traslaciones, reflexiones y rotaciones","Transformaciones en naturaleza y arte"]]]],
["Datos y azar",[["4.1 Estadística",["Interpretación y comparación de gráficos","Medidas de tendencia central","Selección de indicador estadístico pertinente","Población y muestra"]],["4.2 Probabilidad",["Espacio muestral y eventos","Frecuencia relativa","Principio multiplicativo","Modelo de Laplace"]]]],
["Enseñanza-aprendizaje",[["5.1 Estrategias de enseñanza",["Estrategias y actividades","Representaciones de contenidos","Decisiones e intervenciones docentes","Selección de recursos","Actividades según énfasis curriculares","Estrategias ante dificultades"]],["5.2 Aprendizaje",["Conocimientos previos","Errores comunes y aprendizaje desde el error"]],["5.3 Evaluación",["Indicadores y desempeños","Actividades, estrategias e instrumentos de evaluación"]]]]
];

window.QBANK=[
{id:"n1",d:"Números",i:"1.1 Sistemas numéricos",q:"¿Cuál de los siguientes números es primo?",o:["21","29","39","51"],a:1,e:"29 solo tiene como divisores positivos a 1 y 29."},
{id:"n2",d:"Números",i:"1.2 Proporciones y porcentajes",q:"Una chaqueta cuesta $40.000 y tiene 25% de descuento. ¿Cuál es el precio final?",o:["$10.000","$30.000","$35.000","$37.500"],a:1,e:"El 25% de $40.000 es $10.000. Al restarlo al precio original quedan $30.000."},
{id:"n3",d:"Números",i:"1.2 Proporciones y porcentajes",q:"Si 4 cuadernos cuestan $6.000 y el precio es directamente proporcional, ¿cuánto cuestan 10 cuadernos?",o:["$12.000","$15.000","$18.000","$24.000"],a:1,e:"Cada cuaderno cuesta $1.500; 10 cuestan $15.000."},
{id:"a1",d:"Álgebra",i:"2.1 Lenguaje algebraico",q:"¿Qué expresión representa 'el doble de un número disminuido en 7'?",o:["2x-7","2(x-7)","x-14","7-2x"],a:0,e:"El doble de un número es 2x y luego se disminuye en 7."},
{id:"a2",d:"Álgebra",i:"2.2 Ecuaciones e inecuaciones lineales",q:"¿Qué ecuación representa: 'el triple de un número, aumentado en 5, es 26'?",o:["3x+5=26","3(x+5)=26","x+15=26","5x+3=26"],a:0,e:"'El triple de un número' es 3x y luego se aumenta en 5."},
{id:"a3",d:"Álgebra",i:"2.3 Funciones",q:"En la función y=4x+2, ¿qué representa el número 4?",o:["El intercepto con el eje y","La pendiente","El dominio","El recorrido"],a:1,e:"En una función afín y=mx+n, m corresponde a la pendiente."},
{id:"g1",d:"Geometría",i:"3.1 Figuras y cuerpos geométricos",q:"¿Cuál conjunto de longitudes puede formar un triángulo?",o:["2, 3 y 6","4, 5 y 8","1, 2 y 4","3, 3 y 7"],a:1,e:"La suma de dos lados debe ser mayor que el tercero. Para 4, 5 y 8 se cumplen las desigualdades necesarias."},
{id:"g2",d:"Geometría",i:"3.2 Perímetros, áreas y volúmenes",q:"Un rectángulo mide 8 cm de largo y 5 cm de ancho. ¿Cuál es su área?",o:["13 cm²","26 cm²","40 cm²","80 cm²"],a:2,e:"El área de un rectángulo se obtiene multiplicando largo por ancho: 8×5=40 cm²."},
{id:"g3",d:"Geometría",i:"3.3 Transformaciones isométricas",q:"¿Qué transformación conserva forma y tamaño y gira una figura alrededor de un punto?",o:["Traslación","Rotación","Homotecia","Proyección"],a:1,e:"La rotación gira una figura alrededor de un centro conservando distancias y ángulos."},
{id:"d1",d:"Datos y azar",i:"4.1 Estadística",q:"Para los datos 4, 4, 6, 8, 8, ¿cuál es la mediana?",o:["4","6","8","30"],a:1,e:"Ordenados los datos, el valor central es 6."},
{id:"d2",d:"Datos y azar",i:"4.2 Probabilidad",q:"En una bolsa hay 3 fichas rojas y 2 azules. Si todas tienen igual probabilidad de salir, ¿cuál es la probabilidad de obtener una azul?",o:["2/3","2/5","3/5","1/2"],a:1,e:"Hay 5 resultados elementales posibles y 2 favorables: 2/5."},
{id:"d3",d:"Datos y azar",i:"4.2 Probabilidad",q:"Se lanzan una moneda y un dado de 6 caras. ¿Cuántos resultados posibles tiene el experimento?",o:["6","8","12","18"],a:2,e:"Por el principio multiplicativo: 2 resultados de la moneda × 6 del dado = 12."},
{id:"p1",d:"Enseñanza-aprendizaje",i:"5.1 Estrategias de enseñanza",q:"Para introducir el concepto de fracción equivalente, ¿qué recurso favorece mejor una comprensión inicial?",o:["Solo entregar la regla de amplificación","Usar representaciones visuales de una misma cantidad dividida de distintas maneras","Pedir memorizar una lista de fracciones","Comenzar con una prueba sumativa"],a:1,e:"Las representaciones múltiples permiten observar que distintas fracciones pueden representar la misma cantidad."},
{id:"p2",d:"Enseñanza-aprendizaje",i:"5.2 Aprendizaje",q:"Un estudiante afirma que 0,8 es menor que 0,35 porque '8 es menor que 35'. ¿Qué intervención aborda mejor el error conceptual?",o:["Pedirle memorizar la regla de comparación","Comparar ambos números con una representación que haga visible el valor posicional","Indicarle inmediatamente la respuesta correcta","Cambiar el ejercicio por números naturales"],a:1,e:"La dificultad está en el valor posicional. Una representación permite confrontar el razonamiento y reconstruir el concepto."},
{id:"p3",d:"Enseñanza-aprendizaje",i:"5.3 Evaluación",q:"Si el objetivo es evaluar si un estudiante puede justificar un procedimiento matemático, ¿qué evidencia es más pertinente?",o:["Una pregunta de verdadero o falso sin explicación","Una tarea donde deba resolver y explicar por qué su estrategia funciona","Una lista de fórmulas memorizadas","Registrar solo el tiempo que demora"],a:1,e:"La evidencia debe alinearse con el desempeño esperado: justificar requiere hacer visible el razonamiento."}
];

window.STUDY_GUIDES={
"1.1 Sistemas numéricos":{learn:"Trabaja las relaciones entre números: divisibilidad, factores, múltiplos, números primos y compuestos, además de orden y operaciones con enteros y racionales. La clave es comprender las propiedades y no depender solo de algoritmos.",example:"Ejemplo: para comparar -3/4 y -0,6, transforma o representa ambos valores. -3/4=-0,75; como -0,6 está más cerca de 0, entonces -0,6>-0,75.",error:"Un error frecuente es aplicar reglas de signos o divisibilidad de memoria sin interpretar el valor de los números.",pedagogy:"Conviene usar recta numérica, descomposición factorial, representaciones fraccionarias y contextos que hagan visible el significado de las operaciones."},
"1.2 Proporciones y porcentajes":{learn:"Distingue relaciones directamente proporcionales, inversamente proporcionales y no proporcionales. En porcentajes, interpreta el porcentaje como una razón con base 100 y relaciona distintos registros.",example:"Ejemplo: 25% de 80 puede pensarse como 1/4 de 80. Entonces 80÷4=20.",error:"Un error frecuente es asumir que toda relación creciente es directamente proporcional o aplicar regla de tres sin verificar la relación entre variables.",pedagogy:"Tablas, gráficos, dobles rectas numéricas y representaciones de 100 partes ayudan a conectar razón, fracción, decimal y porcentaje."},
"1.3 Potencias y raíces":{learn:"Analiza potencias como multiplicación iterada, reconoce el efecto del exponente y aplica propiedades de multiplicación y división de potencias cuando corresponda.",example:"Ejemplo: (0,5)^3=0,125. Aunque el exponente aumenta, una base entre 0 y 1 produce valores cada vez menores.",error:"Un error habitual es multiplicar base y exponente o extender propiedades de potencias a operaciones donde no corresponden.",pedagogy:"Comparar tablas de valores y representaciones sucesivas ayuda a comprender crecimiento y decrecimiento antes de formalizar propiedades."},
"2.1 Lenguaje algebraico":{learn:"El lenguaje algebraico permite representar regularidades, relaciones y expresiones generales. Es fundamental distinguir entre número desconocido, variable y expresión.",example:"Ejemplo: 'cinco menos el doble de un número' se representa 5-2x, no 2x-5.",error:"Un error común es traducir palabra por palabra sin respetar el orden de las operaciones.",pedagogy:"Usa tablas, patrones figurativos y frases equivalentes para transitar de situaciones concretas a expresiones simbólicas."},
"2.2 Ecuaciones e inecuaciones lineales":{learn:"Una ecuación expresa igualdad entre dos expresiones; una inecuación compara mediante desigualdad. Resolver implica encontrar los valores que hacen verdadera la relación.",example:"Ejemplo: 3x+5=26. Restar 5 en ambos miembros da 3x=21; dividir por 3 entrega x=7.",error:"Un error frecuente es 'pasar términos' cambiando signos sin comprender que se está aplicando la misma operación en ambos miembros.",pedagogy:"La balanza algebraica y la verificación sustituyendo el resultado ayudan a dar sentido a las transformaciones."},
"2.3 Funciones":{learn:"Una función relaciona valores de entrada y salida. Debes identificar dominio, recorrido, variables dependiente e independiente y reconocer parámetros de funciones lineales y afines.",example:"En y=3x+2, 3 es la pendiente y 2 es la intersección con el eje y.",error:"Es común confundir pendiente con intercepto o pensar que toda recta representa proporcionalidad directa.",pedagogy:"Conecta tablas, gráficos y expresiones simbólicas para que una misma relación pueda interpretarse desde varios registros."},
"3.1 Figuras y cuerpos geométricos":{learn:"Estudia propiedades de triángulos, polígonos, cuerpos y circunferencia. La clasificación debe basarse en propiedades y no solo en apariencia visual.",example:"Un cuadrado es también un rectángulo porque tiene cuatro ángulos rectos; además es un rombo porque sus cuatro lados son congruentes.",error:"Un error frecuente es considerar categorías geométricas como excluyentes cuando algunas son inclusivas.",pedagogy:"Clasificar ejemplos y contraejemplos, variar orientación y tamaño, y justificar atributos fortalece el razonamiento geométrico."},
"3.2 Perímetros, áreas y volúmenes":{learn:"Diferencia magnitudes: perímetro mide longitud del contorno, área mide superficie y volumen mide espacio ocupado. Selecciona fórmulas según las propiedades de la figura o cuerpo.",example:"Un rectángulo de 8 cm por 5 cm tiene perímetro 26 cm y área 40 cm²: son magnitudes distintas.",error:"Un error habitual es confundir unidades lineales, cuadradas y cúbicas o usar una fórmula sin identificar qué magnitud se pide.",pedagogy:"Descomponer figuras, cubrir superficies y construir cuerpos permite comprender las fórmulas antes de memorizarlas."},
"3.3 Transformaciones isométricas":{learn:"Las isometrías conservan distancias y ángulos. Traslación, reflexión y rotación cambian posición u orientación sin cambiar forma ni tamaño.",example:"Una rotación de 90° alrededor del origen transforma (2,1) en (-1,2) en sentido antihorario.",error:"Confundir una homotecia con una isometría es frecuente: la homotecia puede cambiar el tamaño.",pedagogy:"Trabajar sobre cuadrículas y plano cartesiano permite observar qué propiedades permanecen invariantes."},
"4.1 Estadística":{learn:"Interpreta gráficos y medidas de tendencia central considerando el contexto. Media, mediana y moda no siempre describen igual de bien un conjunto de datos.",example:"En 2,3,3,4,20 la media es 6,4 pero la mediana es 3; el valor extremo altera fuertemente la media.",error:"Un error frecuente es elegir automáticamente la media sin analizar valores extremos o el propósito de la comparación.",pedagogy:"Pide justificar qué medida representa mejor los datos y comparar distintas representaciones del mismo conjunto."},
"4.2 Probabilidad":{learn:"La probabilidad relaciona casos favorables y posibles cuando los resultados son equiprobables. El espacio muestral debe construirse de manera sistemática.",example:"Al lanzar una moneda y un dado hay 2×6=12 resultados posibles por el principio multiplicativo.",error:"Un error común es contar resultados sin considerar todas las combinaciones o asumir equiprobabilidad cuando no corresponde.",pedagogy:"Diagramas de árbol, tablas de doble entrada y experimentación permiten conectar frecuencia relativa con probabilidad teórica."},
"5.1 Estrategias de enseñanza":{learn:"La estrategia debe ser coherente con el objetivo de aprendizaje, el contenido y la evidencia que se espera observar. No existe una única estrategia adecuada para todos los propósitos.",example:"Si el objetivo es comprender equivalencia de fracciones, comparar representaciones visuales puede ser más pertinente que comenzar con un algoritmo.",error:"Un error docente frecuente es elegir recursos atractivos pero sin relación clara con el aprendizaje que se busca promover.",pedagogy:"Antes de elegir una actividad, pregunta: ¿qué pensamiento matemático quiero hacer visible y qué acción del estudiante permitirá observarlo?"},
"5.2 Aprendizaje":{learn:"Analizar el aprendizaje implica reconocer conocimientos previos y errores como evidencia del razonamiento del estudiante, no solo como respuestas incorrectas.",example:"Si un estudiante cree que 0,35>0,8 porque 35>8, el error revela una dificultad con valor posicional.",error:"Corregir dando solo la respuesta correcta puede ocultar la causa del error y no modificar el razonamiento subyacente.",pedagogy:"Usa preguntas, representaciones y contraejemplos que permitan al estudiante confrontar y revisar su propia estrategia."},
"5.3 Evaluación":{learn:"Una evaluación pertinente alinea objetivo, indicador, tarea y evidencia. El instrumento debe permitir observar realmente el desempeño que se quiere evaluar.",example:"Si el objetivo exige argumentar, una tarea de selección múltiple sin justificación entrega evidencia limitada sobre esa habilidad.",error:"Un error frecuente es evaluar contenidos relacionados pero no el desempeño específico expresado en el objetivo.",pedagogy:"Define primero qué evidencia mostraría logro y luego diseña la actividad o instrumento que permita producir esa evidencia."}
};