window.ECEP_DATA=[
["Números",[["1.1 Sistemas numéricos",["Múltiplos, factores, divisibilidad y números primos","Orden y comparación de enteros y racionales","Problemas con operaciones y números racionales"]],["1.2 Proporciones y porcentajes",["Representaciones de proporcionalidad directa e inversa","Reconocimiento de relaciones proporcionales y no proporcionales","Problemas de proporcionalidad directa o inversa","Cálculo e interpretación de porcentajes"]],["1.3 Potencias y raíces",["Problemas con potencias de base real y exponente entero","Operaciones con potencias de base fraccionaria o decimal"]]]],
["Álgebra",[["2.1 Lenguaje algebraico",["Reglas de formación en secuencias numéricas","Traducción entre lenguaje natural, numérico y algebraico","Modelación algebraica de proporciones, porcentajes y potencias"]],["2.2 Ecuaciones e inecuaciones lineales",["Modelación con ecuaciones e inecuaciones lineales","Problemas mediante ecuaciones e inecuaciones","Resolución con coeficientes enteros o fraccionarios"]],["2.3 Funciones",["Dominio y recorrido","Variables dependientes e independientes","Parámetros de funciones lineal y afín","Modelación con funciones lineales o afines"]]]],
["Geometría",[["3.1 Figuras y cuerpos geométricos",["Construcción de triángulos","Clasificación de polígonos y cuerpos","Ejes y centros de simetría","Propiedades de polígonos","Propiedades de la circunferencia"]],["3.2 Perímetros, áreas y volúmenes",["Perímetros y áreas de figuras planas","Perímetros, áreas y volúmenes","Familias de figuras según simetría","Áreas de figuras compuestas"]],["3.3 Transformaciones isométricas",["Congruencia y transformaciones","Traslaciones, reflexiones y rotaciones","Transformaciones en naturaleza y arte"]]]],
["Datos y azar",[["4.1 Estadística",["Interpretación y comparación de gráficos","Medidas de tendencia central","Selección de indicador estadístico pertinente","Población y muestra"]],["4.2 Probabilidad",["Espacio muestral y eventos","Frecuencia relativa","Principio multiplicativo","Modelo de Laplace"]]]],
["Enseñanza-aprendizaje",[["5.1 Estrategias de enseñanza",["Estrategias y actividades","Representaciones de contenidos","Decisiones e intervenciones docentes","Selección de recursos","Actividades según énfasis curriculares","Estrategias ante dificultades"]],["5.2 Aprendizaje",["Conocimientos previos","Errores comunes y aprendizaje desde el error"]],["5.3 Evaluación",["Indicadores y desempeños","Actividades, estrategias e instrumentos de evaluación"]]]]
];

window.QBANK=[
{d:"Números",i:"1.2 Proporciones y porcentajes",q:"Una chaqueta cuesta $40.000 y tiene 25% de descuento. ¿Cuál es el precio final?",o:["$10.000","$30.000","$35.000","$37.500"],a:1,e:"El 25% de $40.000 es $10.000; se resta al precio original."},
{d:"Álgebra",i:"2.2 Ecuaciones e inecuaciones lineales",q:"¿Qué ecuación representa: el triple de un número, aumentado en 5, es 26?",o:["3x+5=26","3(x+5)=26","x+15=26","5x+3=26"],a:0,e:"El triple es 3x y luego se aumenta en 5."},
{d:"Geometría",i:"3.1 Figuras y cuerpos geométricos",q:"¿Qué conjunto puede formar un triángulo?",o:["2,3,6","4,5,8","1,2,4","3,3,7"],a:1,e:"La suma de dos lados debe ser mayor que el tercero."},
{d:"Datos y azar",i:"4.2 Probabilidad",q:"Hay 3 fichas rojas y 2 azules. ¿Probabilidad de azul?",o:["2/3","2/5","3/5","1/2"],a:1,e:"Hay 2 casos favorables de 5 posibles."},
{d:"Enseñanza-aprendizaje",i:"5.2 Aprendizaje",q:"Un estudiante dice que 0,8 < 0,35 porque 8 < 35. ¿Qué intervención es más pertinente?",o:["Memorizar una regla","Comparar ambos números con una representación de valor posicional","Dar la respuesta correcta","Cambiar a números naturales"],a:1,e:"Una representación permite confrontar el error conceptual y trabajar valor posicional."}
];