// ProfeECEP 2.8.5 — tutor socrático y estudio por errores
(function(){
 'use strict';
 const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
 function errorPool(){const wrong=(S.wrong||[]).map(id=>Q.find(q=>q.id===id)).filter(Boolean);if(wrong.length)return wrong;const by={};(S.history||[]).forEach(h=>{if(!by[h.domain])by[h.domain]={n:0,w:0};by[h.domain].n++;if(!h.ok)by[h.domain].w++});const weak=Object.entries(by).sort((a,b)=>(b[1].w/Math.max(1,b[1].n))-(a[1].w/Math.max(1,a[1].n)))[0]?.[0];return Q.filter(q=>!weak||q.d===weak)}
 function question(id){if(id&&typeof id==='object')return id;const runtime=window.PE22_RUNTIME&&PE22_RUNTIME(),current=runtime?.quiz?.[runtime.pos];return Q.find(q=>q.id===id)||current||errorPool()[0]||Q[0]}
 function message(step,q){
  if(!q)return 'No hay una pregunta disponible todavía.';
  if(step==='identify')return '<b>Qué tienes que resolver</b><p>'+esc(q.q)+'</p><p>Contenido: '+esc(q.skill||q.i)+'.</p>';
  if(step==='clue')return '<b>Entiende la relación</b><p>'+esc(PE304.reason(q,q.a))+'</p>';
  if(step==='eliminate')return PE304.alternatives(q,PE304.selected(q));
  return PE304.feedback(q,PE304.selected(q));
 }
 function log(step,q){S.tutor285=S.tutor285||{sessions:0,steps:0};S.tutor285.sessions++;S.tutor285.steps++;S.tutor285.last={date:new Date().toISOString(),step,questionId:q?.id||null};saveState()}
 function open(id){const q=question(id);window.PE285_CURRENT=q;document.querySelector('.tutor285Overlay')?.remove();const o=document.createElement('div');o.className='tutor285Overlay';o.innerHTML='<div class="tutor285Modal"><button class="close" onclick="PE285.close()">×</button><span class="pill">Tutor guiado</span><h2>Resolvamos paso a paso</h2><div class="tutor285Question"><small>'+esc(q?.d||'')+' · '+esc(q?.i||'')+'</small><b>'+esc(q?.q||'')+'</b></div><div class="tutor285Actions"><button onclick="PE285.ask(\'identify\')">1. ¿Qué pide?</button><button onclick="PE285.ask(\'clue\')">2. Entender el razonamiento</button><button onclick="PE285.ask(\'eliminate\')">3. Explicar alternativas</button><button onclick="PE285.ask(\'solution\')">Ver solución</button></div><div id="tutor285Answer" class="tutor285Answer" tabindex="-1" aria-live="polite"><p class="muted">Intenta razonar antes de mirar la solución.</p></div></div>';document.body.appendChild(o)}
 function ask(step){const q=window.PE285_CURRENT;if(!q)return;log(step,q);const box=document.getElementById('tutor285Answer');if(box){box.innerHTML=message(step,q);box.focus?.({preventScroll:true});box.scrollIntoView?.({block:'nearest'})}}
 function close(){document.querySelector('.tutor285Overlay')?.remove();window.PE285_CURRENT=null}
 function startErrors(){const pool=errorPool();if(!pool.length){alert('Todavía no hay preguntas disponibles para este entrenamiento.');return}mode='practice';quiz=shuffle(pool).slice(0,Math.min(5,pool.length));pos=0;answers=[];showQ()}
 function addTools(){if(mode==='simulation')return;const runtime=window.PE22_RUNTIME&&PE22_RUNTIME(),q=runtime?.quiz?.[runtime.pos];if(!q)return;const target=mode==='diagnosis'?el('diagnosis'):mode==='simulation'?el('simulation'):el('practice');if(!target)return;const box=target.querySelector('.sim12Question')||target.querySelector('.card');if(!box||box.querySelector('.tutor285QuestionBtn'))return;const b=document.createElement('button');b.className='mini tutor285QuestionBtn';b.textContent='💡 Resolver con tutor guiado';b.onclick=()=>open(q);box.appendChild(b)}
 function addFeedback(){const target=el('practice'),feedback=target?.querySelector('.card.good,.card.bad');if(!feedback||!feedback.querySelector('.answerKey')||feedback.querySelector('.tutor285Feedback'))return;const b=document.createElement('button');b.className='btn ghost full tutor285Feedback';b.textContent='Resolver de nuevo con tutor guiado';b.onclick=()=>open(answers[answers.length-1]?.id);feedback.after(b)}
 function inject(){const home=el('home'),practice=el('practice'),progress=el('progress'),errors=(S.wrong||[]).length;if(home&&!home.querySelector('.tutor285home')){const c=document.createElement('div');c.className='card tutor285home';c.innerHTML='<span class="pill">Tutor guiado</span><h3>Aprende a razonar, no solo a acertar</h3><p class="muted">El tutor te guía con preguntas antes de mostrar la solución y usa tus errores para elegir la práctica.</p><button class="btn full" onclick="PE285.startErrors()">'+(errors?'Practicar mis '+errors+' error(es)':'Comenzar práctica guiada')+'</button>';const a=home.querySelector('.tutor26home');if(a)a.after(c);else home.prepend(c)}if(practice&&!practice.querySelector('.tutor285practice')){const c=document.createElement('div');c.className='card tutor285practice';c.innerHTML='<span class="pill">Errores guiados</span><h3>Entrenamiento con tutor</h3><p class="muted">Primero analiza qué pide la pregunta, luego identifica pistas y compara alternativas.</p><button class="btn full" onclick="PE285.startErrors()">Iniciar entrenamiento</button>';const a=practice.querySelector('.error18practice')||practice.firstElementChild;if(a)a.after(c);else practice.prepend(c)}if(progress&&!progress.querySelector('.tutor285')){const c=document.createElement('div');c.className='card tutor285';c.innerHTML='<span class="pill">Acompañamiento 2.8.5</span><h3>Sesiones con tutor</h3><p class="muted">Has usado el tutor '+(S.tutor285?.sessions||0)+' vez/veces. La próxima sesión se enfoca en tus errores pendientes.</p><button class="btn ghost full" onclick="PE285.startErrors()">Practicar errores</button>';const a=progress.querySelector('.editorial284');if(a)a.after(c);else progress.prepend(c)}}
 window.PE285={open,ask,close,startErrors,errorPool,inject};
 const oldRender=window.render;if(oldRender&&!window.__pe285Render){window.render=function(){const r=oldRender();setTimeout(inject,0);return r};window.__pe285Render=true}
 const oldShow=window.showQ;if(oldShow&&!window.__pe285Show){window.showQ=function(){const r=oldShow();setTimeout(addTools,0);return r};window.__pe285Show=true}
 const oldCheck=window.checkAnswer;if(oldCheck&&!window.__pe285Check){window.checkAnswer=function(){const r=oldCheck();setTimeout(addFeedback,0);return r};window.__pe285Check=true}
 setTimeout(inject,0);
}());
