const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),child=require('node:child_process');
const {runtime,root,specialties}=require('./helpers/runtime.cjs');
const baseline=require('./fixtures/bank-310-preservation.json'),audit=require('../docs/revision-fuentes-311.json'),tracks=require('../content-311/audio-manifest.json');
const hash=x=>crypto.createHash('sha256').update(JSON.stringify(x)).digest('hex'),plain=x=>JSON.parse(JSON.stringify(x));
const keys=['A','D','C','B','C','C','B','C','A','A','C','B','D','A','D','A','A'];
const expected=[/Watching nature footage/,/feeling of satisfaction/,/inspire a generation/,/Obstructed/,/explanatory documentary/,/explain how data and technology/,/first discusses recovering/,/Food connects everyone/,/general public/,/separate personal responses/,/figured out/,/confident, promotional/,/as little as 7.5 seconds/,/promote a provider/,/grandfather/,/ironic comment/,/strong emotional response/];

test('17 claves conceptuales independientes, 68 razones y 11 indicadores de escucha de 2026',()=>{
 const a=runtime('basica-ingles'),rows=a.context.PE305.pool('audio');assert.equal(rows.length,17);assert.equal(a.run('Q.length'),147);
 assert.equal(Object.values(specialties).reduce((n,x)=>n+x,0),894);assert.equal(new Set(rows.map(q=>q.indicatorId)).size,11);
 rows.forEach((q,i)=>{assert.equal(q.source.number,i+1);assert.equal(q.source.key,keys[i]);assert.equal(q.source.practiceKey,'ABCD'[q.a]);assert.match(q.o[q.a],expected[i]);assert.equal(q.e,q.explanations[q.a]);assert.equal(new Set(q.explanations).size,4);assert.ok(q.explanations.every(e=>e.length>65));assert.equal(a.context.PE304.complete(q),true);const [d,s,k]=q.indicatorId.split('-').map(Number);assert.equal(q.indicator,a.run('D')[d][1][s][1][k]);assert.equal(q.source.page,q.stimulus[0].track+1);assert.ok(audit.items[i].alignment.length>65);assert.match(q.sourceNote,/No es una pregunta oficial de 2026/);});
 assert.equal(a.context.PE30.status().ready,true);
});
test('las 877 preguntas anteriores y todas las versiones históricas permanecen idénticas',()=>{
 for(const sid of Object.keys(specialties)){const a=runtime(sid),old=a.run('Q').filter(q=>q.version!=='3.0.11');assert.equal(old.length,baseline[sid].count);assert.equal(hash(old),baseline[sid].active);assert.equal(hash(a.context.PE307.fullBank().filter(q=>q.version!=='3.0.11')),baseline[sid].historical);}
});
test('filtros separados: 17 audios, 11 lecturas y 47 referencias de Inglés; aislamiento de especialidades',()=>{
 const a=runtime('basica-ingles'),api=a.context.PE305;assert.equal(api.pool().length,47);assert.equal(api.pool('reading').length,11);assert.ok(api.pool('reading').every(q=>q.stimulus.every(s=>s.kind!=='audio')));assert.match(api.practiceCard(),/Explorar las 47 preguntas/);assert.match(api.practiceCard(),/Comprensión auditiva · 7 pistas \(17\)/);assert.equal(api.start('audio'),true);assert.equal(a.run('quiz.length'),5);assert.ok(a.run('quiz').every(q=>q.version==='3.0.11'));for(const q of api.pool('audio')){assert.equal(api.practiceQuestion(q.id),true);assert.equal(a.run('quiz[0].id'),q.id);}
 for(const sid of Object.keys(specialties).filter(x=>x!=='basica-ingles'))assert.equal(runtime(sid).context.PE305.pool('audio').length,0);
});
test('antes de responder, práctica, diagnóstico y simulacro muestran audio sin pistas de solución',()=>{
 const a=runtime('basica-ingles');for(const q of a.context.PE305.pool('audio')){a.context.target=q;const material=a.context.PE305.stimulus(q);assert.match(material,/<audio controls preload="metadata" aria-label=/);assert.doesNotMatch(material,/autoplay|voz sintética/);for(const mode of ['practice','diagnosis','simulation']){if(mode==='simulation')a.run("mode='simulation';quiz=[target];SIM12={index:0,answers:{},marked:{},seconds:900,maxSeconds:900};renderSimulation12()");else a.run(`quiz=[target];mode='${mode}';pos=0;answers=[];showQ()`);const html=a.elements.get(mode).innerHTML;assert.ok(html.includes(material));assert.doesNotMatch(html,/pe307-transcript|Vuelve al pasaje/);for(const e of [...q.explanations,q.source.adaptation])assert.ok(!html.includes(a.context.PE304.esc(e)));}}
});
test('acierto, error y omisión ofrecen las cuatro razones, transcripción identificada y pasaje temporal',()=>{
 const a=runtime('basica-ingles');for(const q of a.context.PE305.pool('audio'))for(const selected of [q.a,(q.a+1)%4,undefined]){const html=a.context.PE304.feedback(q,selected);q.explanations.forEach(e=>assert.ok(html.includes(a.context.PE304.esc(e))));assert.match(html,/Leer la transcripción del audio/);assert.match(html,/reconocimiento automático/);assert.match(html,/Vuelve al pasaje \d+:\d\d–\d+:\d\d/);assert.ok(html.includes(a.context.PE304.esc(q.stimulus[0].transcript).replace(/\n/g,'<br>')));assert.match(html,/Reportar un problema/);}
});
test('siete grabaciones completas: huellas, duración, decodificación y precaché',()=>{
 const a=runtime('basica-ingles'),sw=fs.readFileSync(path.join(root,'sw.js'),'utf8');assert.equal(tracks.length,7);assert.ok(tracks.reduce((n,t)=>n+t.bytes,0)<8000000);
 for(const t of tracks){const url=a.context.PE305.audioURL(t.file),filename=path.join(root,url.split('?')[0]),bytes=fs.readFileSync(filename);assert.ok(sw.includes('./'+url));assert.equal(bytes.length,t.bytes);assert.equal(crypto.createHash('sha256').update(bytes).digest('hex'),t.sha256);const probe=JSON.parse(child.execFileSync('ffprobe',['-v','error','-show_format','-show_streams','-of','json',filename]));assert.equal(probe.streams[0].codec_name,'mp3');assert.ok(Math.abs(Number(probe.format.duration)-t.sourceDuration)<.1);child.execFileSync('ffmpeg',['-v','error','-xerror','-i',filename,'-f','null','-']);}
});
test('matices editoriales y recursos permitidos evitan generalizaciones y rutas arbitrarias',()=>{
 const a=runtime('basica-ingles'),rows=a.context.PE305.pool('audio'),q=n=>rows[n-1];assert.match(q(7).q,/excluding the narrator/);assert.match(q(8).e,/responsabilidades no sean idénticas/);assert.match(q(10).source.adaptation,/sin inferir el protocolo completo/);assert.match(q(13).e,/no un tiempo garantizado/);assert.match(q(16).e,/ironía/);assert.match(q(17).e,/conmovedor/);assert.match(q(11).stimulus[0].transcript,/\[song title not confirmed\]/);for(const name of ['../secret.mp3','https://other.test/a.mp3','ingles-2023-08.mp3','garden.mp3'])assert.equal(a.context.PE305.audioURL(name),null);
});
test('reportes y simulacros con audio se recuperan después de recargar',()=>{
 const a=runtime('basica-ingles'),q=a.context.PE305.pool('audio')[15];a.context.target=q;assert.equal(a.context.PE309.saveReport(q.id,'material','Revisar volumen del comentario.').ok,true);a.run("quiz=[target];mode='simulation';SIM12={index:0,answers:{},marked:{},timeSpent:{},enteredAt:Date.now(),seconds:900,maxSeconds:900,startedAt:new Date().toISOString()};PE303.startClock();sim12Choose(target.a)");const b=runtime('basica-ingles',{storage:a.storage});b.context.PE303.resume();assert.deepEqual(plain(b.run('quiz[0]')),plain(q));assert.match(b.elements.get('simulation').innerHTML,/<audio controls/);assert.doesNotMatch(b.elements.get('simulation').innerHTML,/pe307-transcript/);assert.equal(b.context.PE309.get(q.id).details,'Revisar volumen del comentario.');b.run('finishSimulation12()');assert.equal(b.run('S.simulations.at(-1).right'),1);
});
