from common import *
import history_maps
S='basica-historia'
def f(asset,title,alt):return [fig(asset,title,alt)]
def sources(a,b,period):return [text('Fuente A · síntesis didáctica original',period+'\n'+a),text('Fuente B · síntesis didáctica original',period+'\n'+b)]
coords=f('308-coord35.svg','Red de coordenadas','P: 35° S y 70° O, al sur del ecuador y al oeste de Greenwich.')
rev(S+'-307-01','En la representación, ¿qué concepto corresponde a los 35° S del punto P?',
 ('Latitud sur.','Los paralelos permiten medir la distancia angular al ecuador. P se sitúa 35° hacia el sur de esa línea de referencia.'),
 ('Longitud oeste.','La longitud se mide respecto de Greenwich. En P corresponde a 70° O, no a 35° S.'),
 ('Altitud sobre el mar.','La altitud es una distancia vertical, habitualmente expresada en metros; los grados de la figura son coordenadas angulares.'),
 ('Distancia en kilómetros al ecuador.','35° expresa un ángulo de latitud. No equivale a 35 kilómetros sobre la superficie.'),coords)
rev('hg22-01','Según la red geográfica, ¿en qué hemisferios se encuentra P?',
 ('Sur y occidental.','P está debajo del ecuador, en 33° S, y a la izquierda de Greenwich, en 70° O: hemisferios sur y occidental.'),
 ('Norte y occidental.','O indica oeste, pero 33° S ubica P al sur del ecuador, no en el hemisferio norte.'),
 ('Sur y oriental.','S indica sur; sin embargo, O corresponde a oeste de Greenwich y no al hemisferio oriental.'),
 ('Norte y oriental.','Esta combinación invierte ambas coordenadas: P está al sur y al oeste de las líneas de referencia.'),f('308-coord33.svg','Coordenadas del punto P','P está en 33° S y 70° O.'))
rev(S+'-28-18','¿Qué línea de la representación sirve de origen para medir la coordenada 35° S de P?',
 ('El ecuador, paralelo de 0°.','La latitud se cuenta hacia el norte o sur a partir del ecuador. La coordenada S de P se refiere a esa línea.'),
 ('Greenwich, meridiano de 0°.','Greenwich es el origen para medir longitud este u oeste; no para la coordenada de latitud sur.'),
 ('El meridiano de 70° O.','Ese meridiano pasa por P, pero no es el origen para medir su latitud.'),
 ('El paralelo de 40° S.','Este paralelo aparece como otra referencia en la red; el origen de las latitudes es 0°, no 40° S.'),coords)
rev(S+'-287-01','En el esquema, la coordenada 70° O de P se obtiene midiendo su distancia angular respecto de Greenwich. ¿Cómo se llama esta coordenada?',
 ('Longitud.','La longitud ubica un lugar al este u oeste del meridiano de origen; en este caso son 70° al oeste.'),
 ('Latitud.','La latitud se mide desde el ecuador y se expresa al norte o al sur. En P es 35° S.'),
 ('Relieve.','El relieve describe las formas y alturas de la superficie; no la distancia angular a Greenwich.'),
 ('Densidad.','La densidad relaciona población y superficie. No es una coordenada geográfica angular.'),coords)
rev(S+'-307-02','Usando la orientación del plano, ¿dónde queda la biblioteca respecto de la plaza?',
 ('Dos cuadras al este y una al sur.','La flecha indica norte hacia arriba. Desde la plaza se avanza dos tramos a la derecha, este, y uno hacia abajo, sur.'),
 ('Dos cuadras al oeste y una al sur.','El desplazamiento horizontal hacia la derecha corresponde a este, no a oeste, con esta orientación.'),
 ('Dos cuadras al este y una al norte.','La biblioteca está una fila por debajo de la plaza; ese desplazamiento es hacia el sur.'),
 ('Una cuadra al este y dos al sur.','Se intercambian las cantidades: en el plano hay dos tramos horizontales y uno vertical.'),f('308-plano.svg','Plano del barrio','La biblioteca está dos cuadras a la derecha y una abajo de la plaza; norte arriba.'))
rev(S+'-287-02','¿Qué ubicación de Coquimbo respecto del Maule permite establecer el esquema?',
 ('Coquimbo se encuentra al norte del Maule.','La flecha marca norte hacia arriba y Coquimbo aparece por encima del Maule; eso permite establecer su posición relativa.'),
 ('Coquimbo se encuentra al sur del Maule.','El sur está hacia abajo en este esquema, pero Coquimbo aparece sobre el Maule.'),
 ('Coquimbo se encuentra al este del Maule a igual latitud.','La disposición mostrada es de norte a sur; no son dos regiones situadas a la misma latitud.'),
 ('Coquimbo y Maule son regiones vecinas con límite común.','El esquema muestra regiones seleccionadas y omite otras. La cercanía dibujada no permite inferir un límite común; estas dos regiones no son contiguas.'),f('308-regiones.svg','Ubicación relativa en Chile','Esquema de regiones seleccionadas, con Coquimbo al norte del Maule; no representa todos los límites.'))
for qid,cm,den,km in [(S+'-307-03',4,200000,8),(S+'-287-03',3,100000,3)]:
 rev(qid,f'¿Qué distancia real representa el segmento A–B del mapa a escala 1:{den:,}?'.replace(',','.'),
 (f'{km} km.',f'Cada centímetro representa {den:,} cm reales. {cm} × {den:,} = {cm*den:,} cm; al dividir por 100.000 se obtienen {km} km.'.replace(',','.')),
 (f'{km*10} km.','Esta conversión multiplica la distancia por diez. Un kilómetro contiene 100.000 cm, no 10.000 cm.'),
 (f'{km/10:g} km.','Esta conversión reduce la distancia diez veces: se debe dividir el resultado en centímetros por 100.000.'),
 (f'{cm} metros.','La medida del dibujo no se traslada directamente a metros reales: es necesario aplicar primero el factor de escala.'),f(f'308-escala{cm}.svg','Escala y segmento A–B',f'A–B mide {cm} cm en el mapa original; escala 1:{den}.'))
rev(S+'-307-43','La zona P está sombreada de oscuro en ambos mapas. ¿Qué información se obtiene al leer sus leyendas?',
 ('Tiene al menos 50 hab./km² y al menos 1.000 m de altitud.','En A el oscuro representa densidad desde 50 hab./km²; en B representa altitud desde 1.000 m. El mismo color codifica variables distintas.'),
 ('Tiene exactamente 50 habitantes y 1.000 m de altitud.','La leyenda de A indica habitantes por km² y ambas leyendas son intervalos abiertos hacia arriba, no valores exactos.'),
 ('Tiene menos de 50 hab./km² y menos de 1.000 m de altitud.','Esos rangos corresponden a las zonas claras, mientras que P está en la categoría oscura.'),
 ('Tiene la misma densidad y la misma altitud porque posee el mismo color.','Densidad y altitud usan unidades distintas. Compartir color no iguala los valores de dos variables diferentes.'),f('308-leyendas.svg','Mapas de densidad y altitud','P oscuro: mapa A ≥50 hab./km²; mapa B ≥1.000 m.'))
rev(S+'-28-01','¿Qué consulta responde directamente cada uno de los dos mapas?',
 ('A permite reconocer rangos de altitud; B permite reconocer divisiones administrativas.','La leyenda de A usa alturas en metros, propias de una representación física; B delimita regiones, información político-administrativa.'),
 ('A permite conocer la población; B permite conocer las precipitaciones.','Ninguna leyenda presenta habitantes ni lluvias: A usa metros de altitud y B límites regionales.'),
 ('A muestra regiones administrativas; B muestra rangos de altitud.','Se invierten las variables de sus leyendas: las franjas de A son alturas y las líneas de B son límites.'),
 ('Ambos permiten calcular la población total de cada región.','No incluyen datos de población ni una relación de densidad y superficie que permita calcularla.'),f('308-tiposmapa.svg','Dos representaciones de un territorio','A: franjas de altitud. B: regiones R1, R2 y R3 con sus límites.'))

rev(S+'-23-01','Una zona chilena presenta clima semiárido, valles transversales y ríos como Elqui y Limarí, cuyos caudales permiten agricultura de riego. ¿Qué zona natural se caracteriza?',
 ('Norte Chico.','La combinación de semiaridez y valles transversales de Elqui y Limarí caracteriza al Norte Chico.'),
 ('Norte Grande.','En el Norte Grande predomina una aridez más intensa; los valles transversales señalados corresponden al Norte Chico.'),
 ('Zona Sur.','La Zona Sur se caracteriza por lluvias más abundantes y paisajes lacustres y vegetación asociados; no por el conjunto semiárido descrito.'),
 ('Zona Austral.','La Zona Austral incluye relieves fragmentados, fiordos y climas fríos; no corresponde a los valles transversales citados.'),[])
rev(S+'-307-06','En una cuenca de Coquimbo con clima semiárido se simula un año seco con 80 unidades de agua disponible y demandas de 20 para consumo humano, 55 agrícolas y 15 mineras. ¿Qué desafío regional muestran estos datos?',
 ('Las demandas suman 90 y superan la disponibilidad en 10; se deben evaluar prioridades y eficiencia entre usos.','20 + 55 + 15 = 90 frente a 80 disponibles. El déficit en una cuenca semiárida exige considerar usos humanos y productivos; la tabla por sí sola no determina cómo repartir el agua.'),
 ('Existe un excedente de 10 que permite aumentar todos los usos.','La resta está invertida: la demanda es 10 unidades mayor que la oferta, por lo que hay déficit y no excedente.'),
 ('La minería utiliza más agua que la agricultura en este escenario.','Las demandas simuladas son 15 para minería y 55 para agricultura. La minería no es el mayor uso de la tabla.'),
 ('La aridez hace innecesario comparar las demandas de cada sector.','Precisamente ante menor disponibilidad, comparar demandas permite dimensionar la presión sobre el recurso y evaluar medidas.'),[text('Escenario didáctico','Datos simulados para una cuenca de la Región de Coquimbo; no constituyen una medición regional real.')])
rev(S+'-306-2023-24','En un sector costero ficticio de Valparaíso, con suelo urbanizable limitado por cerros, crecen viviendas de alto precio y servicios turísticos. Suben los arriendos y familias arrendatarias de menores ingresos se trasladan a sectores periféricos. ¿Qué desafío urbano ilustra el caso?',
 ('Desplazamiento residencial asociado al encarecimiento y la transformación social del barrio.','La valorización del sector costero puede excluir a hogares que no pueden afrontar los nuevos arriendos. El relieve y la presión inmobiliaria contextualizan el problema regional.'),
 ('Despoblamiento originado únicamente por una caída de la demanda de viviendas.','El caso describe mayor inversión y alza de arriendos, señales de presión de demanda, no una caída que explique por sí sola el desplazamiento.'),
 ('Expansión de la agricultura por una mayor disponibilidad de suelo plano.','Se trata de vivienda, turismo y suelo urbano limitado por cerros; no de una transformación agrícola.'),
 ('Reducción de la segregación porque todas las familias acceden a los nuevos servicios.','El traslado de hogares de menores ingresos muestra acceso desigual; no se puede concluir que todos permanecen y reciben los mismos beneficios.'),[])
rev(S+'-23-04','Una planta descarga residuos orgánicos en un río. Aguas arriba se registran 8 mg/L de oxígeno disuelto y 6 especies de peces; aguas abajo, 3 mg/L y 2 especies. Si no hay otros vertidos entre ambos puntos, ¿qué efecto productivo es compatible con los datos?',
 ('La degradación de residuos puede consumir oxígeno y perjudicar a los peces aguas abajo.','La materia orgánica favorece la actividad de descomponedores que consumen oxígeno. Su descenso es compatible con la menor riqueza de peces; el contraste apoya esta explicación sin demostrar por sí solo todas las causas.'),
 ('El vertido aumentó el oxígeno y diversificó la comunidad de peces.','Los datos muestran descensos de oxígeno y del número de especies, justo lo contrario de esta afirmación.'),
 ('La disminución de peces demuestra que el agua posee menos contaminantes.','Una menor riqueza no acredita limpieza. Aquí coincide con menos oxígeno en el tramo que recibe residuos.'),
 ('El impacto termina en el punto de descarga y no puede propagarse.','El río transporta sustancias aguas abajo; las mediciones en ese tramo son compatibles con efectos más allá del punto de vertido.'),[table('Mediciones simuladas en la misma fecha',['Tramo','Oxígeno disuelto','Especies de peces'],[['Aguas arriba','8 mg/L',6],['Aguas abajo','3 mg/L',2]])])
rev(S+'-306-2023-21','En un valle semiárido chileno, el sobrepastoreo reduce la cubierta vegetal. Tras una lluvia intensa aparecen surcos y sedimentos en canales. ¿Qué relación explica un efecto de esta actividad productiva?',
 ('La pérdida de vegetación deja el suelo expuesto y facilita su arrastre por escorrentía.','El sobrepastoreo elimina protección y raíces que retienen suelo. La lluvia puede desprender y transportar partículas, disminuyendo suelo fértil y colmatando canales.'),
 ('El ganado aumenta siempre la infiltración y elimina el arrastre de suelo.','La eliminación de cobertura y el pisoteo pueden favorecer compactación y escorrentía; no garantizan infiltración ni eliminan la erosión.'),
 ('La erosión observada solo puede atribuirse a la sequía, sin relación con el pastoreo.','El caso aporta una presión humana concreta: reducción de cobertura por sobrepastoreo. La condición semiárida no descarta ese efecto productivo.'),
 ('La acumulación en los canales demuestra creación inmediata de nuevo suelo fértil en las laderas.','Los sedimentos provienen del material removido. Su acumulación en canales indica transporte y pérdida desde las laderas, no formación inmediata de suelo allí.'),[])
rev(S+'-28-19','Un territorio chileno reúne las tres características presentadas. ¿Qué interpretación integra la información de relieve, clima y uso del suelo?',
 ('El riego hace posible la agricultura del valle pese a la escasez de lluvia y la concentra en terrenos cultivables.','La planicie facilita cultivos, la baja precipitación limita el aporte pluvial y los canales suministran agua. La explicación articula las tres fuentes.'),
 ('La agricultura depende solo de lluvias abundantes durante todo el año.','El registro muestra precipitaciones escasas; además, la fuente sobre usos registra riego, por lo que esta conclusión contradice los datos.'),
 ('Las mayores superficies de cultivo se ubican necesariamente en pendientes fuertes.','La información sitúa los cultivos en el fondo del valle, donde el relieve es más plano, no en las pendientes fuertes.'),
 ('Los canales carecen de relación con la distribución de los cultivos.','La coincidencia entre zonas irrigadas y cultivos, junto con poca lluvia, sustenta la importancia del riego en esa distribución.'),[table('Tres fuentes de un valle didáctico del Norte Chico',['Fuente','Información'],[['Perfil de relieve','Fondo de valle plano; laderas con pendientes fuertes.'],['Registro climático','Precipitaciones anuales escasas.'],['Mapa de usos','Cultivos concentrados en el fondo del valle junto a canales de riego.']])])
rev(S+'-28-04','Una investigación compara cómo cambió el transporte urbano de Santiago entre 1900, 1950 y 2000, observando permanencias y transformaciones. ¿Qué uso del tiempo histórico predomina?',
 ('Un análisis diacrónico de un proceso a través del tiempo.','Se sigue el mismo tema en momentos sucesivos para examinar cambios y continuidades; eso constituye una perspectiva diacrónica.'),
 ('Un análisis sincrónico de varias ciudades en un mismo año.','La sincronía compara fenómenos contemporáneos; aquí se estudia una ciudad en tres momentos distintos.'),
 ('Una medición de duración que prescinde de comparar cambios.','Hay fechas y duración, pero el objetivo explícito es explicar transformaciones y permanencias, no solo contar años.'),
 ('Una descripción de un único acontecimiento sin desarrollo temporal.','El transporte urbano se examina como proceso durante un siglo, no como un evento aislado.'),[])
rev(S+'-28-05','En Atenas ciertos ciudadanos participaban en asambleas; Roma desarrolló normas e instituciones jurídicas sistematizadas. ¿Qué vínculo con el presente reconoce estos legados sin confundirlos con sistemas actuales?',
 ('La participación cívica y el derecho tienen antecedentes antiguos, aunque hoy existen reglas y derechos diferentes.','Se reconocen aportes griegos y romanos sin suponer identidad: la ciudadanía antigua excluía amplios grupos y las instituciones actuales han cambiado.'),
 ('La democracia ateniense otorgaba iguales derechos políticos a todas las personas como las democracias actuales.','En Atenas la ciudadanía política no incluía, entre otros, a mujeres, esclavos ni extranjeros residentes; no era sufragio universal.'),
 ('El derecho romano dejó sin influencia a los sistemas jurídicos posteriores.','El legado jurídico romano influyó en tradiciones posteriores, especialmente en el derecho civil; negar toda influencia desconoce ese aporte.'),
 ('Atenas y Roma tuvieron instituciones idénticas y una única forma permanente de gobierno.','Ambas sociedades presentaron diferencias y cambios históricos; no compartieron un sistema político invariable e idéntico.'),[])
rev(S+'-307-13','Compara las síntesis sobre agricultura en el Egipto antiguo y en el mundo inca. ¿Qué semejanza y diferencia están sustentadas?',
 ('Ambas organizaron trabajo para producir alimentos; una aprovechó tierras fluviales y la otra acondicionó laderas con terrazas.','Las dos respondieron a necesidades alimentarias mediante trabajo organizado, adaptando la producción a medios distintos: valle del Nilo y laderas andinas.'),
 ('Ambas dependieron exclusivamente de lluvias regulares y no modificaron su entorno.','Las fuentes mencionan canales y terrazas, intervenciones humanas que permiten manejar condiciones del medio.'),
 ('Egipto cultivó solo terrazas de montaña y los incas solo llanuras del Nilo.','Esta alternativa intercambia las localizaciones y técnicas descritas; el Nilo está en África y las terrazas señaladas en los Andes.'),
 ('Las diferencias del relieve impidieron cualquier organización colectiva del trabajo.','Ambas fuentes describen coordinación de labores; el relieve condiciona soluciones, pero no elimina la organización social.'),sources('La producción agrícola egipcia aprovechó suelos del valle del Nilo y sistemas de riego; las crecidas y labores agrícolas requerían coordinación.','En zonas andinas del Tahuantinsuyo, las terrazas permitieron cultivar laderas y manejar agua y suelo; su construcción y mantenimiento requirieron trabajo organizado.','Comparación de sociedades de periodos y regiones distintos; textos originales para práctica.'))

conquest=sources('La fundación de ciudades y la distribución de encomiendas ayudaron a los conquistadores españoles a instalar autoridades y obtener tributos y trabajo indígena.','Las respuestas de los pueblos indígenas fueron diversas: hubo resistencia y también alianzas con españoles, vinculadas a rivalidades y objetivos propios.','Conquista de América, siglo XVI. Síntesis secundarias, no citas de crónicas.')
for qid,stem,correct,reason in [
 (S+'-307-16','¿Qué explicación del proceso de conquista integra las dos fuentes?','La instalación del dominio español coexistió con distintas acciones y estrategias indígenas.','A describe instituciones de dominación y B muestra respuestas diversas; juntas permiten explicar la conquista como un proceso conflictivo con actores que no actuaron todos del mismo modo.'),
 ('hg22-03','¿Qué generalización queda cuestionada al contrastar la fuente B con la A?','Que todos los pueblos indígenas respondieron de la misma manera frente a la conquista.','B menciona resistencia y alianzas con objetivos propios, lo que impide reducir todas las respuestas indígenas a una conducta única; A no elimina esa diversidad.'),
 (S+'-28-06','¿Qué dimensión agrega la fuente B a la explicación institucional de la fuente A?','La capacidad de los pueblos indígenas para resistir o establecer alianzas según sus intereses.','A se concentra en ciudades y encomiendas; B incorpora acciones e intereses indígenas, ampliando la explicación del proceso.'),
 (S+'-287-11','¿Cuál de estas interpretaciones considera tanto la imposición colonial como la diversidad de relaciones durante la conquista?','La dominación se construyó mediante instituciones españolas y relaciones variables de alianza y conflicto.','La primera fuente respalda el papel de las instituciones de dominio; la segunda muestra que las relaciones incluyeron resistencia y alianzas, sin convertirlas en igualdad política.')]:
 wrong=[('Las alianzas implicaron que desaparecieran todas las relaciones de dominación.','La existencia de alianzas no elimina las encomiendas ni la instalación de autoridades descritas en A; colaboración y subordinación podían coexistir.'),('La conquista fue solamente un reemplazo de autoridades sin participación indígena.','B atribuye acciones, intereses y estrategias a los pueblos indígenas; no fueron actores ausentes del proceso.'),('Todas las comunidades indígenas formaron una alianza única y permanente.','B señala diversidad de respuestas. No sostiene unanimidad ni estabilidad de las alianzas en toda América.')]
 if qid=='hg22-03':wrong=[('Que hubo fundación de ciudades durante la conquista.','La fuente A afirma la fundación de ciudades y B no la contradice; la diferencia se refiere a las respuestas indígenas.'),('Que existieron estrategias políticas entre los pueblos indígenas.','B respalda, en vez de refutar, la existencia de intereses, resistencias y alianzas indígenas.'),('Que las encomiendas contribuyeron a la dominación.','A sostiene esa función de las encomiendas y B no la desmiente al describir otras relaciones.')]
 rev(qid,stem,(correct,reason),*wrong,stim=conquest)
colonial=sources('La Corona reguló el comercio colonial mediante puertos, rutas y comerciantes autorizados, buscando controlar los intercambios y recaudar ingresos.','Las dificultades de abastecimiento y los precios de algunos productos incentivaron intercambios que eludían los canales autorizados.','Comercio colonial hispanoamericano antes de su progresiva apertura. Síntesis secundarias originales.')
for qid,stem in [(S+'-307-17','Al contrastar las fuentes sobre comercio colonial, ¿qué relación se puede explicar?'),(S+'-306-2023-29','¿Cómo ayudan ambas fuentes a explicar los incentivos al contrabando colonial?')]:
 rev(qid,stem,('Las restricciones del comercio legal y una demanda no satisfecha podían favorecer intercambios no autorizados.','A describe controles del canal autorizado y B necesidades que persistían; su combinación permite comprender incentivos al contrabando sin afirmar que todo comercio fuera ilegal.'),('El control de rutas eliminó toda demanda de bienes importados.','La fuente B señala dificultades de abastecimiento y demanda persistente; las restricciones no hicieron desaparecer esa demanda.'),('El contrabando era un intercambio expresamente autorizado por la Corona.','Eludir los canales autorizados distingue al contrabando de los intercambios legales regulados que describe A.'),('La existencia de contrabando demuestra que no hubo reglas comerciales.','El contrabando supone eludir reglas existentes; A presenta precisamente esas restricciones, que podían coexistir con incumplimientos.'),colonial)
encomienda=sources('La encomienda concedía a un beneficiario el cobro de tributos de comunidades indígenas y le imponía obligaciones de protección y enseñanza cristiana.','En Chile, la extracción de trabajo indígena para labores mineras y agrarias generó abusos y disputas; normas y tasas buscaron regular esas prestaciones.','Instituciones y relaciones sociales del Chile colonial. Síntesis secundarias originales.')
rev(S+'-287-12','¿Qué tensión del periodo colonial puede explicarse al relacionar las dos fuentes sobre encomienda?',
 ('La obligación declarada de protección coexistió con formas de explotación del trabajo indígena.','A enuncia deberes formales y B describe abusos ligados a la extracción de trabajo. El contraste muestra una tensión entre norma e implementación, no ausencia de regulación.'),
 ('Las obligaciones de protección impidieron cualquier abuso laboral.','La fuente B registra abusos y disputas; la existencia de una norma no garantiza su cumplimiento efectivo.'),
 ('Las comunidades decidían libremente todas las condiciones de tributación.','A describe una concesión a beneficiarios y B extracción de trabajo; no presentan una relación de libre negociación igualitaria.'),
 ('La encomienda equivalía solamente a comprar tierras sin relación con personas o tributos.','La institución se vincula a tributos y trabajo de comunidades; las mercedes de tierra corresponden a otra concesión.'),encomienda)
rev(S+'-307-46','¿Qué característica de la sociedad colonial se explica al contrastar las funciones descritas en ambas fuentes?',
 ('Instituciones religiosas y autoridades de la monarquía organizaban aspectos distintos de la vida de la población.','A muestra intervención eclesiástica en ritos y registros; B muestra intervención civil y fiscal. Ambas dimensiones coexistían en el orden colonial.'),
 ('Solo las parroquias ejercían funciones de gobierno y recaudación.','B identifica autoridades reales y registros fiscales; la sociedad colonial no se organizaba exclusivamente mediante parroquias.'),
 ('Los registros de ambas instituciones tenían una finalidad idéntica.','A registra sacramentos y B obligaciones fiscales; pueden aportar información poblacional, pero respondían a finalidades diferentes.'),
 ('La vida religiosa estaba separada de toda forma de registro comunitario.','A señala que los sacramentos se registraban en parroquias, relacionando prácticas religiosas con documentación de la población.'),sources('Las parroquias celebraban y registraban bautismos, matrimonios y entierros, integrando prácticas religiosas y documentación de la vida local.','Las autoridades coloniales elaboraban padrones y registros para gobernar y organizar obligaciones fiscales de grupos de población.','Organización social de Hispanoamérica colonial. Síntesis secundarias originales; no transcripciones de registros.'))
independence=[text('Fuente secundaria · síntesis original','En 1810, ante la crisis de la monarquía española, la Junta de Santiago afirmó gobernar en nombre de Fernando VII. En 1818, la proclamación de independencia sostuvo la separación de Chile de la monarquía española. Estos pronunciamientos pertenecen a momentos distintos de un proceso con conflictos internos y guerra.')]
rev(S+'-28-07','¿Qué cambio de legitimidad política permite interpretar la fuente sobre 1810 y 1818?',
 ('De una autoridad que invocaba al monarca ausente a la afirmación de una soberanía separada de España.','La Junta de 1810 invocaba a Fernando VII, mientras que la independencia de 1818 afirmaba la separación. El contraste muestra transformación de los fundamentos del poder.'),
 ('De una independencia ya declarada en 1810 a la restauración de la monarquía en 1818.','Se invierte el sentido de los pronunciamientos: la declaración de separación corresponde a 1818.'),
 ('De la ausencia de conflictos a una separación aceptada de inmediato por todos.','La fuente menciona guerra y conflictos internos; no sostiene consenso ni una transición sin enfrentamientos.'),
 ('De una monarquía absoluta a la participación política universal de toda la población en 1818.','La separación no demuestra por sí sola ciudadanía universal. La fuente aborda soberanía y no amplía automáticamente derechos políticos a toda la población.'),independence)
rev(S+'-287-13','¿Por qué los pronunciamientos de 1810 y 1818 respaldan entender la independencia como un proceso?',
 ('Porque muestran objetivos políticos que se transformaron en una secuencia atravesada por conflictos.','La distancia entre gobernar en nombre del rey y declarar la separación indica cambios en el tiempo; la fuente también sitúa esos cambios en conflictos y guerra.'),
 ('Porque ambos declaran exactamente el mismo objetivo de independencia.','La Junta de 1810 invocaba al rey; por eso los pronunciamientos no expresan un objetivo idéntico.'),
 ('Porque una sola proclamación explica todos los cambios sociales posteriores.','La fuente presenta distintos momentos y conflictos. No permite reducir las transformaciones a un acto aislado ni explicar por él todo lo posterior.'),
 ('Porque la independencia se produjo sin alterar el fundamento de la autoridad.','Pasar de invocar al monarca a separarse de España cambia el fundamento de soberanía descrito.'),independence)
constit=[table('Propuestas de organización, síntesis didáctica',['Ensayo','Rasgo político'],[['Constitución de 1823','Regulación de la vida pública y privada mediante normas de virtud y moralidad.'],['Leyes federales de 1826','Distribución del poder entre provincias y mayor autonomía provincial.'],['Constitución de 1828','Reconocimiento de libertades individuales y límites al poder político.']])]
rev(S+'-307-19','¿Qué contraste ideológico entre los ensayos se sustenta en la tabla?',
 ('En 1823 se buscó regular la conducta moral; en 1826, redistribuir territorialmente el poder; en 1828, resguardar libertades.','Los rasgos presentan prioridades políticas diferentes. La organización nacional involucró disputas sobre normas, autoridad territorial y derechos, no solo cambios de fecha.'),
 ('Los tres ensayos defendieron un federalismo idéntico.','La autonomía provincial distingue a las leyes de 1826; la tabla no atribuye el mismo federalismo a los otros ensayos.'),
 ('1823 y 1828 rechazaron toda regulación del poder y de la conducta.','1823 propuso regular la conducta y 1828 estableció límites políticos; la afirmación contradice los dos rasgos.'),
 ('Los cambios respondieron únicamente al nombre del gobernante.','La tabla muestra diferencias de propuestas institucionales e ideológicas, no simples reemplazos personales.'),constit)
rev(S+'-287-14','Un grupo sostiene que las provincias deben decidir más asuntos propios para reducir su dependencia del centro. ¿Con qué ensayo de la tabla coincide y por qué?',
 ('Con las leyes de 1826, por su orientación federal y autonomía provincial.','La distribución territorial del poder y la autonomía son los rasgos de 1826 señalados en la tabla; responden directamente a la demanda del grupo.'),
 ('Con la Constitución de 1823, porque regular la moral equivale a federalismo.','La regulación moral es una dimensión distinta de la distribución del poder entre provincias; no hace equivalentes ambas propuestas.'),
 ('Con la Constitución de 1828, porque las libertades individuales eliminan necesariamente el gobierno central.','Resguardar libertades no implica eliminar el centro ni adoptar necesariamente una organización federal.'),
 ('Con todos por igual, porque se promulgaron después de la independencia.','Compartir periodo no hace iguales sus propuestas: la tabla distingue específicamente el proyecto federal de 1826.'),constit)
territory=[text('Antecedentes territoriales · síntesis didáctica','Antes de la Guerra del Pacífico, Tarapacá pertenecía al Perú. El Tratado de Ancón de 1883 estableció su cesión a Chile. En esa zona existían importantes yacimientos salitreros. El cambio de soberanía supuso incorporar territorio, población y actividades económicas a la administración estatal chilena.')]
rev(S+'-307-21','¿Por qué la incorporación de Tarapacá fue parte de la conformación del Estado-nación chileno y no solo un cambio en el dibujo del mapa?',
 ('Amplió el espacio bajo soberanía chilena e implicó administrar población y recursos de la zona incorporada.','El cambio territorial llevó decisiones de jurisdicción, administración y control de recursos; por eso se relaciona con la construcción material e institucional del Estado.'),
 ('Se limitó a cambiar el nombre de la región sin alterar su soberanía.','El antecedente central es la cesión de soberanía de Perú a Chile, con efectos administrativos, no un cambio nominal.'),
 ('Transformó automáticamente a toda la población en culturalmente homogénea.','La soberanía estatal no produce homogeneidad cultural inmediata; no debe confundirse integración territorial con identidad uniforme.'),
 ('Eliminó la necesidad de establecer instituciones en la zona.','La incorporación requiere extender o reorganizar la administración; no vuelve innecesarias las instituciones.'),territory)
rev(S+'-287-15','¿Qué relación entre guerra, tratado y administración estatal se desprende del caso de Tarapacá?',
 ('El conflicto y el acuerdo posterior modificaron la soberanía, extendiendo responsabilidades del Estado chileno.','La guerra se vincula con un tratado que establece cesión territorial. El Estado debe administrar un espacio incorporado, con habitantes y recursos.'),
 ('El tratado mantuvo Tarapacá bajo soberanía peruana y solo permitió visitas chilenas.','La fuente señala cesión a Chile, no una autorización temporal de tránsito o visita.'),
 ('El cambio de soberanía dependió únicamente de decisiones de empresas salitreras.','La presencia de recursos importa, pero el antecedente aportado corresponde a guerra y tratado entre Estados, no a una transferencia privada.'),
 ('La administración del territorio permaneció necesariamente ajena al Estado chileno.','La incorporación bajo soberanía chilena implica atribuciones estatales; no sostiene una exclusión permanente del Estado.'),territory)
rev(S+'-306-2023-34','Al relacionar los antecedentes sobre Tarapacá, ¿qué vínculo entre territorio y economía es históricamente pertinente?',
 ('La expansión de soberanía incorporó una zona salitrera cuya administración y tributación cobraron importancia para el Estado.','La soberanía sobre un espacio con salitre permitió al Estado organizar su administración y obtener ingresos asociados a la actividad; el territorio tenía efectos económicos e institucionales.'),
 ('El Estado pasó a ser necesariamente dueño directo de todas las salitreras.','Soberanía y propiedad empresarial son conceptos distintos. Incorporar un territorio no implica nacionalizar automáticamente todas las empresas.'),
 ('El tratado eliminó cualquier actividad económica en Tarapacá.','Los antecedentes destacan recursos salitreros; el cambio de soberanía no supone desaparición de la actividad económica.'),
 ('La importancia de los recursos vuelve irrelevante la población y el control territorial.','Los recursos son una dimensión del proceso. Incorporar territorio implica también habitantes, jurisdicción y administración.'),territory)
dictature=[table('Chile desde 1973 · síntesis de transformaciones',['Dimensión','Antecedente'],[['Política','Disolución del Congreso y concentración de funciones de gobierno y legislación en la Junta.'],['Economía','Privatización de empresas estatales y apertura al comercio exterior durante el régimen.']])]
rev(S+'-307-24','¿Qué interpretación relaciona correctamente las transformaciones políticas y económicas de la tabla?',
 ('Se concentró la autoridad política y se amplió el papel del mercado en la organización económica.','La disolución del Congreso reduce la separación institucional de poderes; privatización y apertura comercial reorientan la economía hacia mecanismos de mercado.'),
 ('Se amplió la competencia electoral mientras se estatizaban todas las empresas.','La concentración política no equivale a competencia electoral y las privatizaciones son transferencias hacia propiedad privada, no estatización general.'),
 ('La apertura comercial implicó por sí sola apertura democrática.','La apertura a intercambios económicos no garantiza pluralismo ni elecciones; la tabla muestra concentración del poder político simultánea.'),
 ('La privatización eliminó toda intervención del Estado, incluida la autoridad política.','Cambiar la propiedad de empresas no elimina el Estado ni su poder. La dimensión política muestra, de hecho, concentración de autoridad.'),dictature)
rev(S+'-28-08','¿Qué consecuencia institucional permite analizar el antecedente político presentado?',
 ('Se redujo la existencia de un Congreso independiente que deliberara y controlara públicamente al Ejecutivo.','Disolver el Congreso y concentrar funciones en la Junta suprime un espacio institucional de representación y contrapeso; no se trata solo de cambiar sus integrantes.'),
 ('Se fortaleció una legislatura plural elegida regularmente.','La fuente registra disolución del Congreso, no fortalecimiento de una legislatura plural electa.'),
 ('La potestad legislativa quedó separada de las autoridades del régimen.','El antecedente dice que gobierno y legislación se concentraron en la Junta, lo contrario de una separación reforzada.'),
 ('El cambio económico permite concluir que no hubo cambios institucionales.','Las dos dimensiones son diferentes y la tabla registra expresamente disolución y concentración de funciones políticas.'),dictature)
rev(S+'-287-18','¿Por qué sería incorrecto afirmar que las privatizaciones muestran una democratización política durante el régimen militar?',
 ('Porque un cambio de propiedad económica no demuestra ampliación de participación ni contrapesos políticos.','La privatización afecta la organización económica; la tabla simultáneamente muestra concentración del poder. No se deduce democratización de una política de mercado.'),
 ('Porque privatizar significa transferir empresas privadas al Estado.','Eso describe estatización, no privatización; además, propiedad empresarial y democracia política son dimensiones distintas.'),
 ('Porque apertura comercial y elecciones competitivas son sinónimos.','La apertura al comercio es una decisión económica; las elecciones competitivas requieren condiciones políticas que no se derivan de ella.'),
 ('Porque el régimen mantuvo el Congreso funcionando sin cambios.','La tabla registra su disolución y concentración de funciones, lo que contradice esta premisa.'),dictature)
transition=[text('Secuencia y condiciones · síntesis didáctica','El triunfo del No en el plebiscito de 1988 rechazó la continuidad de Augusto Pinochet por un nuevo periodo y abrió el paso a elecciones presidenciales y parlamentarias en 1989. Patricio Aylwin asumió la presidencia en marzo de 1990. El nuevo gobierno operó con instituciones heredadas, entre ellas senadores designados, que limitaron el alcance inmediato de los cambios.')]
rev(S+'-307-25','¿Cómo se relacionan el resultado de 1988 y la transferencia del gobierno en 1990?',
 ('El triunfo del No habilitó la vía electoral seguida por elecciones y la asunción de un presidente civil elegido.','El plebiscito no eligió directamente a Aylwin: rechazó la continuidad propuesta y abrió la secuencia electoral que culminó en su asunción.'),
 ('El plebiscito eligió directamente a Aylwin para asumir ese mismo día.','Aylwin fue elegido en 1989 y asumió en 1990. Confundir la consulta sobre continuidad con la elección presidencial altera su función.'),
 ('Las elecciones de 1989 fueron innecesarias porque el resultado de 1988 designó todo el Congreso.','El No no eligió parlamentarios; la elección presidencial y parlamentaria posterior fue un paso distinto.'),
 ('La transferencia eliminó inmediatamente todas las instituciones heredadas.','La fuente menciona senadores designados como continuidad; la recuperación del gobierno electo no suprimió de inmediato todos los condicionamientos.'),transition)
rev(S+'-307-47','¿Qué conclusión sobre cambio y continuidad está respaldada por los antecedentes de la transición?',
 ('Se recuperó un gobierno elegido, mientras persistieron instituciones que condicionaron la profundización democrática.','La elección y asunción civil constituyen cambios; los senadores designados muestran continuidades institucionales. Ambas dimensiones ayudan a explicar las condiciones de la transición.'),
 ('No hubo ningún cambio político porque persistieron instituciones anteriores.','La continuidad de algunos mecanismos no anula el cambio de un régimen militar a autoridades surgidas de elecciones.'),
 ('La elección de autoridades hizo desaparecer automáticamente todas las restricciones heredadas.','La fuente señala persistencia de senadores designados; elegir autoridades no equivale a eliminar toda restricción institucional.'),
 ('El retorno a elecciones significó que Pinochet resultó elegido presidente en 1989.','La secuencia identifica la elección y asunción de Patricio Aylwin, no una elección presidencial de Pinochet.'),transition)
rev(S+'-307-42','¿Qué orientación del Estado republicano permite interpretar la síntesis de la Constitución de 1833?',
 ('Fortalecer la autoridad central y presidencial para asegurar el orden político.','El carácter indivisible y la designación presidencial de intendentes apuntan a centralización, en el contexto de predominio conservador tras las disputas previas.'),
 ('Entregar soberanía independiente a cada provincia.','Una república indivisible y autoridades provinciales nombradas desde la presidencia se oponen a provincias soberanas independientes.'),
 ('Eliminar al Ejecutivo para concentrar todo el gobierno en asambleas comunales.','La síntesis atribuye competencias relevantes al presidente; no describe desaparición del Ejecutivo ni gobierno exclusivamente comunal.'),
 ('Establecer que toda autoridad pública fuese elegida mediante sufragio universal.','La designación de intendentes contradice esa afirmación; además, la ciudadanía política del periodo no correspondía al sufragio universal actual.'),[text('Fuente secundaria · adaptación didáctica','La Constitución de 1833 definió una república única e indivisible y otorgó amplias atribuciones al presidente, quien nombraba a los intendentes. Se promulgó tras el triunfo conservador en la guerra civil de 1829–1830. Síntesis original basada en la Biblioteca Nacional de Chile, «La Constitución de 1833»; no es una cita literal.')])
