from common import *
S='basica-lenguaje'
rev(S+'-23-01','¿Qué rasgos del relato permiten clasificarlo como fábula?',
 ('Animales actúan como personas y el desenlace propone una enseñanza sobre la conducta.','El zorro y la hormiga dialogan y toman decisiones humanas; la frase final generaliza una enseñanza. La combinación caracteriza la fábula.'),
 ('Dioses crean el mundo y explican el origen sagrado de la lluvia.','El relato no presenta dioses ni una explicación sagrada del origen del mundo; esos rasgos serían propios de un mito cosmogónico.'),
 ('Una comunidad vincula un hecho extraordinario con un lugar identificable de su tradición.','No se relata una tradición localizada ni un acontecimiento que explique una creencia comunitaria; el foco es una enseñanza moral mediante animales.'),
 ('Un héroe representa a su pueblo en una extensa serie de hazañas fundacionales.','Aquí hay un episodio breve con animales y moraleja, no el desarrollo amplio de gestas de un héroe colectivo propio de una epopeya.'),[text('Relato original','El zorro se burló de la hormiga por guardar semillas cada mañana. Cuando llegaron las lluvias, encontró su despensa vacía y pidió ayuda. La hormiga compartió sus granos y dijo: «Prepararse a tiempo evita dificultades después».')])
rev(S+'-28-01','¿Por qué este relato se aproxima al mito y no a una noticia?',
 ('Explica un origen mediante una acción sagrada de seres sobrenaturales.','La diosa modela el primer sol y funda el ciclo de los días; la explicación de un origen mediante seres sagrados corresponde a un rasgo mítico.'),
 ('Informa un acontecimiento reciente con fecha, lugar y fuentes verificables.','No hay cobertura de un hecho reciente comprobable; se narra un origen sagrado en un tiempo primordial.'),
 ('Presenta exclusivamente consejos prácticos para observar el cielo.','La diosa y la creación del sol forman una narración de origen, no instrucciones de observación.'),
 ('Expone una hipótesis científica que se somete a un experimento.','El texto no plantea pruebas experimentales ni mecanismos científicos; su explicación es simbólica y sobrenatural.'),[text('Relato original inspirado en convenciones del mito','Antes de que existieran los días, la diosa del cielo modeló una esfera de fuego y la elevó sobre el mar. Desde entonces, el primer sol recorre su camino para despertar a los seres de la tierra. Este texto es una creación didáctica, no un mito atribuido a una cultura real.')])
rev(S+'-287-01','¿Qué característica de este relato completo permite reconocer un cuento breve?',
 ('Concentra un único conflicto en pocos personajes y lo resuelve en una secuencia acotada.','La pérdida de la llave organiza el relato; el regreso de la hermana resuelve ese conflicto. La brevedad y concentración narrativa sustentan la clasificación.'),
 ('Desarrolla varias generaciones familiares y numerosas tramas paralelas.','El relato solo presenta un episodio con dos hermanas; no hay amplitud temporal ni múltiples líneas narrativas como en esa descripción de novela.'),
 ('Explica el origen sagrado de un fenómeno natural.','La historia narra un problema cotidiano con una llave; no aparecen dioses ni un relato de origen propio del mito.'),
 ('Presenta diálogos para su representación sin voz narrativa.','Hay una voz que cuenta acciones y pensamientos; no se trata de un texto exclusivamente dramático con acotaciones y diálogos.'),[text('La llave · cuento original','Inés perdió la única llave antes de la lluvia. Revisó sus bolsillos, la mochila y el suelo. Cuando ya pensaba esperar afuera, su hermana volvió corriendo: había encontrado la llave junto al portón. Entraron justo cuando cayó la primera gota.')])
rev(S+'-305-2023-15','¿Qué combinación de rasgos permite clasificar la obra descrita como novela?',
 ('La extensión del relato, las tramas entrelazadas y la evolución de personajes durante varias décadas.','La amplitud temporal y el desarrollo sostenido de varias historias permiten reconocer convenciones de la novela; conocer pensamientos por sí solo no define el género.'),
 ('La sola presencia de un narrador que conoce pensamientos.','Un narrador con acceso a pensamientos puede aparecer también en cuentos y otros relatos; no es un criterio suficiente para distinguir novela.'),
 ('La existencia de una moraleja final y animales humanizados.','La descripción no incluye esos rasgos; corresponden convencionalmente a la fábula.'),
 ('La explicación religiosa del origen de un río mediante dioses.','No se presenta un relato sagrado de origen. La obra sigue vidas humanas y conflictos a lo largo del tiempo.'),[text('Descripción de una obra ficticia','La casa del estero tiene treinta capítulos. Sigue durante cuarenta años a tres generaciones de una familia y entrelaza conflictos por una herencia con la historia de sus vecinos. Las decisiones tempranas de los personajes producen consecuencias en etapas posteriores.')])
rev(S+'-305-2023-17','¿Qué rasgo distingue como leyenda el relato presentado?',
 ('Vincula un suceso extraordinario con un lugar reconocible y una tradición transmitida por la comunidad.','El puente local y el relato que cuentan los habitantes sitúan lo extraordinario en un espacio cercano de tradición colectiva, rasgo característico de la leyenda.'),
 ('Demuestra experimentalmente por qué se oye agua bajo cualquier puente.','No hay experimento ni explicación general; se transmite una narración local con un elemento extraordinario.'),
 ('Narra la creación del universo por divinidades primordiales.','El acontecimiento se asocia a un puente y a una viajera, no al origen sagrado del universo propio de ciertos mitos.'),
 ('Desarrolla una argumentación con estadísticas sobre seguridad vial.','El texto narra una tradición extraordinaria; no presenta tesis ni evidencia estadística sobre tránsito.'),[text('Relato original con convenciones de leyenda','En el pueblo ficticio de Las Vertientes, los mayores cuentan que una viajera guio a varios niños durante una inundación y luego desapareció. Dicen que, cuando crece el río, una luz recorre el antiguo puente para avisar a quienes se acercan. La comunidad sigue contando la historia en las noches de invierno.')])
rev(S+'-307-34','¿Qué rasgos acercan la obra descrita a la epopeya?',
 ('Las hazañas de un héroe representan valores e hitos fundacionales de su pueblo.','El protagonista tiene alcance colectivo y sus acciones se integran en una narración extensa de gestas; no se limita a un conflicto individual cotidiano.'),
 ('Una disputa doméstica breve concluye con una moraleja de animales.','Eso remite a una fábula; la descripción presenta un héroe y un destino colectivo, no animales que encarnen una enseñanza breve.'),
 ('Un periodista contrasta testimonios de un suceso ocurrido ayer.','No se describe una noticia, sino un poema narrativo de hazañas heroicas situado en un pasado de fundación.'),
 ('La voz expresa únicamente sentimientos íntimos sin narrar acciones.','La obra narra travesías, pruebas y fundación de una ciudad; no corresponde a expresión exclusivamente lírica sin acción.'),[text('Descripción de una obra ficticia','Un extenso poema narra las travesías de Arén, héroe de un pueblo imaginario. Tras enfrentar fuerzas sobrenaturales y proteger a su comunidad, conduce a los sobrevivientes a fundar una ciudad. Sus gestas simbolizan el origen y los valores colectivos del pueblo.')])
rev(S+'-287-03','En los dos versos, ¿qué tipo de rima hay entre “trabaja” y “tinaja”?',
 ('Consonante, porque coinciden vocales y consonantes desde la última vocal tónica: -aja.','Desde la a tónica de trabaja y tinaja se repite /aja/. Coinciden los sonidos vocálicos y consonánticos de la terminación.'),
 ('Asonante únicamente, porque solo coincide la vocal final.','Coinciden más sonidos que la a final: la secuencia completa desde la vocal tónica es aja en ambas palabras; por eso se clasifica como consonante.'),
 ('No hay rima porque las palabras comienzan con consonantes diferentes.','La rima se compara desde la última vocal acentuada, no desde el inicio de las palabras.'),
 ('Es un soneto porque ambos versos terminan en a.','Soneto designa una forma estrófica de catorce versos con organización específica; dos terminaciones no permiten identificarlo.'),[text('Versos originales','La abeja trabaja\njunto a la tinaja.')])
rev(S+'-23-02','En el cómic, ¿qué sentido produce que la planta formule la pregunta final?',
 ('La personificación hace visible la contradicción entre pedir ahorro y dejar el agua corriendo.','La planta habla como una persona y llama la atención sobre la llave que gotea. Ese recurso convierte al ser afectado en quien señala la incoherencia.'),
 ('Demuestra literalmente que las plantas poseen lenguaje humano.','La voz de la planta es un recurso de ficción. Su función crítica no constituye una afirmación biológica.'),
 ('Confirma que el personaje cerró correctamente la llave antes de irse.','Las gotas persisten en la última viñeta y la pregunta señala precisamente que la llave quedó abierta.'),
 ('Explica mediante datos técnicos cómo fabricar una llave.','El cómic no incluye instrucciones ni piezas de fabricación; construye una crítica por contraste entre palabras y acciones.'),[material('comic-agua')])
rev(S+'-287-06','¿Cuál es el tema central del cómic de la tarde en familia?',
 ('La distancia entre estar conectados por dispositivos y conversar con quienes están presentes.','La invitación a conversar contrasta con tres personas centradas en teléfonos; la frase final revela esa tensión entre conexión digital e intercambio cara a cara.'),
 ('La dificultad técnica de reparar un teléfono antiguo.','No se muestra una reparación ni un problema técnico; los teléfonos funcionan y concentran la atención de los personajes.'),
 ('La organización de una comida mediante una receta.','Hay una mesa, pero no se presentan alimentos ni pasos de cocina; el conflicto gira en torno a la conversación ausente.'),
 ('El beneficio inevitable de cualquier conversación en línea sobre una presencial.','El cómic ironiza sobre la falta de intercambio cercano; no presenta una comparación que pruebe superioridad inevitable de un tipo de conversación.'),[material('comic-pantallas')])
rev(S+'-287-07','¿Cómo contribuyen “ploc, ploc” y las gotas a construir el sentido del cómic del jardín?',
 ('Hacen perceptible que el desperdicio continúa después del consejo de ahorrar.','La onomatopeya imita el goteo y la imagen lo muestra. Ambas señales sostienen la contradicción entre el mensaje del personaje y su conducta.'),
 ('Indican que comenzó una tormenta que explica toda el agua.','Las gotas salen de la llave dibujada; no hay representación de lluvia que sustituya ese origen.'),
 ('Anuncian que la planta se aleja corriendo.','La onomatopeya acompaña el goteo de la llave, no pasos de la planta, que permanece en su maceta.'),
 ('Eliminan el contraste entre lo que se dice y lo que se hace.','Al mostrar agua desperdiciada refuerzan, en lugar de eliminar, el contraste con el consejo de ahorrar.'),[material('comic-agua')])
rev(S+'-287-08','¿Qué rasgos del texto permiten reconocer una noticia informativa?',
 ('Comunica un hecho reciente e identifica qué ocurrió, dónde y cuándo.','El inicio informa la apertura de una biblioteca el lunes en un lugar determinado y añade servicios. Esas respuestas organizan la entrega de información del suceso.'),
 ('Defiende como tesis central que todas las bibliotecas deben cobrar entrada.','El texto describe apertura y servicios gratuitos; no presenta esa tesis ni argumentos para cobrar.'),
 ('Relata la vida completa de una persona desde su nacimiento.','Una biografía organiza una trayectoria personal. Aquí se informa la apertura reciente de un servicio comunitario.'),
 ('Entrega una secuencia de órdenes para construir estanterías.','No hay instrucciones de fabricación; se comunican hechos y características de la nueva biblioteca.'),[text('Noticia ficticia para práctica','Nueva biblioteca abre en Las Lomas\nEl lunes, la municipalidad de Las Lomas inauguró una biblioteca junto a la plaza. El recinto ofrece préstamo gratuito y una sala infantil. Según informó su encargada, atenderá de martes a sábado.')])
rev(S+'-307-13','Un editorial sostiene: “Este diario considera necesario mejorar la frecuencia del transporte público. Las esperas prolongadas afectan el acceso al trabajo y al estudio; las autoridades deben priorizar una solución”. ¿Cuál es su función periodística predominante?',
 ('Formar opinión mediante una postura y razones sobre un asunto público.','El medio expresa una valoración y recomienda una acción, justificándola por efectos de las esperas. No se limita a informar horarios o describir un hecho.'),
 ('Entretener mediante un relato de ficción sin relación con asuntos públicos.','La postura se refiere a transporte y decisiones de autoridades; no desarrolla personajes ni una trama de ficción.'),
 ('Informar exclusivamente horarios sin emitir valoraciones.','Expresiones como considera necesario y deben priorizar son valoraciones y recomendaciones explícitas.'),
 ('Enseñar paso a paso cómo conducir un bus.','El texto argumenta sobre una política pública; no entrega un procedimiento técnico de conducción.'),[])
rev(S+'-28-05','En “Sofía visitó a Elena después de hablar con su hermana. Ella llevó el libro”, ¿qué problema de cohesión dificulta identificar quién llevó el libro?',
 ('El pronombre “ella” puede remitir a más de una persona mencionada.','Hay varios referentes femeninos disponibles y no se precisa el sujeto de la segunda oración. Repetir el nombre pertinente resolvería la ambigüedad.'),
 ('La palabra “libro” está en plural y no concuerda con “el”.','Libro está en singular y concuerda con el. Esa concordancia no es el problema del texto.'),
 ('No se puede usar un pronombre al comienzo de una oración.','Sí se puede si su referente es recuperable. El problema aquí es la ambigüedad, no la posición inicial del pronombre.'),
 ('El punto impide siempre relacionar dos oraciones consecutivas.','Las referencias pueden cruzar el límite de una oración. La relación se dificulta por los múltiples referentes posibles, no por la existencia del punto.'),[])
rev(S+'-287-12','Un estudiante escribe: “El curso quería observar las piezas. El museo estaba cerrado. Por eso, no pudo entrar”. Si quiere unir las dos primeras oraciones expresando el obstáculo, ¿qué corrección resuelve mejor la relación?',
 ('“El curso quería observar las piezas, pero el museo estaba cerrado”.','Pero introduce el contraste entre la intención de visitar y el obstáculo. La consecuencia posterior, no entrar, mantiene la coherencia.'),
 ('“El curso quería observar las piezas porque el museo estaba cerrado”.','Porque convierte el cierre en causa del deseo de observar, relación que no corresponde al obstáculo descrito.'),
 ('“El curso quería observar las piezas, por eso el museo estaba cerrado”.','La visita deseada no explica el cierre; el conector consecutivo establece una causalidad que el texto no sustenta.'),
 ('“El curso quería observar las piezas para que el museo estuviera cerrado”.','La finalidad propuesta invierte la intención del curso: quería acceder a las piezas, no provocar el cierre.'),[])
# Present an actual faulty connector, rather than only improving a coherent text.
ROWS[S+'-287-12']['q']='Un estudiante escribe: “El curso quería observar las piezas porque el museo estaba cerrado. Por eso, no pudo entrar”. ¿Qué corrección de la primera oración resuelve el problema de conexión entre la intención y el obstáculo?'
rev(S+'-307-10','¿Cómo se relaciona la tabla con la afirmación del breve informe?',
 ('La respalda: los préstamos aumentaron en 30 entre abril y mayo.','La tabla registra 120 y 150: 150 − 120 = 30. Esto apoya el aumento señalado, sin atribuirle una causa que no se ha investigado.'),
 ('La contradice porque en mayo hubo 30 préstamos menos.','La cifra de mayo es mayor que la de abril; la diferencia es positiva y no una disminución.'),
 ('Prueba que todos los estudiantes leyeron más libros en mayo.','La tabla informa préstamos totales, no lectura realizada ni datos por estudiante; no permite generalizar a cada persona.'),
 ('Demuestra que la cantidad de libros disponibles se duplicó.','Se registran préstamos, no inventario; además, pasar de 120 a 150 no es duplicar.'),[text('Informe de biblioteca','Los préstamos de libros aumentaron entre abril y mayo.'),table('Préstamos registrados',['Mes','Número de préstamos'],[['Abril',120],['Mayo',150]])])
rev(S+'-307-41','¿Qué revisión requiere la conclusión del informe a la luz de la tabla?',
 ('Cambiar “bicicleta” por “bus”, porque 25 es la mayor frecuencia.','El bus registra 25 respuestas frente a 18 de bicicleta y 12 de caminata. La conclusión debe corresponder al medio con mayor frecuencia.'),
 ('Mantenerla porque la bicicleta aparece primero en la tabla.','El orden de las filas no indica mayor uso; se deben comparar las cantidades.'),
 ('Cambiarla por “caminata”, porque 12 es el valor más pequeño.','La conclusión pregunta por el medio más usado, por lo que corresponde la mayor frecuencia, no la menor.'),
 ('Afirmar que todos usan bus porque es la categoría mayoritaria.','Tener la frecuencia más alta no implica unanimidad; 30 personas eligieron otros medios y bus tampoco supera la mitad de 55.'),[text('Conclusión de un informe','Entre las personas encuestadas, la bicicleta fue el medio más utilizado.'),table('Medio principal declarado',['Medio','Personas'],[['Bicicleta',18],['Bus',25],['Caminata',12]])])
rev(S+'-28-03','El texto afirma que las visitas crecieron cada mes. ¿Qué lectura del gráfico tabulado exige corregir esa afirmación?',
 ('Las visitas suben de marzo a abril, pero bajan de abril a mayo.','Los valores 200, 260 y 240 muestran aumento seguido de descenso. El total de mayo supera al de marzo, pero eso no equivale a crecer todos los meses.'),
 ('Las visitas disminuyen en ambos intervalos.','Entre marzo y abril suben de 200 a 260; solo el segundo intervalo disminuye.'),
 ('Mayo tiene menos visitas que marzo.','240 en mayo es mayor que 200 en marzo. El problema del texto es el supuesto crecimiento continuo.'),
 ('Abril y mayo tienen exactamente la misma cantidad.','La tabla indica 260 y 240, valores diferentes; no hay estabilidad entre esos meses.'),[text('Texto del informe','Durante los tres meses, las visitas crecieron cada mes.'),table('Registro de visitas',['Mes','Visitas'],[['Marzo',200],['Abril',260],['Mayo',240]])])
ROWS[S+'-28-03']['q']=ROWS[S+'-28-03']['q'].replace('gráfico tabulado','registro de la tabla')
rev(S+'-287-10','¿Qué afirmación del artículo queda respaldada por la tabla, sin convertir una asociación en prueba de causa?',
 ('En este registro, los grupos con más horas declaradas presentan mayor promedio de notas.','Los pares 1/4,8; 3/5,3; 5/5,8 muestran una asociación positiva en los grupos registrados. No controlan otras diferencias ni prueban causalidad por sí solos.'),
 ('Aumentar dos horas garantiza exactamente medio punto adicional a cualquier estudiante.','Promedios de grupos no garantizan efectos individuales ni aíslan la influencia de otras variables.'),
 ('Todos los estudiantes del grupo de cinco horas obtuvieron 5,8.','5,8 es un promedio; las notas individuales pueden ser diferentes.'),
 ('Las horas declaradas no guardan ninguna relación con los promedios observados.','En las tres filas se observa mayor promedio al aumentar las horas; negar toda relación ignora el patrón mostrado.'),[text('Artículo escolar','Una encuesta comparó horas semanales declaradas de estudio con el promedio de notas de tres grupos. Los datos permiten describir patrones, pero no se controlaron otras diferencias entre estudiantes.'),table('Datos simulados de la encuesta',['Horas semanales','Promedio de notas'],[[1,'4,8'],[3,'5,3'],[5,'5,8']])])
