from common import *
S='media-lengua'
rev(S+'-307-05','¿Qué razón sustenta clasificar como tragedia el texto dramático resumido?',
 ('El conflicto enfrenta al protagonista con límites éticos y culmina en una pérdida irreversible.','La decisión entre deberes incompatibles desencadena destrucción sin restitución del orden personal; esos rasgos sustentan una lectura trágica, más allá de que el asunto sea simplemente serio.'),
 ('Todo texto que contiene un diálogo pertenece necesariamente a la tragedia.','El diálogo es común a diversos géneros dramáticos; no distingue por sí solo tragedia de comedia o drama.'),
 ('El desenlace resuelve los malentendidos y restablece una convivencia feliz.','El resumen termina en pérdidas irreversibles, no en reconciliación mediante la resolución de un enredo.'),
 ('Su propósito central es caricaturizar tipos sociales mediante situaciones grotescas.','La descripción se centra en conflicto ético y consecuencias irreversibles; no ofrece la exageración cómica como principio dominante.'),[text('Síntesis de una obra original','Una gobernante debe elegir entre una ley de la ciudad y el deber de proteger a su hermano. Sostiene su decisión pese a las advertencias; el conflicto conduce a la muerte del hermano y a su propia ruina. La escena final deja expuesta la imposibilidad de reparar la pérdida.')])
rev(S+'-287-05','¿Qué razón permite clasificar la obra resumida como comedia de enredo?',
 ('Los equívocos provocan situaciones cómicas y su aclaración permite un desenlace conciliador.','La confusión de identidades organiza la acción y se resuelve al descubrirse el error; el efecto cómico y la reconciliación sostienen la clasificación.'),
 ('La sola presencia de personajes que hablan elimina toda posibilidad de tragedia.','Los diálogos son comunes a los géneros dramáticos y no permiten excluir tragedia ni identificar comedia.'),
 ('Un destino inevitable destruye al protagonista y vuelve imposible cualquier reparación.','En esta obra se aclaran las confusiones y se reconcilian los personajes; el desenlace no es una catástrofe irreversible.'),
 ('Toda obra situada en una casa pertenece a la misma forma dramática.','El lugar no determina el subgénero; importan la organización del conflicto, el tono y el desenlace.'),[text('Síntesis de una obra original','Dos hermanos llegan a una casa con invitaciones intercambiadas. Los anfitriones confunden sus identidades y cada intento de aclaración produce un nuevo malentendido cómico. Al descubrirse las invitaciones, todos reconocen el equívoco y celebran juntos.')])
rev(S+'-28-08','¿Qué progresión temática predomina en el fragmento?',
 ('De una afirmación general sobre humedales a funciones particulares que la desarrollan.','La primera oración presenta su importancia general; las siguientes precisan regulación del agua y hábitat como aspectos que desarrollan esa idea.'),
 ('De una anécdota personal a una conclusión autobiográfica.','No aparece una experiencia del hablante ni una historia personal; se exponen características del mismo tema.'),
 ('De una conclusión a la refutación de esa misma idea en cada oración.','Las oraciones posteriores apoyan y especifican la primera, en lugar de contradecirla.'),
 ('De temas independientes sin relación con una idea común.','Agua, inundaciones y hábitat se articulan como funciones de los humedales; no son temas inconexos en este texto.'),[text('Fragmento expositivo original','Los humedales cumplen diversas funciones ambientales. En relación con el agua, retienen parte de los excedentes y pueden amortiguar inundaciones. Como hábitat, ofrecen alimento y refugio a numerosas especies.')])
rev(S+'-28-16','¿Qué sentido adquiere la expresión final “¡Qué conectados estamos!” al relacionarla con las imágenes?',
 ('Es irónica: celebra una conexión que contrasta con la ausencia de conversación cara a cara.','La primera viñeta propone conversar; después cada persona mira un teléfono. El contraste entre elogio verbal e interacción ausente construye la ironía.'),
 ('Describe sin tensión que las tres personas mantienen una conversación presencial animada.','Las imágenes muestran miradas dirigidas a dispositivos y silencio, no una conversación presencial animada.'),
 ('Demuestra que las personas carecen de toda conexión tecnológica.','Los teléfonos están presentes y se usan. La ironía distingue conexión digital y comunicación cercana; no niega la primera.'),
 ('Funciona únicamente como una indicación técnica para cargar baterías.','La frase se integra al contraste narrativo entre intención y conducta, sin dar instrucciones de carga.'),[material('comic-pantallas')])
rev(S+'-287-06','En el cómic del jardín, ¿cómo contribuye “ploc, ploc” al sentido de la escena?',
 ('La onomatopeya hace persistente el goteo y refuerza la incoherencia del consejo de ahorrar.','La imitación del sonido, junto a las gotas, mantiene visible y audible en la lectura el desperdicio que contradice el mensaje inicial.'),
 ('La hipérbole demuestra que la llave produjo una inundación gigantesca.','El recurso imita un sonido y muestra gotas; no presenta una exageración de esa magnitud ni una inundación.'),
 ('La anáfora transforma el consejo en una explicación científica del agua.','La reiteración sonora no organiza aquí una explicación científica; representa el goteo de la llave dentro del relato.'),
 ('El recurso confirma que el personaje cumplió su propio consejo.','Las gotas siguen cayendo cuando se aleja. La onomatopeya refuerza la contradicción, no el cumplimiento.'),[material('comic-agua')])
rev(S+'-28-17','¿Cómo se caracteriza la relación emisor-receptor y el propósito del aviso?',
 ('La biblioteca comunica a sus usuarios un cambio temporal para orientar sus visitas.','La institución se identifica como emisora, se dirige a usuarios y entrega fechas y horario de reapertura; la finalidad predominante es informar.'),
 ('Un usuario exige a la biblioteca una indemnización mediante una queja privada.','El texto procede de la biblioteca y se dirige colectivamente a usuarios; no formula una queja ni una demanda de indemnización.'),
 ('Un narrador literario cuenta a sus personajes un episodio ficticio.','El aviso institucional presenta un cambio de atención con fechas, sin construir un mundo narrativo ni personajes.'),
 ('Una empresa persuade al público para adquirir una suscripción comercial.','No hay oferta, precio ni exhortación de compra; se informa una suspensión de atención y su término.'),[text('Aviso ficticio','Biblioteca del Barrio — A nuestros usuarios: el viernes 12 permaneceremos cerrados por inventario. Retomaremos la atención el sábado 13 a las 10:00. Los préstamos que vencen el viernes podrán devolverse el sábado sin recargo.')])
rev(S+'-307-09','¿Qué elemento del contexto de producción ayuda a interpretar el conflicto del fragmento?',
 ('Las expectativas sociales que restringían a las mujeres al espacio doméstico frente a sus aspiraciones educativas.','El deber de servir, el reproche y el cuaderno oculto vinculan el deseo de estudiar con límites de género del contexto descrito; no son detalles decorativos.'),
 ('La desaparición de toda diferencia de oportunidades educativas en la época representada.','El ocultamiento y el reproche muestran precisamente restricciones, no igualdad ya asegurada.'),
 ('Una innovación tecnológica que vuelve imposible escribir a mano.','No se plantea imposibilidad técnica: la protagonista escribe, pero esconde su cuaderno por presiones sociales.'),
 ('La falta de interés de la protagonista por aprender.','Acerca de estudiar, la acción de conservar y ocultar el cuaderno sugiere interés persistente pese al límite impuesto.'),[text('Contexto de producción de una obra ficticia','Relato didáctico situado en Chile a fines del siglo XIX, en un ambiente que asigna a las mujeres obligaciones domésticas y cuestiona sus aspiraciones de estudio. La situación representada no describe de igual manera a todas las mujeres del periodo.'),text('Fragmento original','—Los libros no te ayudarán a servir la mesa —dijo su tío. Ella guardó el cuaderno bajo el mantel. Mientras repartía los platos, siguió resolviendo en silencio la pregunta que había dejado a medias.')])
rev(S+'-287-08','¿Qué relación entre el fragmento poético y su contexto de producción resulta pertinente?',
 ('El humo, la sirena y el horario impuesto representan la experiencia de trabajo urbano industrial del contexto indicado.','Esas imágenes vinculan espacio fabril y disciplina del tiempo. La interpretación conecta marcas concretas del poema con el contexto, sin reducirlo a una descripción literal exhaustiva.'),
 ('Las imágenes permiten ignorar por completo el contexto porque solo nombran naturaleza intacta.','Humo de fábrica, sirena y turno son señales urbanas e industriales; no corresponden únicamente a un paisaje natural sin intervención.'),
 ('La presencia de una sirena convierte necesariamente el poema en un mito marino.','En el contexto fabril, la sirena marca el inicio del turno. La lectura mitológica pasa por alto esa pista y el sentido del resto de los versos.'),
 ('El poema prueba estadísticamente las condiciones de todos los trabajadores del país.','Un fragmento literario representa una experiencia mediante imágenes; no es una muestra estadística ni permite esa generalización.'),[text('Contexto didáctico','Poema original que recrea una voz obrera en una ciudad en expansión industrial durante la primera mitad del siglo XX; no se atribuye a un autor histórico.'),text('Fragmento original','La fábrica dibuja humo sobre el amanecer.\nLa sirena divide la mañana en turnos.\nGuardo mi reloj: otro decide la hora\nen que mis manos vuelven a ser mías.')])
rev(S+'-307-10','¿Qué tema de la literatura contemporánea desarrolla principalmente el fragmento?',
 ('La soledad y la incomunicación aun cuando existe contacto cotidiano con otras personas.','La protagonista recibe mensajes y vive acompañada, pero no logra compartir su pérdida. El contraste expresa falta de comunicación significativa, más que ausencia física de otros.'),
 ('La representación heroica de un origen colectivo celebrado sin conflicto.','No se narran gestas fundacionales ni una celebración colectiva; el foco está en una experiencia íntima de aislamiento.'),
 ('La literatura como reflexión explícita sobre el proceso de escribir una novela.','El fragmento no habla de escritura ni del propio relato; representa incomunicación afectiva.'),
 ('Una explicación ordenada de leyes naturales que elimina toda experiencia subjetiva.','El texto se centra en recuerdos, pérdida y vínculos humanos; no expone leyes naturales ni suprime la subjetividad.'),[text('Fragmento narrativo original','En la ciudad nueva recibía decenas de mensajes. Contestaba con el mismo dibujo sonriente. Cuando intentaba hablar de lo que había perdido al partir, alguien cambiaba de tema. En el departamento compartido nunca estaba sola, pero no encontraba a quién contarle su día.')])
rev(S+'-287-09','¿Qué tema contemporáneo se construye en este fragmento sobre una comunidad desplazada por la sequía?',
 ('La incomunicación humana, expresada en la dificultad de compartir experiencias aun reunidos.','La sequía sitúa el desplazamiento, pero las respuestas que no se encuentran y el regreso al silencio focalizan la imposibilidad de una comunicación compartida.'),
 ('La literatura como tema de sí misma, mediante un autor que comenta cómo escribe.','No hay reflexión sobre creación literaria ni un autor comentando su obra; el conflicto representado es entre personas que no logran comunicarse.'),
 ('La certeza de que una explicación única permite abarcar toda la realidad.','El fragmento no ofrece una explicación total; muestra experiencias desconectadas y dificultad para comprenderse.'),
 ('La desaparición del aislamiento por el solo hecho de vivir en un mismo lugar.','Aunque se reúnen físicamente, sus palabras no se encuentran y cada uno vuelve al silencio; esa desaparición queda contradicha.'),[text('Fragmento original','La sequía los había llevado a la misma ciudad. Se reunían cada domingo para recordar el valle. Uno hablaba de su casa; otro respondía con la historia de un trabajo perdido, sin haberlo escuchado. Las frases se cruzaban como calles sin esquina. Al despedirse, cada cual regresaba a su propio silencio.')])
r=rev(S+'-307-22','En el mensaje de la campaña, ¿cómo contribuye la oración condicional al propósito comunicativo?',
 ('Busca persuadir: presenta el ahorro de agua como condición para disponer de ella y motivar una conducta.','Si reducimos introduce una condición vinculada a un resultado deseable. Junto con la exhortación final, orienta a que el receptor actúe; no solo describe un dato.'),
 ('Solo informa una fecha pasada sin intentar influir en la conducta.','El mensaje formula una condición futura y una invitación a actuar; no se organiza como un registro de fecha pasada.'),
 ('Expresa dos alternativas equivalentes que vuelven innecesaria cualquier acción.','La relación condicional vincula una acción con un beneficio; la exhortación recomienda realizarla, no la presenta como irrelevante.'),
 ('Demuestra que el resultado se producirá aunque nadie cambie su consumo.','La estructura si… establece dependencia entre reducción y disponibilidad; no asegura el mismo resultado sin cambios.'),[text('Mensaje original de campaña escolar','Si reducimos el consumo innecesario de agua, tendremos más disponible para las necesidades del barrio. Cierra la llave mientras te cepillas los dientes y súmate al cuidado del agua.')])
r['indicatorId']='1-0-1'
rev(S+'-307-43','¿Con qué tipo de mundo literario se relaciona la situación construida por el anuncio audiovisual?',
 ('Maravilloso: un hecho imposible se acepta como normal dentro del mundo del anuncio.','El dragón habla y reparte el producto sin causar extrañeza a los personajes. La aceptación de lo sobrenatural permite relacionarlo con un mundo maravilloso.'),
 ('Realista: todos los hechos obedecen a las posibilidades del mundo cotidiano.','Un dragón parlante rompe las posibilidades ordinarias. El tratamiento natural del hecho no lo vuelve realista.'),
 ('Fantástico: se sostiene una vacilación entre explicación natural y sobrenatural.','Los personajes no dudan ni buscan explicar lo sucedido como sueño o ilusión; el anuncio normaliza la presencia del dragón.'),
 ('Documental científico: se aporta evidencia verificable de la existencia de dragones.','La pieza es publicitaria y construye una ficción; no presenta investigación ni comprobación científica.'),[text('Descripción de un anuncio ficticio','En un anuncio televisivo de cereales, un dragón entra a la cocina, conversa con una familia y reparte el desayuno. Nadie se sorprende de su presencia ni de que hable; continúan desayunando mientras aparece el nombre del producto.')])
