"""Adaptaciones editoriales de EM-L 2023. Textos de práctica originales."""
ITEMS = []

def text(title, content):
    return {'kind': 'text', 'title': title + ' · texto original de práctica', 'text': content}

def figure(title, asset, alt):
    return {'kind': 'figure', 'title': title + ' · ilustración original de práctica', 'asset': asset, 'alt': alt}

def add(n, page, indicator, kind, question, options, answer, reasons, stimuli=(), note='', alignment=''):
    assert len(options) == len(reasons) == 4
    ITEMS.append(dict(number=n, page=page, indicatorId=indicator, questionType=kind, q=question,
                      o=options, a=answer, explanations=reasons, stimulus=list(stimuli),
                      adaptation=note, alignment=alignment))

add(1,2,'2-0-1','selección de fuentes',
    'Un curso investiga cómo el contexto histórico influyó en el teatro del Siglo de Oro. Ya reunió muchos enlaces. ¿Qué actividad permite seleccionar primero las fuentes pertinentes?',
    ['Registrar autor y editorial de todos los enlaces y elegir el que tenga la ficha más extensa.',
     'Revisar títulos, introducciones e ideas centrales y contrastar su pertinencia con la pregunta de investigación.',
     'Ordenar las fuentes por fecha de publicación y elegir automáticamente las más recientes.',
     'Resumir íntegramente todos los documentos antes de comprobar si responden la pregunta.'],1,
    ['Los datos bibliográficos permiten identificar una fuente, pero la extensión de su ficha no indica que explique la relación entre teatro e historia.',
     'La lectura exploratoria permite detectar qué aporta cada fuente a la pregunta antes de invertir tiempo en una lectura detallada. Luego corresponde comprobar su fiabilidad.',
     'La actualidad puede ser un criterio útil, pero no garantiza pertinencia. Una fuente reciente puede no abordar la relación entre teatro y contexto que el curso investiga.',
     'El resumen sirve para procesar fuentes seleccionadas. Resumirlo todo primero retrasa la decisión y dedica esfuerzo a documentos posiblemente irrelevantes.'],
    note='Se conserva la selección de fuentes y se separa la pertinencia temática de la fiabilidad y del registro bibliográfico.',
    alignment='Modela una decisión concreta del proceso de investigación: seleccionar información según una pregunta delimitada.')

add(2,3,'2-0-3','retroalimentación de escritura',
    'Una estudiante debe transformar el diálogo en estilo indirecto, pero copia las mismas intervenciones entre comillas. ¿Qué orientación le permite realizar la transformación?',
    ['Conservar las comillas y agregar dos puntos antes de cada intervención.',
     'Describir únicamente la apariencia de las personas que conversan.',
     'Pasar todo el relato a primera persona para que cada personaje cuente su experiencia.',
     'Contar con la voz del narrador lo que cada personaje dijo, ajustando personas y referencias temporales al nuevo relato.'],3,
    ['Las comillas y los dos puntos pueden introducir discurso directo. Añadirlos no integra las palabras del personaje en la voz del narrador.',
     'Describir el aspecto de los personajes cambia el contenido y no resuelve cómo comunicar indirectamente sus palabras.',
     'Cambiar la persona del narrador no determina el estilo del discurso. Un narrador en primera persona también puede citar directamente o referir indirectamente palabras.',
     'La orientación explicita la operación: por ejemplo, Paula dijo que al día siguiente llevaría el libro. La voz narradora presenta las palabras y ajusta las referencias.'],
    [text('Diálogo', 'Paula dijo: «Mañana traeré el libro».\nDiego respondió: «Lo leeremos aquí».')],
    note='La viñeta se sustituye por un diálogo propio completo. Se explicitan las transformaciones de persona, tiempo y deícticos sin exigir cambios mecánicos en todo contexto.',
    alignment='Selecciona retroalimentación comprensible y conceptualmente precisa sobre una dificultad de escritura.')

add(3,4,'2-0-0','estrategia de interpretación',
    'El curso lee «Buscar un verso». ¿Qué orientación ayuda mejor a interpretar la imagen del caminante en relación con la escritura?',
    ['Determinar una interpretación exclusivamente a partir del contexto histórico, sin contrastarla con las imágenes del poema.',
     'Enumerar las figuras literarias sin relacionarlas con lo que expresa el poema.',
     'Sustituir cada palabra por un sinónimo y considerar terminada la interpretación.',
     'Relacionar el título con las acciones de caminar y extraviarse, y fundamentar qué sugieren sobre escribir.'],3,
    ['El contexto puede enriquecer una lectura, pero no sustituye las relaciones y evidencias del propio poema. La interpretación de una imagen necesita volver a sus versos.',
     'Reconocer recursos puede apoyar la lectura, pero una lista de nombres no explica qué sentido construyen en este poema.',
     'Aclarar vocabulario facilita la comprensión literal. La interpretación exige relacionar las imágenes con el tema y justificar la lectura.',
     'Caminar sin un mapa y encontrar una voz después de extraviarse sugieren una búsqueda creativa incierta. La estrategia exige sostener esa lectura con el texto.'],
    [text('Buscar un verso','Salgo sin mapa por la página.\nCada palabra abre una calle.\nA veces me extravío;\nsolo entonces encuentro mi voz.')],
    note='Se reemplaza el poema fuente por uno original y se mantiene la lectura de imágenes vinculadas al tema, sin reducirla a identificar nombres de figuras.',
    alignment='Elige una estrategia de comprensión que relaciona título, imágenes y evidencias del poema.')

add(4,5,'2-0-0','lectura de un autorretrato',
    'Los estudiantes dicen que las oraciones de «Autorretrato en fragmentos» no cuentan una historia ordenada. ¿Qué pregunta ayuda a construir su sentido global?',
    ['¿Qué imagen de una persona forman, en conjunto, sus hábitos, recuerdos y contradicciones, y cómo se relaciona con el título?',
     '¿Qué persona gramatical utiliza el narrador en las distintas oraciones?',
     '¿Qué recuerdos se mencionan expresamente y qué hábitos tiene la persona?',
     '¿Cuál de las experiencias narradas se parece más a una experiencia personal del lector?'],0,
    ['El título orienta a leer los rasgos dispersos como una representación de identidad. Relacionarlos permite comprender una organización que no es cronológica.',
     'Reconocer la primera persona ayuda a describir la voz, pero no resuelve por sí solo cómo se relacionan los fragmentos con una identidad.',
     'Localizar recuerdos y hábitos recupera información explícita. Falta relacionar esas piezas para construir el sentido del autorretrato.',
     'Conectar con experiencias propias puede motivar, pero esta pregunta aislada no orienta a explicar la organización y el sentido global del fragmento.'],
    [text('Autorretrato en fragmentos','Guardo boletos de viajes que no recuerdo. Me incomodan los relojes, pero llego antes que todos. Aprendí a nadar tarde. Aún conservo el dibujo de una casa en la que nunca viví.')],
    note='Se usa un autorretrato original; la pregunta permite interpretar la relación entre fragmentación e identidad sin calificar las oraciones como necesariamente incoherentes.',
    alignment='Orienta la comprensión global relacionando información del texto con un elemento organizador, su título.')

add(5,6,'2-0-3','explicación de un microcuento',
    'Un estudiante afirma que «El regreso» no puede ser un cuento porque tiene solo dos oraciones. ¿Qué explicación responde con mayor precisión?',
    ['Es cuento solo si quien lo lee conoce previamente una novela que explique sus personajes.',
     'Es cuento porque cualquier enunciado breve tiene obligatoriamente narrador omnisciente.',
     'La brevedad no elimina el relato: alguien vuelve a un lugar y encuentra una situación inesperada, aunque muchos antecedentes quedan implícitos.',
     'Es cuento porque todas las narraciones alteran obligatoriamente el orden gramatical de las palabras.'],2,
    ['El texto permite reconocer una situación y un cambio sin exigir una novela previa. Las inferencias del lector no requieren esa referencia externa.',
     'La extensión no determina cuánto sabe un narrador. En este caso no se presentan los pensamientos de todos los personajes.',
     'El regreso y el reconocimiento imposible construyen una secuencia narrativa condensada. Un microcuento puede dejar antecedentes y resolución implícitos; no necesita desplegar explícitamente todas las fases de una trama.',
     'El hipérbaton no es requisito de los cuentos. La condición narrativa depende de la configuración de acontecimientos, no de una inversión gramatical obligatoria.'],
    [text('El regreso','Volvió al pueblo que había desaparecido bajo el agua. Al abrir la puerta, su madre le preguntó por qué llegaba tan tarde.')],
    note='Se sustituye el microcuento por un relato original y se corrige la generalización de que todo microcuento debe presentar explícitamente conflicto, clímax y desenlace.',
    alignment='Distingue una explicación docente precisa ante una confusión entre extensión y carácter narrativo.')

add(6,7,'2-0-6','enfoque comunicativo cultural',
    'Un curso compara el conflicto de una tragedia antigua con un debate actual y presenta su interpretación a otra clase, apoyándose en pasajes de la obra. ¿Por qué esta actividad integra el enfoque comunicativo cultural?',
    ['Porque acumula nombres de autores aunque no se interpreten las obras.',
     'Porque mejora la fluidez de la exposición, independientemente del sentido de la obra y de sus destinatarios.',
     'Porque relaciona una obra con contextos culturales y comunica una interpretación fundamentada a destinatarios concretos.',
     'Porque comprueba únicamente que se memorizaron las definiciones de los géneros dramáticos.'],2,
    ['La actividad exige interpretar y comunicar, no solo reunir información enciclopédica. Nombrar autores por sí solo no integra esos propósitos.',
     'La fluidez puede desarrollarse, pero esa explicación deja fuera la interpretación cultural y la situación comunicativa que dan propósito a la actividad.',
     'Se articulan la comprensión cultural e histórica de la literatura y el uso del lenguaje en una situación con propósito, interlocutores y evidencias.',
     'Recordar conceptos puede servir como apoyo, pero la tarea exige aplicarlos para interpretar y comunicar, no solo comprobar su memorización.'],
    note='Se añade un destinatario y la exigencia de evidencia textual para hacer observables las dimensiones comunicativa y cultural de la actividad.',
    alignment='Relaciona el diseño de una actividad con los énfasis curriculares de la asignatura.')

add(7,8,'2-0-2','metáfora visual',
    'La docente utiliza la ilustración «Antes de salir» para explicar cómo una imagen puede construir una metáfora. ¿Qué relación debe modelar?',
    ['La descripción literal de una familia que se desplaza con su equipaje.',
     'La sustitución de una persona por su maleta como relación de parte y todo.',
     'La repetición visual de varias personas para representar una multitud.',
     'La asociación de la enorme sombra con una amenaza que domina la experiencia de los personajes.'],3,
    ['Reconocer personas y equipaje describe lo representado. Falta explicar la asociación figurada que introduce la sombra desproporcionada.',
     'La maleta aparece junto a las personas y no las sustituye. Además, objeto y propietario no son una relación literal de parte y todo.',
     'Se ven tres personas diferenciadas, no una repetición destinada a construir una multitud. Esa lectura no explica la sombra dominante.',
     'La desproporción entre la sombra con forma de garra y las personas pequeñas convierte la amenaza en una presencia visible. Esa relación permite explicar la metáfora visual.'],
    [figure('Antes de salir','media-310-sombra.svg','Tres personas con una maleta se agrupan delante de una puerta. Por encima se extiende una gran sombra con forma de garra, mucho mayor que ellas; no se muestra un animal que la proyecte.')],
    note='La imagen de Shaun Tan se reemplaza por una ilustración didáctica propia. Se conserva la interpretación de una sombra amenazante sin atribuir al original los trazos nuevos.',
    alignment='Usa una representación visual para hacer comprensible un recurso literario mediante una relación explícita.')

add(8,9,'2-0-0','pregunta inferencial',
    '¿Cuál de estas preguntas exige inferir información al leer «La llave»?',
    ['¿Por qué la narradora relaciona el final de sus juegos con el momento en que recibe la llave?',
     '¿Qué objeto le dejó la madre a la narradora?',
     '¿Qué opinas de que los niños ayuden en las tareas del hogar?',
     '¿A qué hora dice el texto que salía la madre?'],0,
    ['El texto no explica directamente esa relación: hay que vincular la llave, el cuidado del hermano y el cambio en la vida cotidiana para inferir nuevas responsabilidades.',
     'La llave se menciona expresamente. Identificar ese objeto recupera información literal, sin establecer una relación implícita.',
     'Solicita una valoración del lector. Puede promover discusión, pero no exige por sí misma inferir el sentido de un hecho del relato.',
     'La expresión antes del amanecer está explícita. Recuperarla corresponde a una pregunta de localización de información.'],
    [text('La llave','Mamá empezó a salir antes del amanecer. Dejó una llave junto a mi cuaderno: «Si tu hermano despierta, calienta el pan». Esa mañana guardé las bolitas en el cajón y no volví a buscarlas.')],
    note='Se reemplaza el relato por uno original y se distinguen una inferencia fundamentada, dos recuperaciones literales y una valoración personal.',
    alignment='Selecciona una pregunta que desarrolla comprensión inferencial a partir de indicios relacionados.')

add(9,10,'2-1-1','análisis de error narrativo',
    'Un estudiante clasifica el fragmento como discurso indirecto porque está escrito en tercera persona. ¿Qué distinción conviene reforzar para reconocer el indirecto libre?',
    ['La diferencia entre una narración larga y una breve, según la cantidad de párrafos.',
     'La diferencia entre un personaje principal y uno secundario, según cuántas veces aparece su nombre.',
     'La persona gramatical del narrador y la incorporación de la voz o pensamiento del personaje son dimensiones distintas.',
     'La narración en tercera persona siempre reproduce las palabras del personaje mediante comillas.'],2,
    ['La extensión no permite distinguir estos modos de representar el discurso. La dificultad observada está en atribuir las voces del fragmento.',
     'La importancia del personaje en la trama no determina el modo en que aparecen sus pensamientos. Contar nombres no resuelve la confusión.',
     'La tercera persona se combina aquí con la exclamación y la valoración de Elena, sin comillas ni dijo que. Hay que reconocer esa entrada de su voz en el relato.',
     'Las comillas son características de una reproducción directa cuando se emplean con esa función. La tercera persona no obliga a utilizarlas ni identifica por sí sola un estilo.'],
    [text('La espera','Elena miró el reloj de la estación. ¡Otra vez llegaba tarde ese tren! Tendría que explicárselo todo al director.')],
    note='Se usa un fragmento original con marcas inequívocas de indirecto libre; se evita equiparar persona gramatical y modo de representación del discurso.',
    alignment='Identifica el error conceptual de un estudiante para orientar la retroalimentación.')

add(10,11,'2-2-0','indicador de evaluación',
    'El objetivo es interpretar cómo el giro satírico de este epigrama cuestiona la conducta de un personaje. ¿Qué desempeño evidencia mejor ese aprendizaje?',
    ['Reconoce la estructura breve y describe su distribución en versos.',
     'Identifica los personajes y resume literalmente lo que hacen.',
     'Explica cómo la contradicción entre escuchar a otros y amplificar la propia voz construye una crítica a la falta de escucha.',
     'Localiza palabras relacionadas con sonido y clasifica su categoría gramatical.'],2,
    ['Describir la brevedad y la distribución identifica propiedades formales, pero no muestra que se comprenda el efecto satírico ni la conducta cuestionada.',
     'Resumir acciones acredita comprensión literal. Falta explicar por qué su contradicción produce una crítica.',
     'El desempeño relaciona una evidencia concreta, la contradicción del personaje, con el efecto satírico y la crítica que produce.',
     'El campo léxico del sonido puede aportar evidencia, pero clasificar palabras sin relacionarlas con la contradicción no muestra el efecto satírico.'],
    [text('El gran oyente','Prometió escuchar al barrio.\nInstaló un gran altavoz\npara oírse todo el día.')],
    note='Se aporta un epigrama original y se precisa el objetivo evaluado. No se trata la sátira como rasgo obligatorio de todos los epigramas.',
    alignment='Propone un desempeño observable alineado con el análisis de un recurso poético.')

add(11,12,'2-2-1','retroalimentación formativa',
    'Al revisar este borrador argumentativo, la docente observa que el segundo párrafo no desarrolla la pregunta inicial. ¿Qué devolución ofrece evidencia y un siguiente paso útil?',
    ['Tu texto necesita coherencia. Mejora todo antes de entregarlo nuevamente.',
     'Agrega un conector al inicio del segundo párrafo sin cambiar sus ideas.',
     'Primero preguntas si la biblioteca debe abrir los sábados; después describes el uniforme. Sustituye ese párrafo por una razón sobre el horario y explica cómo respalda tu postura.',
     'Copia el primer párrafo otra vez para que ambos párrafos traten el mismo tema.'],2,
    ['Nombra un problema general, pero no localiza la evidencia ni propone una operación concreta para resolverlo.',
     'Un conector no crea una relación argumentativa entre contenidos desvinculados. Antes hay que revisar la pertinencia de las ideas.',
     'La devolución señala el desajuste entre ambos párrafos y propone revisar la razón en función de la postura. Permite que el estudiante actúe sobre su propio escrito.',
     'Repetir la pregunta inicial no desarrolla un argumento. La unidad temática debe construirse haciendo avanzar la justificación.'],
    [text('Borrador de una propuesta','¿Debería abrir la biblioteca escolar los sábados? Considero que sí.\nEl uniforme del colegio tiene pantalón azul y una chaqueta gris. El año pasado cambió su diseño.')],
    note='Se reemplaza el ensayo por un borrador propio con una digresión clara; la retroalimentación diferencia pertinencia de las ideas y uso superficial de conectores.',
    alignment='Evalúa una intervención formativa a partir de evidencia concreta de un desempeño escrito.')

add(12,13,'2-1-1','retroalimentación de lectura',
    'Un estudiante afirma que el poema solo presenta un felino real. ¿Qué pregunta lo ayuda a interpretar la relación metafórica central?',
    ['¿Qué nombre recibe la figura literaria que aparece en el primer verso?',
     '¿Qué acciones realiza el animal, consideradas solo en su sentido literal?',
     '¿Qué relación se establece entre el tigre que devora y el tiempo que hace desaparecer días y recuerdos?',
     '¿Qué sentimientos expresa el hablante, sin examinar la relación entre tiempo y tigre?'],2,
    ['Solicita una etiqueta antes de ayudar a construir la relación de sentido. Si la dificultad es la lectura literal, nombrar la figura no explica su funcionamiento.',
     'Describir acciones literales puede ser un primer paso, pero la intervención debe vincularlas con el tiempo para superar la dificultad detectada.',
     'La pregunta guía hacia la asociación entre devorar y hacer desaparecer. Permite explicar por qué el tiempo se presenta como un tigre y qué sentido produce esa elección.',
     'Los sentimientos importan en la interpretación global, pero omitir la relación entre tiempo y tigre deja sin resolver el problema conceptual observado.'],
    [text('El tiempo','El tiempo es un tigre en mi casa:\ndevora los días del calendario,\narrastra al patio los nombres\ny deja sus huellas en mis manos.')],
    note='Se reemplaza el poema por uno original con una metáfora sostenida, evitando exigir que una comparación inicial descarte la presencia de otras figuras.',
    alignment='Reconoce una intervención para superar una interpretación literal mediante evidencia textual.')

add(13,14,'2-2-0','evaluación de lectura contextual',
    'El objetivo es relacionar los valores de un relato medieval con su contexto de producción. ¿Qué respuesta del estudiante evidencia ese aprendizaje?',
    ['Enumera las armas del caballero sin explicar su función en el relato.',
     'Juzga al personaje exclusivamente según las normas políticas actuales, sin considerar el contexto presentado.',
     'Relaciona la búsqueda del favor del rey y del honor familiar con un orden social que valora los vínculos de fidelidad y reconocimiento público.',
     'Reconstruye el orden de las acciones del caballero sin explicar su sentido social.'],2,
    ['La enumeración recupera información del mundo representado, pero no la relaciona con valores ni con el contexto histórico.',
     'Comparar con el presente puede enriquecer una lectura posterior. El objetivo aquí exige primero comprender el marco de valores del contexto presentado.',
     'La respuesta vincula las acciones del personaje con fidelidad, honor y reconocimiento social. Integra evidencia narrativa y contexto sin afirmar que todos los grupos medievales pensaban igual.',
     'Ordenar acciones muestra comprensión de la secuencia narrativa. El objetivo requiere además relacionarlas con valores y contexto de producción.'],
    [text('Caballero desterrado','En un relato ambientado en un orden de vínculos entre señor y vasallo, un caballero desterrado entrega parte de sus victorias al rey. Aspira a recuperar su favor y el honor público de su familia.')],
    note='Se usa una síntesis narrativa didáctica identificada como tal; se evita afirmar que el Cid fue realmente traidor o que una calumnia demuestra deslealtad.',
    alignment='Identifica evidencia evaluable que relaciona valores de la obra y contexto histórico.')

add(14,14,'2-2-0','evaluación de personajes',
    'El objetivo es comprender cómo las relaciones de ayuda y oposición entre personajes hacen avanzar un conflicto. ¿Qué desempeño es el más directo para evaluarlo?',
    ['Explica quién ayuda u obstaculiza la meta de la protagonista y cómo esas acciones cambian el conflicto.',
     'Clasifica a los personajes como principales y secundarios por su presencia en el relato.',
     'Describe los rasgos psicológicos de la protagonista sin analizar sus vínculos con otros personajes.',
     'Ordena los acontecimientos del relato sin explicar quién ayuda u obstaculiza la meta.'],0,
    ['Vincula relaciones entre personajes, acciones y cambios del conflicto, que son precisamente los componentes del objetivo evaluado.',
     'La jerarquía de personajes describe su importancia, pero no explica directamente las relaciones de ayuda y oposición ni su efecto sobre el conflicto.',
     'La caracterización psicológica aporta a la comprensión, pero el desempeño descrito deja fuera las relaciones y acciones exigidas por el objetivo.',
     'Reconstruir la secuencia acredita comprensión de hechos. Falta explicar la incidencia de las relaciones entre personajes en su desarrollo.'],
    note='Se acota el objetivo a relaciones de ayuda y oposición para evitar que varias alternativas igualmente interpretativas satisfagan la misma consigna.',
    alignment='Selecciona un indicador observable coherente con el objetivo de comprensión de relaciones narrativas.')

add(15,15,'0-0-1','interpretación de una imagen poética',
    'En «Taller de palabras», ¿qué sentido adquiere la imagen de forcejear con una puerta?',
    ['La decisión de abandonar la escritura para dedicarse a reparar una vivienda.',
     'El esfuerzo de buscar una expresión poética que se resiste a aparecer.',
     'La certeza de que toda inspiración llega sin trabajo ni dificultades.',
     'La nostalgia por una casa descrita como el único tema posible del poema.'],1,
    ['El contexto habla de una frase y un verso. No presenta un cambio de oficio ni una reparación material como asunto del poema.',
     'La frase que no abre y el forcejeo relacionan escribir con un esfuerzo de acceso. El verso que finalmente entra resuelve esa búsqueda de expresión.',
     'Los nudillos cansados y el forcejeo destacan resistencia y trabajo. Esa evidencia contradice una inspiración presentada como inmediata y sin esfuerzo.',
     'La puerta forma parte de una imagen de la creación poética; no hay recuerdos de una vivienda que sostengan una lectura centrada en nostalgia doméstica.'],
    [text('Taller de palabras','La frase era una puerta cerrada.\nForcejeé hasta cansarme los nudillos.\nAl alba, un verso cruzó el umbral.')],
    note='Se sustituye el fragmento por un poema original que permite justificar el sentido de la imagen mediante sus propias palabras.',
    alignment='Interpreta el efecto y sentido de una imagen figurada en el poema.')

add(16,16,'0-0-1','efecto de la anáfora',
    '¿Qué efecto produce la repetición de «Vuelve» al comienzo de los versos de «Regresos»?',
    ['Presenta cada recuerdo como un hecho desconectado de los demás.',
     'Establece una sucesión cronológica precisa mediante fechas.',
     'Contrapone explícitamente dos opiniones incompatibles del hablante.',
     'Da ritmo e insiste en la reaparición de distintas experiencias en la memoria.'],3,
    ['La repetición une las imágenes por una misma acción de regreso. No las aísla, aunque cada verso evoque una experiencia distinta.',
     'No se entregan fechas ni un orden temporal preciso. La organización se apoya en la recurrencia del recuerdo.',
     'Los versos no desarrollan dos opiniones opuestas. El recurso dominante suma evocaciones bajo una misma estructura.',
     'La anáfora repite una palabra al inicio de unidades sucesivas. Aquí produce ritmo y refuerza que voces, olores y sensaciones vuelven a la memoria.'],
    [text('Regresos','Vuelve la voz del patio.\nVuelve el olor del pan.\nVuelve la lluvia antigua\na golpear mi ventana.')],
    note='Se aporta un poema original cuyo efecto de reiteración está fundamentado; se evita afirmar que una figura tiene el mismo efecto en cualquier poema.',
    alignment='Distingue el efecto contextual de una figura, además de reconocer su nombre.')

add(17,17,'0-0-2','efecto del narrador',
    '¿Qué aporta la primera persona plural a la narración de «La guardia»?',
    ['Un conocimiento completo de los pensamientos de todas las personas del pueblo.',
     'La perspectiva de alguien que observa desde fuera sin participar en las acciones.',
     'La reproducción literal del diálogo de quienes esperan en la estación.',
     'El testimonio de un integrante del grupo sobre sus acciones y motivos compartidos.'],3,
    ['La voz cuenta lo que su grupo hace y pretende. Usar nosotros no concede conocimiento ilimitado de la mente de los demás.',
     'Las formas encendíamos y temíamos incluyen al narrador en el grupo que actúa; no corresponden a un observador ajeno a los hechos.',
     'El fragmento no cita intervenciones mediante diálogo. La primera persona plural expresa participación, no discurso directo.',
     'El narrador se incluye en la acción y comunica desde dentro el temor y el propósito del grupo. Esto no garantiza una verdad objetiva sobre todo el mundo narrado.'],
    [text('La guardia','Encendíamos las lámparas antes de que oscureciera. Temíamos que el tren pasara de largo y queríamos que nuestros hijos distinguieran la estación desde sus ventanas.')],
    note='Se reemplaza el relato por uno original y se distingue acceso a motivos del grupo de certeza absoluta u omnisciencia.',
    alignment='Relaciona grado de participación y perspectiva narrativa con su efecto en el relato.')

add(18,17,'0-0-2','focalización narrativa',
    '¿Qué evidencia permite clasificar como focalización cero la narración de «La carta»?',
    ['La mención de una carta como objeto central de la acción.',
     'El acceso a pensamientos de ambos personajes y a un hecho que ninguno conoce.',
     'El uso de tercera persona, que siempre implica conocimiento ilimitado.',
     'La descripción exclusiva de movimientos observables desde el exterior.'],1,
    ['El objeto del relato no determina la focalización. La clasificación depende de cómo se distribuye la información respecto de los personajes.',
     'La voz sabe qué teme Ana, qué cree Luis y qué ocurrió con la carta sin que ellos lo sepan. Su información no queda restringida a la perspectiva de un solo personaje.',
     'Una narración en tercera persona también puede limitarse a la percepción de un personaje. La persona gramatical, por sí sola, no demuestra focalización cero.',
     'El fragmento comunica pensamientos y conocimiento no observable, por lo que no se limita a registrar gestos desde fuera.'],
    [text('La carta','Ana temía que Luis hubiera leído la carta. Luis, en cambio, estaba convencido de que ella la había quemado. Ninguno sabía que el viento la había llevado hasta el patio del vecino.')],
    note='Reformulación conceptual: el acceso a una sola interioridad no basta para probar focalización cero. El nuevo relato incluye dos interioridades y un hecho desconocido por ambos personajes.',
    alignment='Identifica una técnica narrativa a partir del alcance efectivo de la información.')

add(19,18,'0-0-4','clasificación dramática',
    '¿Qué rasgo del fragmento «La mejor silla» fundamenta mejor su clasificación como farsa?',
    ['La exageración caricaturesca de una disputa por prestigio y la acción corporal absurda.',
     'La caída irreversible de un personaje noble ante un destino presentado como inevitable.',
     'El análisis íntimo y contenido de un conflicto familiar, sin deformación de las conductas.',
     'La reconstrucción documental de un suceso mediante testimonios sin intervención escénica.'],0,
    ['La competencia desproporcionada por una silla y la caída buscada para parecer superior caricaturizan el afán de prestigio. La deformación cómica sostiene la lectura como farsa.',
     'Se describe un rasgo propio de ciertas tragedias. Aquí no hay un destino inexorable: la caída produce ridículo dentro de una acción cómica exagerada.',
     'El tono no es contenido ni realista: los gestos y la lógica de los personajes están deliberadamente deformados.',
     'El fragmento presenta personajes, diálogo y acotaciones para una acción ficticia. No se organiza como reconstrucción testimonial de hechos reales.'],
    [text('La mejor silla','EL ALCALDE: Mi silla es más alta; por eso mi opinión vale más.\nEL VECINO: Entonces escucharéis mi gran argumento.\n(Se sube a tres sillas apiladas. El alcalde añade otra a la suya; ambos caen y siguen discutiendo desde el suelo sobre quién cayó más alto.)')],
    note='Se reemplaza la escena por una farsa original con deformación y comicidad inequívocas; no se usa cualquier diálogo repetitivo como criterio suficiente.',
    alignment='Fundamenta la clasificación en un subgénero dramático mediante rasgos del fragmento.')

add(20,19,'0-0-5','interpretación de cómic',
    'En «Despedida», ¿qué sentido tiene el hilo rojo que une a los personajes después de separarse?',
    ['Demuestra que la estación dispone de un sistema físico para impedir que las personas se alejen.',
     'Hace visible la continuidad del vínculo afectivo a pesar de la distancia.',
     'Indica que ambos han olvidado lo que sentían antes de despedirse.',
     'Representa un recorrido ferroviario cuya longitud se puede calcular con la imagen.'],1,
    ['La tira presenta el hilo entre los pechos de los personajes, sin un mecanismo de estación. Leerlo como instalación física ignora su función figurada.',
     'El hilo permanece cuando los cuerpos se distancian y conecta sus pechos. Esa relación visual expresa que el vínculo afectivo continúa más allá de la cercanía física.',
     'La persistencia de la conexión visual sugiere continuidad, no desaparición del afecto. El segundo cuadro conserva el vínculo mostrado en el primero.',
     'No hay escala ni trazado ferroviario. El hilo conecta personajes y funciona como recurso expresivo, no como información cartográfica.'],
    [figure('Despedida','media-310-despedida.svg','Dos viñetas. En la primera, dos personas se toman de las manos y un hilo rojo une la zona de sus pechos. En la segunda caminan en direcciones opuestas; el hilo rojo continúa uniéndolas. Una dice: «Te escribiré».')],
    note='El cómic de Liniers se sustituye por una tira original con otra metáfora visual. Se conserva la interpretación fundamentada de sentimientos mediante un recurso gráfico.',
    alignment='Atribuye un sentido a un recurso de cómic relacionando elementos de ambas viñetas.')

add(21,20,'0-0-7','visión de mundo',
    '¿Qué visión de mundo sostiene el hablante de «Los mapas»?',
    ['La experiencia confirma sin cambios todas las certezas aprendidas en la infancia.',
     'Conocer el nombre de un lugar garantiza comprenderlo por completo.',
     'La experiencia obliga a revisar las certezas con las que se interpretaba la vida.',
     'Toda búsqueda de conocimiento debe abandonarse porque carece de valor.'],2,
    ['El poema dice que los mapas quedaron pequeños y que cambió el hablante. No presenta una confirmación intacta de las certezas iniciales.',
     'Nombrar los caminos no evita descubrir orillas imprevistas. El poema cuestiona que una representación previa agote la experiencia.',
     'La insuficiencia de los mapas y el cambio del propio hablante sostienen una visión de la experiencia como revisión de certezas.',
     'El hablante sigue preguntando y recorriendo. Cuestionar certezas no equivale a rechazar cualquier posibilidad de conocimiento.'],
    [text('Los mapas','Me dieron mapas con todos los caminos.\nPero el viaje abrió orillas que no estaban.\nAhora pregunto hasta mi propio nombre:\nel mapa quedó pequeño, y yo he cambiado.')],
    note='Se usa un poema original y se vincula la visión de mundo con evidencias que muestran revisión de certezas, sin inferir nihilismo automáticamente.',
    alignment='Reconoce la perspectiva que una obra sostiene sobre la experiencia y el conocimiento.')

add(22,21,'0-0-7','punto de vista literario',
    '¿Qué idea defiende la voz de «La alegría» mediante sus imágenes?',
    ['La alegría auténtica debe permanecer secreta para no perder su valor.',
     'La alegría permite evitar cualquier dificultad de la vida cotidiana.',
     'La alegría solo puede reconocerse por las palabras de una autoridad.',
     'La alegría busca expresarse y compartir su presencia con otros.'],3,
    ['El cajón cerrado aparece como lo que la alegría rechaza. La ventana abierta y la voz compartida contradicen una defensa del secreto.',
     'El texto no promete resolver todas las dificultades. Sus imágenes se refieren a expresión y comunicación, no a eliminación de problemas.',
     'No se invoca ninguna autoridad. La voz fundamenta su idea mediante acciones figuradas que dan movimiento a la alegría.',
     'Escapar del cajón, abrir la ventana y llamar al vecino presentan la alegría como impulso de manifestación y encuentro.'],
    [text('La alegría','La alegría no acepta vivir en un cajón cerrado. Se escapa por las rendijas, abre la ventana y llama al vecino para que también vea amanecer.')],
    note='Se crea un fragmento propio y se pregunta por la idea que articula todas sus imágenes, evitando privilegiar un detalle aislado.',
    alignment='Reconoce un punto de vista que el texto literario sostiene mediante recursos persuasivos.')

add(23,22,'0-0-8','movimiento literario',
    'Una ficha sitúa el poema a comienzos del siglo XX en Hispanoamérica y destaca musicalidad, imágenes sensoriales y una renovación estética asociada a Rubén Darío. ¿Con qué movimiento se vincula mejor?',
    ['Naturalismo, por la explicación determinista de la conducta mediante herencia y ambiente.',
     'Neoclasicismo, por la subordinación explícita de la forma a una lección moral racional.',
     'Modernismo hispanoamericano, por su elaboración musical y sensorial del lenguaje.',
     'Realismo social, por el predominio de un registro documental de condiciones laborales.'],2,
    ['El material no explica una conducta por determinación biológica o social. El énfasis está en la elaboración estética del lenguaje.',
     'No se presenta una lección moral como centro ni una defensa de normas racionales clásicas. La ficha destaca una búsqueda de renovación estética.',
     'El contexto hispanoamericano, la referencia a Darío y la elaboración musical y sensorial permiten fundamentar esta relación, más allá de una palabra ornamental aislada.',
     'No hay un registro documental del trabajo o de un conflicto social concreto. Esos rasgos no describen el material ofrecido.'],
    [text('Jardín nocturno','En la fuente de plata tiembla un rumor de seda;\nla noche azul perfuma sus pétalos de luz.')],
    note='Poema y ficha didácticos originales, sin atribución a autores históricos. Se aporta contexto para no clasificar un movimiento por un único adjetivo o símbolo.',
    alignment='Relaciona rasgos formales y contexto histórico-literario para reconocer un movimiento.')

add(24,23,'0-0-9','tema contemporáneo',
    '¿Qué tema de la literatura contemporánea desarrolla «El inventario»?',
    ['La existencia de una descripción única y definitiva que abarca toda la realidad.',
     'La superioridad moral inevitable del pasado sobre el presente.',
     'La desaparición literal del mundo una vez que alguien lo describe.',
     'La imposibilidad de agotar la realidad mediante una sola representación.'],3,
    ['Cada nueva descripción deja algo fuera y obliga a abrir otro cuaderno. El texto niega, precisamente, una representación que cierre todo el inventario.',
     'No compara la moral de dos épocas. Su conflicto se concentra en los límites de describir un mundo cambiante.',
     'El mundo no desaparece: se transforma y sigue ofreciendo aspectos nuevos. Confundir representación e inexistencia altera el sentido del relato.',
     'El inventario nunca termina porque cada perspectiva y cada cambio introducen elementos que no estaban registrados. Esa estructura expresa la inabarcabilidad de la realidad.'],
    [text('El inventario','Hizo una lista de cuanto existía en la plaza. Al terminar, descubrió que faltaba la plaza vista por su hermana. Abrió otro cuaderno. Mientras escribía, cayó una hoja que no estaba en ninguna lista.')],
    note='Se sustituye el poema por un microrelato original que distingue inabarcabilidad de inexistencia literal de la realidad.',
    alignment='Reconoce uno de los temas contemporáneos enumerados explícitamente en el temario.')

add(25,24,'0-0-7','valores en una voz narrativa',
    '¿Qué valoración legitima la voz que presume en «El primero», sin atribuirla automáticamente al autor?',
    ['Que el valor personal se mide por superar a otros en premios, posesiones y reconocimiento.',
     'Que cooperar importa más que cualquier posición en una competencia.',
     'Que renunciar a los bienes materiales es la única forma de felicidad.',
     'Que todos los logros deben permanecer anónimos para tener mérito.'],0,
    ['La voz acumula comparaciones y exige quedar por encima de los demás. Así legitima una valoración centrada en éxito competitivo y reconocimiento externo.',
     'El fragmento organiza el mérito como superioridad individual. No presenta la cooperación como el criterio principal para valorar a las personas.',
     'La voz exhibe sus posesiones y premios como pruebas de valor. No propone austeridad ni renuncia material.',
     'El narrador exige que el éxito sea visible en la fotografía. Esa búsqueda de reconocimiento contradice el anonimato como criterio de mérito.'],
    [text('El primero','Mi casa tiene más pisos que la tuya y mis diplomas ocupan otra pared. Si alguien recibe un premio, consigo dos. No me basta llegar: necesito que en la foto todos sepan que llegué primero.')],
    note='Se usa una voz narrativa original. La consigna distingue la valoración expresada por esa voz de una adhesión del autor y vincula el tema al indicador sobre legitimación de valores.',
    alignment='Identifica los valores que una voz literaria legitima mediante comparación y exageración.')

add(26,25,'0-0-10','teoría literaria',
    '¿Qué perspectiva teórica se reconoce en la propuesta de lectura presentada?',
    ['Un estudio biográfico que explica cada significado por un hecho de la vida del autor.',
     'Un estudio exclusivamente métrico que identifica el sentido con el número de sílabas.',
     'Una clasificación de funciones narrativas que busca un modelo estable de relaciones.',
     'Una lectura deconstructiva que examina tensiones y desplazamientos que impiden fijar un significado definitivo.'],3,
    ['La propuesta se centra en relaciones y tensiones del lenguaje. No remite a episodios biográficos para resolver el significado.',
     'La métrica puede ser un objeto de análisis, pero no explica la inestabilidad del significado descrita en este material.',
     'La búsqueda de un modelo estable caracteriza otra orientación. Aquí se examina cómo las oposiciones del propio texto desestabilizan un cierre definitivo.',
     'La atención a contradicciones internas y al desplazamiento de los significados corresponde a una lectura deconstructiva. Esto no implica que cualquier interpretación carezca de necesidad de evidencia.'],
    [text('Propuesta crítica','Un texto presenta el habla como superior a la escritura, pero sus propios ejemplos necesitan la escritura para explicar qué sería un habla auténtica. La lectura examina esa dependencia y muestra cómo la oposición se desestabiliza; ningún término conserva una pureza definitiva.')],
    note='Se reemplaza la cita teórica por un caso didáctico original de oposición y dependencia; no se atribuyen estas frases a Derrida ni a Eagleton.',
    alignment='Distingue un rasgo de la deconstrucción entre perspectivas de análisis literario.')

add(27,26,'0-0-10','lector y recepción',
    'Una investigación compara cómo lectores de dos épocas interpretan el final de una novela según sus expectativas culturales. ¿Con qué perspectiva se relaciona principalmente?',
    ['Con un análisis que limita la lectura al recuento de rimas y metros.',
     'Con una reconstrucción de la intención privada del autor que excluye a los lectores.',
     'Con una descripción de manuscritos que solo busca establecer cuál palabra escribió primero el autor.',
     'Con la estética de la recepción, al estudiar la participación del lector y sus horizontes de expectativas.'],3,
    ['El objeto de estudio son las interpretaciones de lectores en contextos distintos, no la estructura métrica del texto.',
     'La investigación no reduce el sentido a una intención autoral fija: examina cómo se recibe la obra desde diferentes expectativas.',
     'Establecer variantes textuales es una tarea distinta. Aquí se compara la recepción de la misma obra, no la cronología material de sus borradores.',
     'La estética de la recepción considera la relación entre obra y lectores, incluidos sus horizontes históricos de expectativas. Esa relación explica el enfoque de la investigación.'],
    note='Se precisa el análisis de lectores situados históricamente para distinguir la recepción de una simple descripción de emociones individuales.',
    alignment='Reconoce el foco en lectores y horizontes de expectativas de una teoría del temario.')

add(28,27,'0-1-0','propósito informativo',
    '¿Cuál es el propósito predominante de esta reseña biográfica dirigida a visitantes de una biblioteca?',
    ['Convencer a los visitantes de comprar un libro mediante una oferta comercial.',
     'Informar sobre la trayectoria y algunos rasgos de una escritora.',
     'Enseñar paso a paso cómo postular a una beca de edición.',
     'Demostrar que todas las escritoras comparten una misma personalidad.'],1,
    ['La reseña no ofrece precios ni llama a comprar. Presenta información sobre una persona, no una promoción comercial.',
     'Los datos sobre formación, primeras publicaciones y trabajo muestran una trayectoria; las observaciones sobre su curiosidad caracterizan a la escritora.',
     'No hay una secuencia de instrucciones para realizar un trámite. Mencionar un taller no convierte el texto en un procedimiento.',
     'La información se refiere a una figura particular. No entrega una comparación que permita generalizar sus rasgos a todas las escritoras.'],
    [text('Reseña de una escritora ficticia','Clara Vidal creció cerca de un puerto y desde pequeña registraba las historias que escuchaba en el mercado. Publicó sus primeros relatos mientras trabajaba en una biblioteca. Sus cuadernos muestran una curiosidad constante por las voces y costumbres de su barrio.')],
    note='Se usa una biografía ficticia declarada, sin inventar datos sobre Teresa Wilms Montt. La consigna explicita destinatario y género informativo.',
    alignment='Caracteriza la finalidad de un texto informativo en una situación de enunciación concreta.')

add(29,28,'0-1-2','argumento por analogía',
    '¿En qué procedimiento se apoya el argumento de «Ensayar»?',
    ['En la autoridad de un especialista al que se atribuye una conclusión.',
     'En una estadística que cuantifica la frecuencia de errores de estudiantes.',
     'En un valor moral presentado como criterio suficiente para juzgar una conducta.',
     'En una analogía que traslada una relación del ensayo musical a la escritura.'],3,
    ['No se cita la opinión de un especialista. La fuerza del argumento se construye comparando dos procesos.',
     'El fragmento no aporta cantidades ni resultados de una muestra. No es una generalización apoyada en datos estadísticos.',
     'No se invoca principalmente un principio moral como justicia o igualdad. Se compara el papel de la práctica en dos actividades.',
     'Afinar después de escuchar permite explicar por comparación por qué revisar un borrador mejora un escrito. La analogía es pertinente al proceso, aunque no prueba que ambas actividades sean idénticas.'],
    [text('Ensayar','Un cuarteto no interpreta mejor una obra por esconder sus desafinaciones: necesita escucharse y ajustar. Del mismo modo, quien escribe aprende al releer su borrador y corregir lo que todavía no comunica bien.')],
    note='Se reemplaza la entrevista por un argumento original con relación analógica explícita; la explicación también señala el límite de la comparación.',
    alignment='Distingue argumentos basados en explicaciones y comparaciones.')

add(30,29,'0-1-2','argumento explicativo',
    '¿Cómo fundamenta la reseña su juicio sobre el suspenso de la película ficticia?',
    ['Presentando únicamente la cifra de entradas vendidas como prueba de calidad.',
     'Apelando al deber moral de respetar a quienes prefieren la película.',
     'Citando como razón decisiva el prestigio de un crítico reconocido.',
     'Explicando cómo la información anticipada modifica la incertidumbre del espectador.'],3,
    ['No se entregan cifras de venta. Además, la popularidad comercial no es el criterio utilizado para analizar el suspenso.',
     'La reseña no juzga moralmente al público. Relaciona una decisión narrativa con un efecto de recepción.',
     'No se invoca una autoridad externa. La justificación se apoya en describir y explicar el funcionamiento del relato.',
     'El texto conecta revelar tempranamente la solución con reducir la incertidumbre. Es una explicación del efecto de un recurso narrativo, no solo una declaración de gusto.'],
    [text('Reseña','La película pierde parte de su suspenso porque revela al responsable en la primera escena y luego repite esa información. Cuando los investigadores presentan sus dudas, el público ya conoce la respuesta y dispone de pocos elementos nuevos que la pongan en cuestión.')],
    note='Se emplea una reseña original con una relación causal delimitada; no se sostiene que revelar al responsable elimine siempre cualquier forma de suspenso.',
    alignment='Reconoce una explicación causal como fundamento de un punto de vista.')

add(31,30,'0-1-3','discurso público',
    'En este fragmento de una ceremonia comunitaria, ¿qué función discursiva predomina?',
    ['Describir de manera neutral las dimensiones del edificio.',
     'Elogiar públicamente conductas y valores considerados ejemplares.',
     'Narrar en orden cronológico todos los hechos de una investigación.',
     'Intercambiar preguntas y respuestas con los asistentes.'],1,
    ['El texto valora la solidaridad y el compromiso. No se limita a caracterizar propiedades físicas de un edificio.',
     'La voz reconoce y celebra públicamente las acciones de las voluntarias. Esa función de elogio es epidíctica y puede integrarse con otras formas en un discurso público.',
     'Se mencionan acciones, pero no se organiza una secuencia de hechos para reconstruir una investigación. El centro es su valoración pública.',
     'Dirigirse a una audiencia no constituye por sí solo una secuencia dialogada. El fragmento no alterna turnos de pregunta y respuesta.'],
    [text('Reconocimiento comunitario','Hoy honramos a quienes abrieron esta biblioteca cada tarde, incluso cuando faltaban recursos. Su compromiso convirtió una sala vacía en un espacio para todos. Gracias por mostrarnos lo que puede hacer la solidaridad.')],
    note='Se reemplaza la descalificación del discurso fuente por un elogio original, explicitando la función epidíctica sin negar que el discurso público pueda combinar secuencias.',
    alignment='Reconoce una de las formas discursivas que integran un discurso público y su función.')

add(32,30,'0-1-3','secuencia en discurso público',
    '¿Qué secuencia predomina en este fragmento de un discurso conmemorativo?',
    ['Dialogada, porque alterna preguntas de un entrevistador y respuestas de un invitado.',
     'Narrativa, porque organiza acontecimientos de la biblioteca en una secuencia temporal.',
     'Descriptiva, porque detalla exclusivamente la apariencia actual de la sala.',
     'Instructiva, porque ordena pasos que el público debe ejecutar de inmediato.'],1,
    ['Habla una sola voz y no hay alternancia de intervenciones. La presencia de público no convierte el fragmento en diálogo.',
     'Los marcadores en 2012, tres años después y en 2020 articulan acontecimientos que transforman la biblioteca a través del tiempo.',
     'El fragmento cuenta fundación, traslado y ampliación. No organiza sus frases como una descripción estática de la apariencia de un lugar.',
     'Los hechos se presentan como ya ocurridos. No se dan instrucciones ni se solicita al público realizar un procedimiento.'],
    [text('Aniversario','En 2012 comenzamos con una caja de libros prestados. Tres años después nos trasladamos a esta sala. En 2020 sumamos lecturas a distancia y, al reabrir, recuperamos los encuentros de los sábados.')],
    note='Se utiliza un discurso original con cronología explícita para que la secuencia narrativa pueda identificarse sin depender de una clasificación ambigua del original.',
    alignment='Identifica la función organizadora de una secuencia dentro del discurso público.')

add(33,31,'0-1-4','relación con la audiencia',
    '¿Qué relación busca construir el diario ficticio con sus lectores en este mensaje?',
    ['Cercanía y colaboración, al presentar la participación de los lectores como parte del trabajo del diario.',
     'Distancia jerárquica, al declarar que la experiencia de los lectores carece de valor informativo.',
     'Neutralidad impersonal, al evitar cualquier valoración de la participación ciudadana.',
     'Relación exclusivamente comercial, al limitarse a informar el precio de la suscripción.'],0,
    ['Las expresiones nuestra conversación y juntos incluyen a la audiencia en una tarea común. El diario reconoce sus aportes y promueve colaboración.',
     'El texto afirma que las cartas permiten conocer problemas del barrio. Eso contradice que se descarte la experiencia de los lectores.',
     'Se valora explícitamente la participación y se invita a continuarla. La voz no adopta una distancia impersonal respecto de su audiencia.',
     'No se ofrecen tarifas ni compras. La relación se presenta en términos de participación y elaboración de información.'],
    [text('Mensaje a quienes nos leen','Sus cartas forman parte de nuestra conversación diaria. Gracias a ellas conocemos dificultades del barrio que no siempre llegan a una conferencia de prensa. Sigamos preguntando y buscando respuestas juntos.')],
    note='Se sustituye el texto del diario por un mensaje original. La relación con la audiencia se justifica con marcas lingüísticas concretas.',
    alignment='Caracteriza la relación emisor-mensaje-receptor en un texto de un medio.')

add(34,32,'0-1-5','contexto de un anuncio',
    '¿Qué circunstancia permite interpretar el sentido de «Todo gira alrededor del balón» en el anuncio de Radio Patio?',
    ['Una explicación científica sobre el movimiento de los planetas.',
     'Una comunicación privada cuyo único destinatario es un jugador.',
     'La cobertura de un campeonato escolar que concentra la atención de la comunidad.',
     'Una instrucción para fabricar balones con determinadas medidas.'],2,
    ['El balón ocupa figuradamente el centro de atención. El texto anuncia transmisiones deportivas y no formula una afirmación astronómica.',
     'El anuncio está dirigido a la comunidad interesada en el campeonato, no a un destinatario único dentro de una conversación privada.',
     'Las menciones al campeonato, los resultados y las transmisiones explican la exageración: durante ese evento, la atención de la audiencia se concentra en el fútbol.',
     'El anuncio no presenta materiales ni pasos de fabricación. Su propósito es invitar a seguir una cobertura deportiva.'],
    [figure('Radio Patio','media-310-campeonato.svg','Afiche ficticio de Radio Patio: «Semana del campeonato escolar. Todo gira alrededor del balón. Partidos, entrevistas y resultados, cada tarde». Un balón ocupa el centro y tres puntos siguen una órbita dibujada a su alrededor.')],
    note='Se crea un anuncio de un campeonato escolar ficticio. El contexto aparece en el recurso y no depende de reconocer un evento o una marca reales.',
    alignment='Relaciona las circunstancias de enunciación con el sentido de un mensaje mediático.')

add(35,33,'0-1-6','recurso retórico en publicidad',
    '¿Qué recurso usa principalmente el anuncio «Con un lápiz», al afirmar que un solo lápiz llena mil bibliotecas en una tarde?',
    ['Una elipsis que omite el sujeto de todas las oraciones.',
     'Una hipérbole que exagera la capacidad de escritura para destacar el producto.',
     'Una sinécdoque que nombra una parte real del lápiz en lugar del objeto completo.',
     'Una comparación explícita construida con la fórmula «tan… como».'],1,
    ['El enunciado identifica un lápiz como sujeto. La omisión gramatical no explica la afirmación desmesurada sobre su capacidad.',
     'Llenar mil bibliotecas en una tarde excede deliberadamente una posibilidad realista. Esa exageración construye la promesa publicitaria.',
     'Se nombra el lápiz completo y no una de sus partes. El mecanismo destacado consiste en aumentar desmesuradamente lo que podría producir.',
     'No aparece esa estructura comparativa ni se igualan expresamente dos elementos mediante como. Se formula una capacidad exagerada.'],
    [figure('Con un lápiz','media-310-lapiz.svg','Afiche ficticio con un lápiz y una fila de libros. Texto central: «Con un lápiz, llena mil bibliotecas en una tarde». Pie: «Anuncio ficticio para analizar recursos expresivos».')],
    note='El anuncio fuente se reemplaza por uno propio con una hipérbole verbal inequívoca y accesible en pantalla pequeña.',
    alignment='Relaciona un procedimiento retórico con la intención de un mensaje publicitario.')

add(36,33,'0-1-8','persuasión y estereotipos',
    '¿Qué estrategia persuasiva emplea el anuncio ficticio «Cada edad, su regalo»?',
    ['Asocia rígidamente ciertos regalos con grupos de edad, recurriendo a un estereotipo.',
     'Ofrece evidencia estadística de las preferencias individuales de toda la población.',
     'Sustenta su promesa en la opinión identificable de una autoridad experta.',
     'Describe de manera neutral materiales y dimensiones de cada producto.'],0,
    ['El anuncio da por sentado que jóvenes y mayores desean regalos distintos por su edad. Esa generalización simplifica a los grupos y puede excluir preferencias reales.',
     'No presenta una muestra, datos ni metodología. Sus afirmaciones generales no constituyen evidencia de preferencias individuales.',
     'No se cita un especialista ni un estudio. La persuasión se apoya en una expectativa social simplificada sobre la edad.',
     'El mensaje asigna deseos a las personas según su edad. No se limita a informar características técnicas de los productos.'],
    [figure('Cada edad, su regalo','media-310-regalos.svg','Anuncio ficticio para análisis crítico. Dos recuadros muestran un control de videojuegos y unas pantuflas. Texto: «Para jóvenes, aventura. Para mayores, solo descanso. Cada edad, su regalo».')],
    note='Se reemplaza el afiche por un ejemplo explícito de estereotipo etario. Se analiza críticamente la generalización, sin presentarla como descripción válida de las personas.',
    alignment='Reconoce el uso de estereotipos como estrategia de persuasión en medios.')

add(37,34,'0-1-7','publicidad y mundos literarios',
    '¿Qué relación construye el afiche «La jornada» entre el producto y un mundo de rasgos épicos?',
    ['Presenta la jornada como una experiencia íntima centrada únicamente en expresar tristeza.',
     'Representa un debate jurídico mediante pruebas y testimonios ante un tribunal.',
     'Reconstruye una crónica histórica documentada de una guerra real.',
     'Convierte figuradamente a la ciclista en una heroína que enfrenta desafíos y conquista una meta.'],3,
    ['La imagen y el lema destacan acción, desafíos y logro. No organizan la escena alrededor de una expresión íntima de tristeza.',
     'No hay tribunal, pruebas ni deliberación jurídica. Los signos visuales remiten a hazaña y combate figurado.',
     'Se trata de un anuncio ficticio: la armadura y el banderín construyen una asociación expresiva, no documentan un conflicto histórico.',
     'La armadura, los obstáculos como montañas y la meta con estandarte trasladan rasgos de hazaña heroica a una actividad cotidiana. El producto se asocia así a ese mundo.'],
    [figure('La jornada','media-310-jornada.svg','Afiche ficticio de una bicicleta. Una ciclista lleva un casco dibujado como yelmo; delante hay tres pequeños obstáculos con forma de montañas y una meta con banderín. Texto: «Conquista tu jornada».')],
    note='Se crea un anuncio propio que relaciona heroísmo y vida cotidiana mediante rasgos visibles, sin atribuir una condición divina al personaje.',
    alignment='Relaciona el mundo representado en un anuncio con rasgos de un mundo literario.')

add(38,35,'1-0-0','cohesión por elipsis',
    'En «Marta abrió el cuaderno y anotó la fecha», ¿qué procedimiento permite omitir Marta antes de anotó?',
    ['La elipsis de un sujeto que puede recuperarse de la cláusula anterior.',
     'La catáfora, porque el sujeto solo se identifica en una oración posterior aún no leída.',
     'La sinonimia, porque Marta y cuaderno tienen significados equivalentes.',
     'La hiperonimia, porque fecha es una categoría que incluye a Marta.'],0,
    ['El sujeto de anotó se recupera como Marta a partir de la primera cláusula. La omisión evita repetirlo y mantiene la continuidad referencial.',
     'El referente ya aparece antes de la omisión, no después. Por eso la explicación como anticipación catafórica no corresponde.',
     'No se sustituye el nombre por una expresión de significado equivalente. Se omite un elemento recuperable en el contexto.',
     'No existe una relación de inclusión semántica entre fecha y Marta. La continuidad se logra mediante la recuperación del sujeto omitido.'],
    note='Se utiliza una oración original y se indica expresamente el segmento analizado, para no depender de un subrayado que pueda perderse al digitalizar.',
    alignment='Reconoce un mecanismo de cohesión y explica cómo recupera el referente.')

add(39,35,'1-0-1','función de la coordinación',
    'En el texto de la recepción, ¿qué función cumplen las coordinaciones con «y»?',
    ['Presentan una causa gramatical explícita de cada acción mediante porque.',
     'Añaden acciones del personaje dentro de una secuencia del relato.',
     'Plantean alternativas excluyentes entre acciones que no pueden realizarse juntas.',
     'Contraponen dos afirmaciones mediante una objeción adversativa.'],1,
    ['El texto no emplea porque ni construye esas relaciones como subordinaciones causales. La sucesión puede interpretarse, pero la conjunción añade acciones.',
     'Las coordinaciones copulativas enlazan dejó y firmó, así como saludó y salió. Presentan acciones añadidas dentro de lo narrado.',
     'Una disyunción ofrecería alternativas mediante o u otra expresión equivalente. Aquí las acciones se presentan como realizadas, no como opciones excluyentes.',
     'No aparece una oposición como la expresada por pero. El enlace predominante suma acciones, aunque el relato avance temporalmente.'],
    [text('En la recepción','La visitante dejó el paquete y firmó el registro. Luego saludó a la encargada y salió al patio.')],
    note='Texto original con dos coordinaciones copulativas visibles; se distingue la relación gramatical aditiva de la secuencia temporal del relato.',
    alignment='Determina la función comunicativa de una coordinación en un texto.')

add(40,36,'1-1-0','modalización discursiva',
    '¿Qué expresión de la nota marca explícitamente un grado de certeza no pleno sobre la utilidad futura del dispositivo?',
    ['«Esta semana», porque localiza temporalmente la presentación.',
     '«Por ejemplo», porque introduce un caso de aplicación.',
     '«En la sala», porque indica el lugar de la demostración.',
     '«Es probable que», porque presenta la utilidad como una posibilidad evaluada.'],3,
    ['Localizar un hecho en el tiempo no expresa, por sí mismo, cuánto se compromete la voz con su verdad o posibilidad.',
     'La expresión organiza un ejemplo. No marca directamente duda, probabilidad ni certeza sobre la afirmación.',
     'El complemento señala una ubicación. No introduce una evaluación epistémica del contenido.',
     'Es probable que sitúa el resultado como una posibilidad y evita afirmarlo como seguro. Es una marca explícita de modalización epistémica.'],
    [text('Nota sobre un prototipo ficticio','Esta semana se presentó un sensor en la sala del taller. Es probable que ayude a detectar filtraciones pequeñas. Por ejemplo, podría avisar cuando aparezca agua bajo una tubería.')],
    note='Se explicita el segmento relevante con una construcción de probabilidad, sin confundir conectores de ejemplificación o expresiones temporales con grados de certeza.',
    alignment='Distingue una marca textual de probabilidad frente a expresiones de tiempo, lugar y ejemplificación.')

add(41,37,'1-1-1','ortografía de homófonos',
    'En el borrador «El echo de compartir libros tubo buena recepción», ¿qué corrección y explicación corresponden?',
    ['«El hecho de compartir libros tubo buena recepción»: basta corregir echo porque tubo es una forma de tener.',
     '«El hecho de compartir libros tuvo buena recepción»: hecho nombra un acontecimiento y tuvo es una forma del verbo tener.',
     '«El echo de compartir libros tuvo buena recepción»: echo y hecho son intercambiables en cualquier contexto.',
     '«El hécho de compartir libros túvo buena recepción»: ambas palabras requieren tilde por su pronunciación.'],1,
    ['Hecho está bien corregido, pero tubo es un sustantivo que nombra un objeto tubular. La forma verbal necesaria es tuvo.',
     'El contexto exige el sustantivo hecho y la forma verbal tuvo. La selección ortográfica se apoya en función y significado, aunque esas parejas suenen igual en el habla habitual.',
     'Echo pertenece al verbo echar y no puede sustituir aquí al sustantivo hecho. Los homófonos no son intercambiables por compartir pronunciación.',
     'Hecho y tuvo son palabras llanas terminadas en vocal; no requieren esas tildes. El problema se resuelve seleccionando las grafías apropiadas.'],
    note='Se usa un borrador propio y se exige aplicar la corrección, además de reconocer la homofonía. Se eliminan afirmaciones ambientales ajenas al objetivo ortográfico.',
    alignment='Aplica normas de ortografía literal mediante el significado y la función de palabras homófonas.')

add(42,38,'1-1-1','acentuación e hiato',
    '¿Por qué «seguía» y «venía» llevan tilde en la í?',
    ['Porque la vocal cerrada tónica junto a una vocal abierta forma hiato y debe llevar tilde.',
     'Porque la tilde distingue dos monosílabos con funciones gramaticales diferentes.',
     'Porque ambas son agudas terminadas en vocal y la fuerza recae en la última a.',
     'Porque toda palabra que contiene dos vocales juntas se tilda sin excepción.'],0,
    ['Se separan se-guí-a y ve-ní-a: í es tónica y a es abierta átona. Esa combinación forma hiato y se marca con tilde en la vocal cerrada.',
     'Son palabras de varias sílabas, no parejas de monosílabos diferenciadas por tilde diacrítica. Aquí importa la secuencia vocálica.',
     'La fuerza de voz no recae en la a final, sino en í. Clasificarlas como agudas desplaza incorrectamente su sílaba tónica.',
     'Las secuencias vocálicas siguen reglas específicas; muchas forman diptongos y no llevan tilde. La condición relevante aquí es la vocal cerrada tónica.'],
    note='Se conservan las dos palabras visibles del original y se explicita la regla de hiato, sin depender del nombre escolar acento dierético.',
    alignment='Aplica una regla de ortografía acentual a palabras concretas.')

add(43,38,'1-1-1','tilde diacrítica',
    '¿Qué explica las tildes de «sí» y «más» en «Confía en sí mismo y pide más tiempo»?',
    ['Sí es una conjunción condicional y más una conjunción equivalente a pero.',
     'Ambas palabras son agudas polisílabas terminadas en vocal o s.',
     'Distinguen el pronombre sí de la conjunción si y el cuantificador más de la conjunción mas.',
     'Se usan solo para indicar que las dos palabras deben leerse con volumen alto.'],2,
    ['Esas funciones corresponden a si y mas sin tilde. En la oración, sí remite reflexivamente al sujeto y más expresa cantidad.',
     'Son monosílabos; la razón de sus tildes no es la regla general de palabras agudas polisílabas, sino la distinción diacrítica.',
     'La tilde diferencia usos gramaticales: sí es pronombre reflexivo, mientras más cuantifica tiempo. Si puede introducir una condición y mas equivale a pero.',
     'La tilde diacrítica no es una instrucción de volumen. Sirve para distinguir determinados usos de palabras que, sin ella, comparten grafía.'],
    note='Se usa una oración propia y se mantiene la oposición entre usos tónicos y conjunciones. Más funciona aquí como cuantificador del nombre tiempo.',
    alignment='Aplica la tilde diacrítica distinguiendo funciones gramaticales en contexto.')

add(44,39,'0-1-0','propósito de una entrevista',
    'En la respuesta de esta entrevista informativa, ¿para qué se organiza una secuencia de experiencias?',
    ['Para probar que todas las vocaciones son idénticas desde el nacimiento.',
     'Para demostrar que solo la familia determina los intereses profesionales.',
     'Para enseñar los pasos obligatorios de un trámite de ingreso universitario.',
     'Para explicar al público cómo un interés se desarrolló progresivamente.'],3,
    ['La entrevistada relata cambios y nuevas oportunidades de aprendizaje. No generaliza su experiencia a todas las personas ni a una inclinación inmutable.',
     'La familia participa en el relato, pero también intervienen lecturas, un taller y la propia práctica. No se establece una causa única.',
     'La respuesta reconstruye una trayectoria personal. No presenta requisitos ni instrucciones de un procedimiento administrativo.',
     'La secuencia conecta curiosidad inicial, nuevas experiencias y continuidad de la práctica. Así comunica a la audiencia un desarrollo, en lugar de situarlo en un único momento decisivo.'],
    [text('Entrevista a una ilustradora ficticia','—¿Cómo nació tu interés por ilustrar?\n—De niña dibujaba los insectos que veía con mi abuelo. Años después encontré libros de ilustración científica. En enseñanza media participé en un taller y empecé a combinar observación y dibujo; desde entonces seguí aprendiendo.')],
    note='Se sustituye la entrevista real por una ficticia. Se clasifica por el propósito informativo de la respuesta, sin forzar su inclusión en argumentación oral.',
    alignment='Reconoce cómo una secuencia contribuye al propósito de informar a una audiencia.')

add(45,40,'1-1-2','reformulación en diálogo',
    'En una discusión, una estudiante pide «usar responsablemente el agua». Un compañero pregunta qué entiende por responsablemente. ¿Qué intervención mejora la precisión de su postura?',
    ['Repetir la misma frase con mayor énfasis, sin modificar su contenido.',
     'Añadir otra recomendación general sobre energía sin responder a la pregunta.',
     'Definir qué usos considera responsables y ofrecer ejemplos y límites de ese criterio.',
     'Dar por cerrado el intercambio porque solicitar una aclaración equivale a rechazar la postura.'],2,
    ['El énfasis no aclara el significado de la expresión cuestionada. La dificultad es conceptual, no de volumen o convicción.',
     'Cambiar de recurso desplaza el tema sin resolver la ambigüedad de responsablemente. Una ampliación útil debe responder al problema planteado.',
     'Puede precisar, por ejemplo, evitar pérdidas reparables sin impedir usos necesarios de higiene. Definir y ejemplificar hace discutible un criterio concreto.',
     'Pedir precisión puede contribuir a comprender y desarrollar el argumento. No implica necesariamente desacuerdo ni justifica clausurar la conversación.'],
    note='Se adapta el tema a un caso propio y se conserva la estrategia de aclarar términos para sostener una discusión argumentativa.',
    alignment='Identifica una reformulación que sigue el hilo de la discusión y permite hacerse entender.')

add(46,40,'1-1-3','foro y debate',
    'Después de ver una película, el curso organizará un foro para contrastar interpretaciones. ¿Qué organización corresponde mejor a esta situación oral?',
    ['Asignar dos bancadas que deben defender posiciones opuestas fijadas antes de ver la película.',
     'Encargar una exposición continua a una sola persona, sin intervenciones de los asistentes.',
     'Abrir intervenciones de distintos participantes sobre un tema común, con moderación y razones apoyadas en la película.',
     'Exigir una votación final que elimine todas las interpretaciones discrepantes como condición de cierre.'],2,
    ['Dos bancadas con posiciones preasignadas describen una organización típica de debate. El foro propuesto busca abrir intervenciones y contrastar interpretaciones.',
     'Una exposición sin intercambio no permite la participación de la audiencia propia del foro. Podría ser una ponencia, pero no satisface esta organización.',
     'La moderación administra turnos y mantiene el tema, mientras los participantes aportan razones. El foro puede apoyarse en preparación previa y no exige alcanzar unanimidad.',
     'El propósito de contrastar interpretaciones no obliga a suprimir el desacuerdo por votación. Se pueden sintetizar coincidencias y diferencias al cerrar.'],
    note='Se reformula la comparación entre situaciones orales: un foro no exige bancadas ni consenso, pero tampoco excluye preparación o investigación previa.',
    alignment='Caracteriza una situación de argumentación oral formal y sus reglas de participación.')
