"""Compile original questions. Sources: indicator|difficulty|format|stem|four option/reason pairs|optional material."""
import json
from pathlib import Path
from collections import Counter
ROOT=Path(__file__).resolve().parents[1]
audit=json.loads((ROOT/'docs/auditoria-307.json').read_text())
materials=json.loads((ROOT/'content-307/materials.json').read_text())
items=[];archive={};summary={}
for sid,before in audit['specialties'].items():
 indicators={i['id']:i for i in before['indicators']};archive[sid]=[q['id'] for q in before['archive']]
 rows=(ROOT/'content-307'/(sid+'.tsv')).read_text().strip().splitlines();assert len(rows)==50,(sid,len(rows))
 coverage=Counter();keys=Counter()
 for n,row in enumerate(rows):
  c=[s.strip() for s in row.split('|')];assert len(c) in (12,13),(sid,n,len(c))
  indicator,diff,kind,stem=c[:4];assert indicator in indicators and diff in ('básica','media','alta'),(sid,n)
  assert all(c[:12]) and len(set(c[4:12:2]))==4,(sid,n)
  assert len(set(c[5:12:2]))==4 and min(map(len,c[5:12:2]))>=30,(sid,n)
  answer=n%4;pairs=list(zip(c[4:12:2],c[5:12:2]));pairs=pairs[-answer:]+pairs[:-answer] if answer else pairs
  material=c[12] if len(c)==13 else '';assert not material or material in materials,(sid,n,material)
  q=dict(id=f'{sid}-307-{n+1:02}',specialtyId=sid,indicatorId=indicator,q=stem,o=[p[0] for p in pairs],a=answer,explanations=[p[1] for p in pairs],e=c[5],diff=diff,questionType=kind,skill=kind,feedbackKind='por-pregunta',questionLang='en' if sid=='basica-ingles' else 'es',stimulus=[materials[material]] if material else [],familyId=f'{sid}:{material or indicator+":"+str(n+1)}',version='3.0.7',origin='Pregunta original ProfeECEP',sourceNote='Ejercicio original para estudio, vinculado al temario 2026 cargado. No es una pregunta oficial ni una predicción del examen.',difficultyNote='Dificultad estimada para práctica; no calibración psicométrica.')
  items.append(q);coverage[indicator]+=1;keys[answer]+=1
 assert set(coverage)==set(indicators),(sid,'coverage')
 assert all(i['beforeSpecific']+coverage[i['id']]>=2 for i in indicators.values()),sid
 summary[sid]=dict(new=50,archived=len(archive[sid]),active=before['before']-len(archive[sid])+50,indicators=len(indicators),keys=dict(keys),gapsCovered=[i['id'] for i in indicators.values() if not i['beforeSpecific']])
assert len(items)==300 and len({q['q'].casefold() for q in items})==300
(ROOT/'bank-data-307.js').write_text('// Generated by scripts/build-307.py; edit content-307 sources.\nwindow.PE307_ITEMS = '+json.dumps(items,ensure_ascii=False,indent=2)+';\nwindow.PE307_ARCHIVE_IDS = '+json.dumps(archive,ensure_ascii=False)+';\n')
(ROOT/'docs/resultados-307.json').write_text(json.dumps(summary,ensure_ascii=False,indent=2)+'\n')
print('300 questions; 1200 explanations;',sum(x['active'] for x in summary.values()),'active; 25 gaps covered')
