"""Transcripciones de apoyo recuperadas de los resultados ASR del 5 de octubre.
Edición de puntuación, agrupación por pasajes y omisión de algunas muletillas.
Los tiempos aproximados no sustituyen la grabación. Nombres inciertos marcados.
"""
TEXTS=[
'''[0:03] What is happiness? Can we find it in a new pair of shoes? A fast car? Or a bigger house? Or does real happiness lie somewhere else?
[0:29] Hundreds of studies have proved that spending time in nature can make us feel better both in mind and body in a way that nothing else can. We wanted to find out whether simply watching footage of the natural world could have the same effect.
[0:48] Last year, we partnered with Professor [name not confirmed], an expert in human psychology and emotion at the University of California, Berkeley. For this project, he has reviewed over 150 scientific studies that explore the positive effect of nature on humans. We also asked over 7,500 people in six countries to tell us how they were feeling before and after watching Planet Earth 2 clips.
[1:15] This data showed significant increases in joy, contentment, curiosity, awe, amazement, and wonder, and clear reductions in tiredness and low energy. It even reduced stress, especially among younger viewers. These findings revealed that wildlife programs can cause viewers to experience positive emotions.
[1:40] My study of human happiness has revealed that these emotions — amazement, wonder and awe — are the foundations of a powerful form of real human happiness. Real happiness is a deeper, less transient form of happiness that can positively affect our health and well-being.
[2:00] So by simply watching incredible footage of our natural world, you too can experience these uplifting emotions, helping you to be more connected with this amazing place we call home.''',
'''[0:00] Text number two, Going to Mars, associated with questions three and four.
[0:05] Do you believe that we should be going to Mars? Is this a good idea? — I don't see why not, for many reasons. — Well, it's expensive. — Well, yeah, sure, but... — And is it really of value in terms of science?
[0:14] It is if it galvanizes an entire generation of students in the educational pipeline to want to become scientists, engineers, technologists, and [final field not confirmed].
[0:23] The next generation of astronauts to land on Mars are in middle school now. So what I have in mind is you go select them. You select them now in middle school. — It's like China with Olympic athletes. — Exactly. And then [publication name not confirmed] will chase them and follow them. How are your grades? Are you healthy? Are you eating right? Then everybody will want to be them. It'll be the next generation's Mercury 7. And you get them from middle school. And that'll galvanize a nation.
[0:47] So we need, like, an American Idol for the next generation of astronauts. — Essentially, we've lost... Our intellectual compass, our urge to want to dream about tomorrow has long evaporated. And that has stymied any of our efforts to see ourselves in the future as the rest of the world passes us by.
[1:07] Isn't it okay, can't we just subcontract that out to other nations? Why should we be the ones to pay for it, do the science? Instead of we going to Mars, we just farm it out. — Yeah, China, you take care of that. Well, of course, Mars is already red, so it'd be easy to market that in China. — Yeah, but the science, we'll get the numbers. Why do we have to be the one to pay for it?
[1:28] That's if you're only after the scientific results. But there's another layer here, and that's the ambition that a next generation will have upon seeing one of our own out there doing the discovering.
[1:43] This is why there are statues throughout time and across cultures given unto explorers. Just look around. Yes, there are military people holding guns and explorers, all right? So the exploration part is a fundamental dimension of what it is to be alive and what it is to be human.''',
'''[0:00] Text number three, Agriculture, associated with questions five and six.
[0:07] What happens when agriculture goes high-tech? Farmers using what's known as precision agriculture can harness the power of science and technology to improve their land's productivity. This can be done in many ways and at any point in the process.
[0:22] But most farmers begin by collecting data about their own farms. For example, smart combines can detect differences in yield among fields while harvesting. Soil maps can reveal the soil's structure and chemical properties. And mobile weather apps can provide short and long-term forecasts.
[0:40] Computers then analyze all this information and help farmers decide how to make each field as productive as possible. Once the farmers have their analysis in hand, they can put it to use.
[0:52] GPS-guided systems help steer machinery, reducing seeding and spraying overlap to less than an inch. Variable-rate technology places specific amounts of fertilizer and pesticide on each part of a field. Monitors and other sensing technologies, such as drones, track field conditions.
[1:10] So what do farmers stand to gain? Well, by using guidance systems and variable-rate technologies, small farms saw an average gross annual benefit of $11,000. Typical-size farms stand to gain even more, and large farms reap the greatest return with the technology paying for itself in less than two years. A pretty sweet reward after a hard, high-tech day's work.''',
'''[0:00] Text number four, Plastic Trash, associated with questions seven to nine.
[0:08] Eight million metric tons of plastic trash enters the sea from land every year. The equivalent of five plastic bags filled with trash for every foot of coastline in the world.
[0:22] Across our ocean, plastic trash flows into circulation, dispersed almost everywhere, but concentrating in huge swaths in the midst of global currents, breaking down into smaller and smaller pieces, ingested by species across the marine world and sinking to the bottom of the sea.
[0:51] Anyone can make plastic anywhere in the world and sell it anywhere else in the world. There's no design paradigm, there's no barriers. In order to solve the plastic packaging problem, we need to effectively rethink the entire system. From one which is linear, i.e. take, make, dispose, to one where it can be recovered and fed back into the economy as a valuable plastic material, or one where it is bio-benign and it can enter the environment. The ultimate goal of the new plastics economy is to design an economy where plastic packaging never becomes waste. And to do that, we need every single player in the chain to change the way that they do things.
[1:28] But marine pollution comes in many forms. Industrial, agricultural, and urban waste also sweep into the sea, fueling explosions of algae that rob marine ecosystems of the oxygen they need to survive. With sustained pollution, these areas become dead zones, which already exist in more than 400 locations across the globe. But nutrient pollution can be managed through change in major contributing systems, like agriculture.
[2:10] If you eat, you're involved in agriculture. So it's a problem that all of us have to work together to solve. Soil health is critical for water quality. It's the first thing we have to focus on. Here on the farm, organic matter is the key thing that we try to improve.
[2:27] The more organic matter you have in the soil, the better the soil can hold on to nutrients like phosphorus and nitrogen. Organic matter keeps it from leaching out of the soil. It grabs onto it, and that's good for the farmer, but it's also good for water quality in the Bay.
[2:47] For any farmer to change their system is tricky and it takes a lot of work. I think all farmers want to. It's learning different processes, practices that allow you to do it effectively that becomes a key.''',
'''[0:00] The song that changed my life is a song called [song title not confirmed] that was off the first EP by a band called [band name not confirmed] that came out in about 1998.
[0:14] I remember at the time I was really into hardcore but I was kind of wondering whether there was a way that it could be more kind of melodic and more emotional and all that kind of thing.
[0:22] I'd sort of been having theoretical discussions with a friend about this and then he bought that EP and he actually called me up and told me to stop whatever it was I was doing and go around his house now because somebody had already cracked the thing that we'd been talking about. I went down and I just distinctly remember sitting on his bed listening to the song and scales falling from my eyes and thinking, wow, music can do so much more than I thought it could before, and it's an incredible song.
[0:48] [Artist and song title not confirmed], maybe, actually, because I remember when I first started working with [station name not confirmed], they gave me [artist name not confirmed]'s album. I remember I got [artist and album title not confirmed], and an album by [artist name not confirmed], which was called [album title not confirmed], and those three albums definitely changed my life.
[1:08] Even though I listened to grime or garage and stuff before, that's when it really kind of, that's when it took over, like UK dance, club culture. I was like 18 and I was like, this is it, this is me now. Forward, every week, loved it.
[1:24] The song that changed my life was my own song, [song title not confirmed]. Just making a record that kind of takes you from being in one position to the complete opposite. Not expecting it to happen as well, just hoping that it would. So that's definitely the song that changed my life.
[1:49] Just really thankful for everyone who was a part of it, really, to be honest. I couldn't ask for a better team, better production. When we took that song on the road to the nightclubs and to the festivals and everyone that was really vibing to it, like, it probably sounds a bit... I don't know if the word's big-headed, picking my own song, but honestly, if I was to say a song that changed my life, it definitely was that one.''',
'''[0:01] If you want to keep passengers happy, you have to keep them moving.
[0:11] With ever-increasing passenger numbers, security risks, resourcing issues and budget constraints, it's no wonder that airports and border agents are feeling the pressure. So, how can you increase throughput at borders without compromising security?
[0:28] Border automation could provide an answer, with secure, user-friendly alternatives to traditional border controls. eGates can fully automate the border process, speeding up the processing of low-risk passengers. Document and biometric checks are automatically performed as the traveller walks through the gate. Irregularities are flagged to border supervisors, who can focus their attention on high-risk passengers.
[0:55] For border agencies who wish to retain final vetting of passengers, the use of passport-control kiosks can automate part of the border-clearance process by performing document and biometric checks, resulting in shorter wait times, less congestion and faster processing.
[1:13] There are 113 million e-passports currently in circulation, with 175 million expected by 2019. Meanwhile, facial-recognition technology is now achieving a 99.7% success rate. But border automation isn't a future technology. It's working right now.
[1:34] In one European airport, travellers using SITA e-gates are now clearing border control in as little as 7.5 seconds. In another, SITA e-gates are processing up to 3,000 passengers a day.
[1:48] In North America, SITA's automated passport-control kiosks are capturing biometrics, validating travel documents and processing customs-declaration data in 90 seconds or less. At two Caribbean airports, SITA's kiosks are completing initial screening and watchlist checks in less than 60 seconds.
[2:10] Developed in partnership with our government customers over the past 20 years, SITA iBorders is the most trusted and widely deployed border-security portfolio available. As the world's leading specialist in air-transport technology, we're well positioned to deal with the growing overlap between airport and border processes.
[2:30] SITA can help you transform your border operations, making them smarter, faster, safer and more efficient. Why not find out how we can help you enhance your border operations?''',
'''[0:04] Take a look at this document. Any idea what that is? — That's his certificate of citizenship. — That is when your grandfather became an American citizen. Would you please read the highlighted section?
[0:23] Be it known that [name on the certificate], having petitioned to be admitted a citizen of the United States, is here unto affirm this 10th day of November in the year of our Lord, 1930. — That's his certificate of citizenship. — Wow. Complexion. Dark. — Dark. There you go.
[0:48] It's, you know, it's very moving for me. — It's a big journey. — Big time. And look, and they have like [first form of the name], and then they put [anglicized form of the name] on top of it. It's funny, they're Americanizing him.
[1:05] He became an American citizen in November of 1930, and a little more than a year later, his wife and child arrived. Did your father talk about what it was like to get here, and what America was like?
[1:15] Yeah, he told me that he had never seen different kinds of people, the way he grew up. He had never been to a movie theater. He saw Dr. Jekyll and Mr. Hyde very early on, which I'm surprised they took him to that.
[1:29] Something to help you sleep at night. — Yeah. They put him in front of the class. They made him sit in the front because he couldn't speak English. — Oh, man. — And he said he was really kind of terrified. He didn't know any... — It had to be traumatic, man.
[1:43] They all made huge sacrifices to come to the United States and more especially to become Americans. — Well, I think that people were looking for a life, but that's a big journey to leave your language, your culture, everything you know, your family, and to go it alone.
[2:01] And so someone like him, I look at him and I say, that's the reason why I'm doing well and that I'm talking to you. It's because of him.'''
]
